// Code generated by MockGen. DO NOT EDIT.
// Source: regrab_usecase.go
//
// Generated by this command:
//
//	mockgen -source=regrab_usecase.go -destination=mocks/regrab_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	regrab "github.com/alexmorbo/seasonfill/application/regrab"
	scan "github.com/alexmorbo/seasonfill/application/scan"
	qbit "github.com/alexmorbo/seasonfill/infrastructure/qbit"
	domain "github.com/alexmorbo/seasonfill/internal/shared/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQbitClientFactory is a mock of QbitClientFactory interface.
type MockQbitClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockQbitClientFactoryMockRecorder
	isgomock struct{}
}

// MockQbitClientFactoryMockRecorder is the mock recorder for MockQbitClientFactory.
type MockQbitClientFactoryMockRecorder struct {
	mock *MockQbitClientFactory
}

// NewMockQbitClientFactory creates a new mock instance.
func NewMockQbitClientFactory(ctrl *gomock.Controller) *MockQbitClientFactory {
	mock := &MockQbitClientFactory{ctrl: ctrl}
	mock.recorder = &MockQbitClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQbitClientFactory) EXPECT() *MockQbitClientFactoryMockRecorder {
	return m.recorder
}

// NewClient mocks base method.
func (m *MockQbitClientFactory) NewClient(s regrab.Settings) (qbit.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClient", s)
	ret0, _ := ret[0].(qbit.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClient indicates an expected call of NewClient.
func (mr *MockQbitClientFactoryMockRecorder) NewClient(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockQbitClientFactory)(nil).NewClient), s)
}

// MockDetectorFactory is a mock of DetectorFactory interface.
type MockDetectorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockDetectorFactoryMockRecorder
	isgomock struct{}
}

// MockDetectorFactoryMockRecorder is the mock recorder for MockDetectorFactory.
type MockDetectorFactoryMockRecorder struct {
	mock *MockDetectorFactory
}

// NewMockDetectorFactory creates a new mock instance.
func NewMockDetectorFactory(ctrl *gomock.Controller) *MockDetectorFactory {
	mock := &MockDetectorFactory{ctrl: ctrl}
	mock.recorder = &MockDetectorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetectorFactory) EXPECT() *MockDetectorFactoryMockRecorder {
	return m.recorder
}

// NewDetector mocks base method.
func (m *MockDetectorFactory) NewDetector(c qbit.Client, customMsgs []string) regrab.Detector {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDetector", c, customMsgs)
	ret0, _ := ret[0].(regrab.Detector)
	return ret0
}

// NewDetector indicates an expected call of NewDetector.
func (mr *MockDetectorFactoryMockRecorder) NewDetector(c, customMsgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDetector", reflect.TypeOf((*MockDetectorFactory)(nil).NewDetector), c, customMsgs)
}

// MockDetector is a mock of Detector interface.
type MockDetector struct {
	ctrl     *gomock.Controller
	recorder *MockDetectorMockRecorder
	isgomock struct{}
}

// MockDetectorMockRecorder is the mock recorder for MockDetector.
type MockDetectorMockRecorder struct {
	mock *MockDetector
}

// NewMockDetector creates a new mock instance.
func NewMockDetector(ctrl *gomock.Controller) *MockDetector {
	mock := &MockDetector{ctrl: ctrl}
	mock.recorder = &MockDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetector) EXPECT() *MockDetectorMockRecorder {
	return m.recorder
}

// Detect mocks base method.
func (m *MockDetector) Detect(ctx context.Context, hash string) (qbit.DetectionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detect", ctx, hash)
	ret0, _ := ret[0].(qbit.DetectionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detect indicates an expected call of Detect.
func (mr *MockDetectorMockRecorder) Detect(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detect", reflect.TypeOf((*MockDetector)(nil).Detect), ctx, hash)
}

// MockSettingsLookup is a mock of SettingsLookup interface.
type MockSettingsLookup struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsLookupMockRecorder
	isgomock struct{}
}

// MockSettingsLookupMockRecorder is the mock recorder for MockSettingsLookup.
type MockSettingsLookupMockRecorder struct {
	mock *MockSettingsLookup
}

// NewMockSettingsLookup creates a new mock instance.
func NewMockSettingsLookup(ctrl *gomock.Controller) *MockSettingsLookup {
	mock := &MockSettingsLookup{ctrl: ctrl}
	mock.recorder = &MockSettingsLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsLookup) EXPECT() *MockSettingsLookupMockRecorder {
	return m.recorder
}

// Lookup mocks base method.
func (m *MockSettingsLookup) Lookup(ctx context.Context, instanceName domain.InstanceName) (regrab.Settings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", ctx, instanceName)
	ret0, _ := ret[0].(regrab.Settings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockSettingsLookupMockRecorder) Lookup(ctx, instanceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockSettingsLookup)(nil).Lookup), ctx, instanceName)
}

// MockInstanceRegistry is a mock of InstanceRegistry interface.
type MockInstanceRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockInstanceRegistryMockRecorder
	isgomock struct{}
}

// MockInstanceRegistryMockRecorder is the mock recorder for MockInstanceRegistry.
type MockInstanceRegistryMockRecorder struct {
	mock *MockInstanceRegistry
}

// NewMockInstanceRegistry creates a new mock instance.
func NewMockInstanceRegistry(ctrl *gomock.Controller) *MockInstanceRegistry {
	mock := &MockInstanceRegistry{ctrl: ctrl}
	mock.recorder = &MockInstanceRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanceRegistry) EXPECT() *MockInstanceRegistryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockInstanceRegistry) Get(name string) (scan.Instance, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(scan.Instance)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInstanceRegistryMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInstanceRegistry)(nil).Get), name)
}
