// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexmorbo/seasonfill/infrastructure/qbit (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=mocks/qbit_mock.go -package=mocks github.com/alexmorbo/seasonfill/infrastructure/qbit Client
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	qbit "github.com/alexmorbo/seasonfill/infrastructure/qbit"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// GetTrackers mocks base method.
func (m *MockClient) GetTrackers(ctx context.Context, hash string) ([]qbit.Tracker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrackers", ctx, hash)
	ret0, _ := ret[0].([]qbit.Tracker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrackers indicates an expected call of GetTrackers.
func (mr *MockClientMockRecorder) GetTrackers(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrackers", reflect.TypeOf((*MockClient)(nil).GetTrackers), ctx, hash)
}

// ListTorrents mocks base method.
func (m *MockClient) ListTorrents(ctx context.Context) ([]qbit.Torrent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTorrents", ctx)
	ret0, _ := ret[0].([]qbit.Torrent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTorrents indicates an expected call of ListTorrents.
func (mr *MockClientMockRecorder) ListTorrents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTorrents", reflect.TypeOf((*MockClient)(nil).ListTorrents), ctx)
}

// Login mocks base method.
func (m *MockClient) Login(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockClientMockRecorder) Login(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockClient)(nil).Login), ctx)
}

// NewSyncSession mocks base method.
func (m *MockClient) NewSyncSession(ctx context.Context) (qbit.SyncSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSyncSession", ctx)
	ret0, _ := ret[0].(qbit.SyncSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSyncSession indicates an expected call of NewSyncSession.
func (mr *MockClientMockRecorder) NewSyncSession(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSyncSession", reflect.TypeOf((*MockClient)(nil).NewSyncSession), ctx)
}

// Ping mocks base method.
func (m *MockClient) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockClientMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockClient)(nil).Ping), ctx)
}
