// Package auth hosts the admin bounded context's application services —
// Bootstrap (first-run password seed), OIDCLoginUseCase (PKCE + group
// ACL), OIDCTestUseCase (operator pre-flight against runtime_config),
// and IPLimiter (login + webhook rate limit). The directory name is
// `app` (PRD §3.2 layout) but the Go package keeps its established
// short name `auth` so consumers' import paths churn only on the
// trailing path segment without an alias rename. A later normalization
// story can rename `auth` → `app` everywhere (with operator-supplied
// aliases) once the dust on Phase 1 has settled.
//
// ports.go gathers the narrow port interfaces and exported entry-points
// this layer publishes to its consumers. The interfaces themselves are
// declared in their owning files (so the production impl + test fakes
// live next to the interface that constrains them) — this file is an
// index pointing at each port so future readers can find the contract
// surface without grepping. Story 428 (A-1-2) carved out the bounded
// context; story 429+ will move the operator-visible AdminUserRepository
// interface decl OUT of application/ports and into this file as part of
// the "ports.go is the contract" convention. Until then, see:
//
//   - Bootstrap (bootstrap.go) — first-run idempotent password seed.
//     Accepts a ports.AdminUserRepository (the legacy catch-all port
//     declaration that still lives in application/ports — story 429
//     relocates it here). Auto-generates a 24-char password and WARN-
//     logs the plaintext when neither WebPassword nor WebPasswordHash
//     is supplied; flips AutoGenerated=false on first explicit set.
//
//   - OIDCLoginUseCase (oidc_login_usecase.go) — Start/Callback driver.
//     Owns the PKCE state/nonce roundtrip, derives the redirect URL
//     from RequestInfo when runtime_config omits it, enforces the
//     group ACL, and auto-creates the single-user admin record by
//     oidc_subject on first login.
//
//   - OIDCTestUseCase (oidc_test_usecase.go) — operator pre-flight
//     against a candidate runtime_config row. Discovers the issuer
//     without persisting, exchanges a test code if supplied, and
//     reports back which group(s) the user would match.
//
//   - IPLimiter (ratelimit.go) — IP-keyed (login) and instance-keyed
//     (webhook 021a-2) token bucket map with bounded LRU eviction
//     (HIGH-S3). The webhook receiver reuses this same type — see
//     interface/http/handlers/webhook*.go.
//
// Cross-package consumers (interface/http/handlers + middleware,
// infrastructure/reload, cmd/server/wiring) import these names directly
// from package auth via the import path
// `github.com/alexmorbo/seasonfill/internal/admin/app` — the bare
// package identifier `auth` survived the story 428 move unchanged.

package auth
