package wiring

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/alexmorbo/seasonfill/application/bootstrap"
	"github.com/alexmorbo/seasonfill/infrastructure/database/repositories"
	adminpersistence "github.com/alexmorbo/seasonfill/internal/admin/persistence"
	adminrest "github.com/alexmorbo/seasonfill/internal/admin/rest"
	catalogpersistence "github.com/alexmorbo/seasonfill/internal/catalog/persistence"
	"github.com/alexmorbo/seasonfill/internal/config"
	"github.com/alexmorbo/seasonfill/internal/runtime/crypto"
	"github.com/alexmorbo/seasonfill/internal/runtime/tz"
	database "github.com/alexmorbo/seasonfill/internal/shared/db"
	sharedports "github.com/alexmorbo/seasonfill/internal/shared/ports"

	"gorm.io/gorm"
)

// PersistenceBundle holds the database handle and the bedrock
// repositories + crypto primitives every other wiring constructor
// depends on. Returned by BuildPersistence.
//
// MasterKey is the plaintext AES-GCM key resolved or generated by
// bootstrap.ResolveAPIKey. It is later embedded in config.Auth.APIKey
// so the HTTP auth layer can compare against the X-Api-Key header.
//
// TZResolver and TimezoneHandler share the same underlying *tz.Resolver
// instance — the handler is a thin HTTP wrapper. Exposing both on the
// bundle lets server.go thread the resolver into scheduler factories
// (which call tzResolver.Get()) without re-deriving it.
type PersistenceBundle struct {
	DB              *gorm.DB
	Cipher          *crypto.Cipher
	MasterKey       string
	RuntimeRepo     *catalogpersistence.RuntimeConfigRepository
	InstanceRepo    *repositories.SonarrInstanceRepository
	AppSettingsRepo *adminpersistence.AppSettingsRepository
	QuotaCounter    *adminpersistence.QuotaCounterRepository
	TZResolver      *tz.Resolver
	TimezoneHandler *adminrest.TimezoneHandler
}

// BuildPersistence opens the database, runs migrations, derives the
// master key + cipher via the tempRuntimeRepo→permanent dance, and
// constructs the bedrock repositories used by every later wirer.
//
// The ctx parameter is reserved for future use — the current body
// uses a background context for the early DB reads (ResolveAPIKey,
// tz.New) to mirror the pre-refactor behaviour: those reads must
// complete even if the parent ctx already carries a deadline applied
// by an outer test harness. Plumbing the parent ctx here would
// change the cancel semantics (e.g. signal-driven test shutdown
// could race the early reads). Out of scope for B-11.
func BuildPersistence(
	ctx context.Context,
	cfg *config.Bootstrap,
	log *slog.Logger,
) (*PersistenceBundle, error) {
	_ = ctx
	bgCtx := context.Background()

	db, err := database.Open(cfg.Database)
	if err != nil {
		return nil, fmt.Errorf("open db: %w", err)
	}
	if err := database.Migrate(db); err != nil {
		return nil, fmt.Errorf("migrate: %w", err)
	}

	instanceRepo := repositories.NewSonarrInstanceRepository(db)

	// Temporary repo without cipher to resolve the API key first.
	// Then rebuild the repo with the derived cipher so encrypted
	// columns (api_key, oidc_client_secret) can be written/read.
	tempRuntimeRepo := catalogpersistence.NewRuntimeConfigRepository(db, nil)
	masterKey, err := bootstrap.ResolveAPIKey(bgCtx, cfg.Auth.APIKey, tempRuntimeRepo, log)
	if err != nil {
		return nil, fmt.Errorf("resolve api key: %w", err)
	}
	cipher, err := crypto.New(masterKey)
	if err != nil {
		return nil, fmt.Errorf("derive cipher: %w", err)
	}
	runtimeRepo := catalogpersistence.NewRuntimeConfigRepository(db, cipher)

	// Story 301: app-level settings (id=1) — currently only the
	// operator-selected timezone. Built early so the scheduler
	// factory and the HTTP handler share the same Resolver. The
	// store is the GORM-backed app_settings repo; the v36 seed
	// guarantees a singleton row exists.
	appSettingsRepo := adminpersistence.NewAppSettingsRepository(db)
	// F-4b-8: tz resolver loads the operator timezone at boot —
	// configuration-resolution records belong to the "boot" slot.
	tzResolver := tz.New(bgCtx, appSettingsRepo, sharedports.DomainLogger(log, "boot"))
	log.Info("timezone resolver",
		slog.String("name", tzResolver.Name()),
		slog.String("source", string(tzResolver.Source())))
	timezoneHandler := adminrest.NewTimezoneHandler(tzResolver, log)

	// Story 305: generic DB-backed rate-limit counter. Currently
	// consumed by the OMDb budget guard (replaces the in-process
	// counter that zeroed on every pod restart). Other external-
	// service clients can opt in by injecting `quotaCounter` and
	// switching their guard to the QuotaCounter port.
	quotaCounter := adminpersistence.NewQuotaCounterRepository(db)

	return &PersistenceBundle{
		DB:              db,
		Cipher:          cipher,
		MasterKey:       masterKey,
		RuntimeRepo:     runtimeRepo,
		InstanceRepo:    instanceRepo,
		AppSettingsRepo: appSettingsRepo,
		QuotaCounter:    quotaCounter,
		TZResolver:      tzResolver,
		TimezoneHandler: timezoneHandler,
	}, nil
}
