// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package dataports

import (
	"context"
	"sync"
	"time"
)

// Ensure, that OutboxRepositoryMock does implement OutboxRepository.
// If this is not the case, regenerate this file with moq.
var _ OutboxRepository = &OutboxRepositoryMock{}

// OutboxRepositoryMock is a mock implementation of OutboxRepository.
//
//	func TestSomethingThatUsesOutboxRepository(t *testing.T) {
//
//		// make and configure a mocked OutboxRepository
//		mockedOutboxRepository := &OutboxRepositoryMock{
//			CountPendingFunc: func(ctx context.Context) (int64, error) {
//				panic("mock out the CountPending method")
//			},
//			FetchDueBatchFunc: func(ctx context.Context, now time.Time, limit int) ([]OutboxRow, error) {
//				panic("mock out the FetchDueBatch method")
//			},
//			InsertFunc: func(ctx context.Context, row OutboxRow) error {
//				panic("mock out the Insert method")
//			},
//			MarkDeadFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the MarkDead method")
//			},
//			MarkSentFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the MarkSent method")
//			},
//			RescheduleFunc: func(ctx context.Context, id int64, nextAttemptAt time.Time) error {
//				panic("mock out the Reschedule method")
//			},
//		}
//
//		// use mockedOutboxRepository in code that requires OutboxRepository
//		// and then make assertions.
//
//	}
type OutboxRepositoryMock struct {
	// CountPendingFunc mocks the CountPending method.
	CountPendingFunc func(ctx context.Context) (int64, error)

	// FetchDueBatchFunc mocks the FetchDueBatch method.
	FetchDueBatchFunc func(ctx context.Context, now time.Time, limit int) ([]OutboxRow, error)

	// InsertFunc mocks the Insert method.
	InsertFunc func(ctx context.Context, row OutboxRow) error

	// MarkDeadFunc mocks the MarkDead method.
	MarkDeadFunc func(ctx context.Context, id int64) error

	// MarkSentFunc mocks the MarkSent method.
	MarkSentFunc func(ctx context.Context, id int64) error

	// RescheduleFunc mocks the Reschedule method.
	RescheduleFunc func(ctx context.Context, id int64, nextAttemptAt time.Time) error

	// calls tracks calls to the methods.
	calls struct {
		// CountPending holds details about calls to the CountPending method.
		CountPending []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// FetchDueBatch holds details about calls to the FetchDueBatch method.
		FetchDueBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Now is the now argument value.
			Now time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// Insert holds details about calls to the Insert method.
		Insert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Row is the row argument value.
			Row OutboxRow
		}
		// MarkDead holds details about calls to the MarkDead method.
		MarkDead []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// MarkSent holds details about calls to the MarkSent method.
		MarkSent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Reschedule holds details about calls to the Reschedule method.
		Reschedule []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// NextAttemptAt is the nextAttemptAt argument value.
			NextAttemptAt time.Time
		}
	}
	lockCountPending  sync.RWMutex
	lockFetchDueBatch sync.RWMutex
	lockInsert        sync.RWMutex
	lockMarkDead      sync.RWMutex
	lockMarkSent      sync.RWMutex
	lockReschedule    sync.RWMutex
}

// CountPending calls CountPendingFunc.
func (mock *OutboxRepositoryMock) CountPending(ctx context.Context) (int64, error) {
	if mock.CountPendingFunc == nil {
		panic("OutboxRepositoryMock.CountPendingFunc: method is nil but OutboxRepository.CountPending was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountPending.Lock()
	mock.calls.CountPending = append(mock.calls.CountPending, callInfo)
	mock.lockCountPending.Unlock()
	return mock.CountPendingFunc(ctx)
}

// CountPendingCalls gets all the calls that were made to CountPending.
// Check the length with:
//
//	len(mockedOutboxRepository.CountPendingCalls())
func (mock *OutboxRepositoryMock) CountPendingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountPending.RLock()
	calls = mock.calls.CountPending
	mock.lockCountPending.RUnlock()
	return calls
}

// FetchDueBatch calls FetchDueBatchFunc.
func (mock *OutboxRepositoryMock) FetchDueBatch(ctx context.Context, now time.Time, limit int) ([]OutboxRow, error) {
	if mock.FetchDueBatchFunc == nil {
		panic("OutboxRepositoryMock.FetchDueBatchFunc: method is nil but OutboxRepository.FetchDueBatch was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Now   time.Time
		Limit int
	}{
		Ctx:   ctx,
		Now:   now,
		Limit: limit,
	}
	mock.lockFetchDueBatch.Lock()
	mock.calls.FetchDueBatch = append(mock.calls.FetchDueBatch, callInfo)
	mock.lockFetchDueBatch.Unlock()
	return mock.FetchDueBatchFunc(ctx, now, limit)
}

// FetchDueBatchCalls gets all the calls that were made to FetchDueBatch.
// Check the length with:
//
//	len(mockedOutboxRepository.FetchDueBatchCalls())
func (mock *OutboxRepositoryMock) FetchDueBatchCalls() []struct {
	Ctx   context.Context
	Now   time.Time
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Now   time.Time
		Limit int
	}
	mock.lockFetchDueBatch.RLock()
	calls = mock.calls.FetchDueBatch
	mock.lockFetchDueBatch.RUnlock()
	return calls
}

// Insert calls InsertFunc.
func (mock *OutboxRepositoryMock) Insert(ctx context.Context, row OutboxRow) error {
	if mock.InsertFunc == nil {
		panic("OutboxRepositoryMock.InsertFunc: method is nil but OutboxRepository.Insert was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Row OutboxRow
	}{
		Ctx: ctx,
		Row: row,
	}
	mock.lockInsert.Lock()
	mock.calls.Insert = append(mock.calls.Insert, callInfo)
	mock.lockInsert.Unlock()
	return mock.InsertFunc(ctx, row)
}

// InsertCalls gets all the calls that were made to Insert.
// Check the length with:
//
//	len(mockedOutboxRepository.InsertCalls())
func (mock *OutboxRepositoryMock) InsertCalls() []struct {
	Ctx context.Context
	Row OutboxRow
} {
	var calls []struct {
		Ctx context.Context
		Row OutboxRow
	}
	mock.lockInsert.RLock()
	calls = mock.calls.Insert
	mock.lockInsert.RUnlock()
	return calls
}

// MarkDead calls MarkDeadFunc.
func (mock *OutboxRepositoryMock) MarkDead(ctx context.Context, id int64) error {
	if mock.MarkDeadFunc == nil {
		panic("OutboxRepositoryMock.MarkDeadFunc: method is nil but OutboxRepository.MarkDead was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockMarkDead.Lock()
	mock.calls.MarkDead = append(mock.calls.MarkDead, callInfo)
	mock.lockMarkDead.Unlock()
	return mock.MarkDeadFunc(ctx, id)
}

// MarkDeadCalls gets all the calls that were made to MarkDead.
// Check the length with:
//
//	len(mockedOutboxRepository.MarkDeadCalls())
func (mock *OutboxRepositoryMock) MarkDeadCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockMarkDead.RLock()
	calls = mock.calls.MarkDead
	mock.lockMarkDead.RUnlock()
	return calls
}

// MarkSent calls MarkSentFunc.
func (mock *OutboxRepositoryMock) MarkSent(ctx context.Context, id int64) error {
	if mock.MarkSentFunc == nil {
		panic("OutboxRepositoryMock.MarkSentFunc: method is nil but OutboxRepository.MarkSent was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockMarkSent.Lock()
	mock.calls.MarkSent = append(mock.calls.MarkSent, callInfo)
	mock.lockMarkSent.Unlock()
	return mock.MarkSentFunc(ctx, id)
}

// MarkSentCalls gets all the calls that were made to MarkSent.
// Check the length with:
//
//	len(mockedOutboxRepository.MarkSentCalls())
func (mock *OutboxRepositoryMock) MarkSentCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockMarkSent.RLock()
	calls = mock.calls.MarkSent
	mock.lockMarkSent.RUnlock()
	return calls
}

// Reschedule calls RescheduleFunc.
func (mock *OutboxRepositoryMock) Reschedule(ctx context.Context, id int64, nextAttemptAt time.Time) error {
	if mock.RescheduleFunc == nil {
		panic("OutboxRepositoryMock.RescheduleFunc: method is nil but OutboxRepository.Reschedule was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ID            int64
		NextAttemptAt time.Time
	}{
		Ctx:           ctx,
		ID:            id,
		NextAttemptAt: nextAttemptAt,
	}
	mock.lockReschedule.Lock()
	mock.calls.Reschedule = append(mock.calls.Reschedule, callInfo)
	mock.lockReschedule.Unlock()
	return mock.RescheduleFunc(ctx, id, nextAttemptAt)
}

// RescheduleCalls gets all the calls that were made to Reschedule.
// Check the length with:
//
//	len(mockedOutboxRepository.RescheduleCalls())
func (mock *OutboxRepositoryMock) RescheduleCalls() []struct {
	Ctx           context.Context
	ID            int64
	NextAttemptAt time.Time
} {
	var calls []struct {
		Ctx           context.Context
		ID            int64
		NextAttemptAt time.Time
	}
	mock.lockReschedule.RLock()
	calls = mock.calls.Reschedule
	mock.lockReschedule.RUnlock()
	return calls
}
