// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package dataports

import (
	"context"
	"sync"
)

// Ensure, that NotificationAgentRepositoryMock does implement NotificationAgentRepository.
// If this is not the case, regenerate this file with moq.
var _ NotificationAgentRepository = &NotificationAgentRepositoryMock{}

// NotificationAgentRepositoryMock is a mock implementation of NotificationAgentRepository.
//
//	func TestSomethingThatUsesNotificationAgentRepository(t *testing.T) {
//
//		// make and configure a mocked NotificationAgentRepository
//		mockedNotificationAgentRepository := &NotificationAgentRepositoryMock{
//			CreateFunc: func(ctx context.Context, ownerID int64, a NotificationAgent) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (NotificationAgent, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context) ([]NotificationAgent, error) {
//				panic("mock out the List method")
//			},
//			ListEnabledForEventFunc: func(ctx context.Context, eventType string) ([]NotificationAgent, error) {
//				panic("mock out the ListEnabledForEvent method")
//			},
//			UpdateFunc: func(ctx context.Context, id int64, name string, enabled bool, eventTypes []string, newConfig []byte) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedNotificationAgentRepository in code that requires NotificationAgentRepository
//		// and then make assertions.
//
//	}
type NotificationAgentRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, ownerID int64, a NotificationAgent) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (NotificationAgent, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]NotificationAgent, error)

	// ListEnabledForEventFunc mocks the ListEnabledForEvent method.
	ListEnabledForEventFunc func(ctx context.Context, eventType string) ([]NotificationAgent, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id int64, name string, enabled bool, eventTypes []string, newConfig []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OwnerID is the ownerID argument value.
			OwnerID int64
			// A is the a argument value.
			A NotificationAgent
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListEnabledForEvent holds details about calls to the ListEnabledForEvent method.
		ListEnabledForEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EventType is the eventType argument value.
			EventType string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Name is the name argument value.
			Name string
			// Enabled is the enabled argument value.
			Enabled bool
			// EventTypes is the eventTypes argument value.
			EventTypes []string
			// NewConfig is the newConfig argument value.
			NewConfig []byte
		}
	}
	lockCreate              sync.RWMutex
	lockDelete              sync.RWMutex
	lockGet                 sync.RWMutex
	lockList                sync.RWMutex
	lockListEnabledForEvent sync.RWMutex
	lockUpdate              sync.RWMutex
}

// Create calls CreateFunc.
func (mock *NotificationAgentRepositoryMock) Create(ctx context.Context, ownerID int64, a NotificationAgent) (int64, error) {
	if mock.CreateFunc == nil {
		panic("NotificationAgentRepositoryMock.CreateFunc: method is nil but NotificationAgentRepository.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OwnerID int64
		A       NotificationAgent
	}{
		Ctx:     ctx,
		OwnerID: ownerID,
		A:       a,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, ownerID, a)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.CreateCalls())
func (mock *NotificationAgentRepositoryMock) CreateCalls() []struct {
	Ctx     context.Context
	OwnerID int64
	A       NotificationAgent
} {
	var calls []struct {
		Ctx     context.Context
		OwnerID int64
		A       NotificationAgent
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *NotificationAgentRepositoryMock) Delete(ctx context.Context, id int64) error {
	if mock.DeleteFunc == nil {
		panic("NotificationAgentRepositoryMock.DeleteFunc: method is nil but NotificationAgentRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.DeleteCalls())
func (mock *NotificationAgentRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *NotificationAgentRepositoryMock) Get(ctx context.Context, id int64) (NotificationAgent, error) {
	if mock.GetFunc == nil {
		panic("NotificationAgentRepositoryMock.GetFunc: method is nil but NotificationAgentRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.GetCalls())
func (mock *NotificationAgentRepositoryMock) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *NotificationAgentRepositoryMock) List(ctx context.Context) ([]NotificationAgent, error) {
	if mock.ListFunc == nil {
		panic("NotificationAgentRepositoryMock.ListFunc: method is nil but NotificationAgentRepository.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.ListCalls())
func (mock *NotificationAgentRepositoryMock) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListEnabledForEvent calls ListEnabledForEventFunc.
func (mock *NotificationAgentRepositoryMock) ListEnabledForEvent(ctx context.Context, eventType string) ([]NotificationAgent, error) {
	if mock.ListEnabledForEventFunc == nil {
		panic("NotificationAgentRepositoryMock.ListEnabledForEventFunc: method is nil but NotificationAgentRepository.ListEnabledForEvent was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		EventType string
	}{
		Ctx:       ctx,
		EventType: eventType,
	}
	mock.lockListEnabledForEvent.Lock()
	mock.calls.ListEnabledForEvent = append(mock.calls.ListEnabledForEvent, callInfo)
	mock.lockListEnabledForEvent.Unlock()
	return mock.ListEnabledForEventFunc(ctx, eventType)
}

// ListEnabledForEventCalls gets all the calls that were made to ListEnabledForEvent.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.ListEnabledForEventCalls())
func (mock *NotificationAgentRepositoryMock) ListEnabledForEventCalls() []struct {
	Ctx       context.Context
	EventType string
} {
	var calls []struct {
		Ctx       context.Context
		EventType string
	}
	mock.lockListEnabledForEvent.RLock()
	calls = mock.calls.ListEnabledForEvent
	mock.lockListEnabledForEvent.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *NotificationAgentRepositoryMock) Update(ctx context.Context, id int64, name string, enabled bool, eventTypes []string, newConfig []byte) error {
	if mock.UpdateFunc == nil {
		panic("NotificationAgentRepositoryMock.UpdateFunc: method is nil but NotificationAgentRepository.Update was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ID         int64
		Name       string
		Enabled    bool
		EventTypes []string
		NewConfig  []byte
	}{
		Ctx:        ctx,
		ID:         id,
		Name:       name,
		Enabled:    enabled,
		EventTypes: eventTypes,
		NewConfig:  newConfig,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, name, enabled, eventTypes, newConfig)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.UpdateCalls())
func (mock *NotificationAgentRepositoryMock) UpdateCalls() []struct {
	Ctx        context.Context
	ID         int64
	Name       string
	Enabled    bool
	EventTypes []string
	NewConfig  []byte
} {
	var calls []struct {
		Ctx        context.Context
		ID         int64
		Name       string
		Enabled    bool
		EventTypes []string
		NewConfig  []byte
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
