// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package dataports

import (
	"context"
	"sync"
)

// Ensure, that NotificationAgentRepositoryMock does implement NotificationAgentRepository.
// If this is not the case, regenerate this file with moq.
var _ NotificationAgentRepository = &NotificationAgentRepositoryMock{}

// NotificationAgentRepositoryMock is a mock implementation of NotificationAgentRepository.
//
//	func TestSomethingThatUsesNotificationAgentRepository(t *testing.T) {
//
//		// make and configure a mocked NotificationAgentRepository
//		mockedNotificationAgentRepository := &NotificationAgentRepositoryMock{
//			CreateFunc: func(ctx context.Context, ownerID int64, a NotificationAgent) (int64, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64, ownerID int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64, ownerID int64) (NotificationAgent, error) {
//				panic("mock out the Get method")
//			},
//			ListByOwnerFunc: func(ctx context.Context, ownerID int64) ([]NotificationAgent, error) {
//				panic("mock out the ListByOwner method")
//			},
//			ListEnabledForEventAndUserFunc: func(ctx context.Context, eventType string, userID int64) ([]NotificationAgent, error) {
//				panic("mock out the ListEnabledForEventAndUser method")
//			},
//			UpdateFunc: func(ctx context.Context, id int64, ownerID int64, name string, enabled bool, eventTypes []string, newConfig []byte) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedNotificationAgentRepository in code that requires NotificationAgentRepository
//		// and then make assertions.
//
//	}
type NotificationAgentRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, ownerID int64, a NotificationAgent) (int64, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64, ownerID int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64, ownerID int64) (NotificationAgent, error)

	// ListByOwnerFunc mocks the ListByOwner method.
	ListByOwnerFunc func(ctx context.Context, ownerID int64) ([]NotificationAgent, error)

	// ListEnabledForEventAndUserFunc mocks the ListEnabledForEventAndUser method.
	ListEnabledForEventAndUserFunc func(ctx context.Context, eventType string, userID int64) ([]NotificationAgent, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id int64, ownerID int64, name string, enabled bool, eventTypes []string, newConfig []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OwnerID is the ownerID argument value.
			OwnerID int64
			// A is the a argument value.
			A NotificationAgent
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// OwnerID is the ownerID argument value.
			OwnerID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// OwnerID is the ownerID argument value.
			OwnerID int64
		}
		// ListByOwner holds details about calls to the ListByOwner method.
		ListByOwner []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OwnerID is the ownerID argument value.
			OwnerID int64
		}
		// ListEnabledForEventAndUser holds details about calls to the ListEnabledForEventAndUser method.
		ListEnabledForEventAndUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EventType is the eventType argument value.
			EventType string
			// UserID is the userID argument value.
			UserID int64
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// OwnerID is the ownerID argument value.
			OwnerID int64
			// Name is the name argument value.
			Name string
			// Enabled is the enabled argument value.
			Enabled bool
			// EventTypes is the eventTypes argument value.
			EventTypes []string
			// NewConfig is the newConfig argument value.
			NewConfig []byte
		}
	}
	lockCreate                     sync.RWMutex
	lockDelete                     sync.RWMutex
	lockGet                        sync.RWMutex
	lockListByOwner                sync.RWMutex
	lockListEnabledForEventAndUser sync.RWMutex
	lockUpdate                     sync.RWMutex
}

// Create calls CreateFunc.
func (mock *NotificationAgentRepositoryMock) Create(ctx context.Context, ownerID int64, a NotificationAgent) (int64, error) {
	if mock.CreateFunc == nil {
		panic("NotificationAgentRepositoryMock.CreateFunc: method is nil but NotificationAgentRepository.Create was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OwnerID int64
		A       NotificationAgent
	}{
		Ctx:     ctx,
		OwnerID: ownerID,
		A:       a,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, ownerID, a)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.CreateCalls())
func (mock *NotificationAgentRepositoryMock) CreateCalls() []struct {
	Ctx     context.Context
	OwnerID int64
	A       NotificationAgent
} {
	var calls []struct {
		Ctx     context.Context
		OwnerID int64
		A       NotificationAgent
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *NotificationAgentRepositoryMock) Delete(ctx context.Context, id int64, ownerID int64) error {
	if mock.DeleteFunc == nil {
		panic("NotificationAgentRepositoryMock.DeleteFunc: method is nil but NotificationAgentRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ID      int64
		OwnerID int64
	}{
		Ctx:     ctx,
		ID:      id,
		OwnerID: ownerID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id, ownerID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.DeleteCalls())
func (mock *NotificationAgentRepositoryMock) DeleteCalls() []struct {
	Ctx     context.Context
	ID      int64
	OwnerID int64
} {
	var calls []struct {
		Ctx     context.Context
		ID      int64
		OwnerID int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *NotificationAgentRepositoryMock) Get(ctx context.Context, id int64, ownerID int64) (NotificationAgent, error) {
	if mock.GetFunc == nil {
		panic("NotificationAgentRepositoryMock.GetFunc: method is nil but NotificationAgentRepository.Get was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ID      int64
		OwnerID int64
	}{
		Ctx:     ctx,
		ID:      id,
		OwnerID: ownerID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id, ownerID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.GetCalls())
func (mock *NotificationAgentRepositoryMock) GetCalls() []struct {
	Ctx     context.Context
	ID      int64
	OwnerID int64
} {
	var calls []struct {
		Ctx     context.Context
		ID      int64
		OwnerID int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ListByOwner calls ListByOwnerFunc.
func (mock *NotificationAgentRepositoryMock) ListByOwner(ctx context.Context, ownerID int64) ([]NotificationAgent, error) {
	if mock.ListByOwnerFunc == nil {
		panic("NotificationAgentRepositoryMock.ListByOwnerFunc: method is nil but NotificationAgentRepository.ListByOwner was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OwnerID int64
	}{
		Ctx:     ctx,
		OwnerID: ownerID,
	}
	mock.lockListByOwner.Lock()
	mock.calls.ListByOwner = append(mock.calls.ListByOwner, callInfo)
	mock.lockListByOwner.Unlock()
	return mock.ListByOwnerFunc(ctx, ownerID)
}

// ListByOwnerCalls gets all the calls that were made to ListByOwner.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.ListByOwnerCalls())
func (mock *NotificationAgentRepositoryMock) ListByOwnerCalls() []struct {
	Ctx     context.Context
	OwnerID int64
} {
	var calls []struct {
		Ctx     context.Context
		OwnerID int64
	}
	mock.lockListByOwner.RLock()
	calls = mock.calls.ListByOwner
	mock.lockListByOwner.RUnlock()
	return calls
}

// ListEnabledForEventAndUser calls ListEnabledForEventAndUserFunc.
func (mock *NotificationAgentRepositoryMock) ListEnabledForEventAndUser(ctx context.Context, eventType string, userID int64) ([]NotificationAgent, error) {
	if mock.ListEnabledForEventAndUserFunc == nil {
		panic("NotificationAgentRepositoryMock.ListEnabledForEventAndUserFunc: method is nil but NotificationAgentRepository.ListEnabledForEventAndUser was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		EventType string
		UserID    int64
	}{
		Ctx:       ctx,
		EventType: eventType,
		UserID:    userID,
	}
	mock.lockListEnabledForEventAndUser.Lock()
	mock.calls.ListEnabledForEventAndUser = append(mock.calls.ListEnabledForEventAndUser, callInfo)
	mock.lockListEnabledForEventAndUser.Unlock()
	return mock.ListEnabledForEventAndUserFunc(ctx, eventType, userID)
}

// ListEnabledForEventAndUserCalls gets all the calls that were made to ListEnabledForEventAndUser.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.ListEnabledForEventAndUserCalls())
func (mock *NotificationAgentRepositoryMock) ListEnabledForEventAndUserCalls() []struct {
	Ctx       context.Context
	EventType string
	UserID    int64
} {
	var calls []struct {
		Ctx       context.Context
		EventType string
		UserID    int64
	}
	mock.lockListEnabledForEventAndUser.RLock()
	calls = mock.calls.ListEnabledForEventAndUser
	mock.lockListEnabledForEventAndUser.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *NotificationAgentRepositoryMock) Update(ctx context.Context, id int64, ownerID int64, name string, enabled bool, eventTypes []string, newConfig []byte) error {
	if mock.UpdateFunc == nil {
		panic("NotificationAgentRepositoryMock.UpdateFunc: method is nil but NotificationAgentRepository.Update was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ID         int64
		OwnerID    int64
		Name       string
		Enabled    bool
		EventTypes []string
		NewConfig  []byte
	}{
		Ctx:        ctx,
		ID:         id,
		OwnerID:    ownerID,
		Name:       name,
		Enabled:    enabled,
		EventTypes: eventTypes,
		NewConfig:  newConfig,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, ownerID, name, enabled, eventTypes, newConfig)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedNotificationAgentRepository.UpdateCalls())
func (mock *NotificationAgentRepositoryMock) UpdateCalls() []struct {
	Ctx        context.Context
	ID         int64
	OwnerID    int64
	Name       string
	Enabled    bool
	EventTypes []string
	NewConfig  []byte
} {
	var calls []struct {
		Ctx        context.Context
		ID         int64
		OwnerID    int64
		Name       string
		Enabled    bool
		EventTypes []string
		NewConfig  []byte
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
