// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package dataports

import (
	"context"
	"sync"
)

// Ensure, that RadarrClientMock does implement RadarrClient.
// If this is not the case, regenerate this file with moq.
var _ RadarrClient = &RadarrClientMock{}

// RadarrClientMock is a mock implementation of RadarrClient.
//
//	func TestSomethingThatUsesRadarrClient(t *testing.T) {
//
//		// make and configure a mocked RadarrClient
//		mockedRadarrClient := &RadarrClientMock{
//			AddMovieFunc: func(ctx context.Context, p AddMoviePayload) (AddMovieResult, error) {
//				panic("mock out the AddMovie method")
//			},
//			CreateTagFunc: func(ctx context.Context, label string) (Tag, error) {
//				panic("mock out the CreateTag method")
//			},
//			GetQualityProfileFunc: func(ctx context.Context, id int) (QualityProfile, error) {
//				panic("mock out the GetQualityProfile method")
//			},
//			ListMoviesFunc: func(ctx context.Context) ([]RadarrMovie, error) {
//				panic("mock out the ListMovies method")
//			},
//			ListQualityProfilesFunc: func(ctx context.Context) ([]QualityProfile, error) {
//				panic("mock out the ListQualityProfiles method")
//			},
//			ListRootFoldersFunc: func(ctx context.Context) ([]RootFolder, error) {
//				panic("mock out the ListRootFolders method")
//			},
//			ListTagsFunc: func(ctx context.Context) ([]Tag, error) {
//				panic("mock out the ListTags method")
//			},
//			LookupMovieFunc: func(ctx context.Context, term string) ([]RadarrLookupResult, error) {
//				panic("mock out the LookupMovie method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			SystemStatusFunc: func(ctx context.Context) (SystemStatus, error) {
//				panic("mock out the SystemStatus method")
//			},
//		}
//
//		// use mockedRadarrClient in code that requires RadarrClient
//		// and then make assertions.
//
//	}
type RadarrClientMock struct {
	// AddMovieFunc mocks the AddMovie method.
	AddMovieFunc func(ctx context.Context, p AddMoviePayload) (AddMovieResult, error)

	// CreateTagFunc mocks the CreateTag method.
	CreateTagFunc func(ctx context.Context, label string) (Tag, error)

	// GetQualityProfileFunc mocks the GetQualityProfile method.
	GetQualityProfileFunc func(ctx context.Context, id int) (QualityProfile, error)

	// ListMoviesFunc mocks the ListMovies method.
	ListMoviesFunc func(ctx context.Context) ([]RadarrMovie, error)

	// ListQualityProfilesFunc mocks the ListQualityProfiles method.
	ListQualityProfilesFunc func(ctx context.Context) ([]QualityProfile, error)

	// ListRootFoldersFunc mocks the ListRootFolders method.
	ListRootFoldersFunc func(ctx context.Context) ([]RootFolder, error)

	// ListTagsFunc mocks the ListTags method.
	ListTagsFunc func(ctx context.Context) ([]Tag, error)

	// LookupMovieFunc mocks the LookupMovie method.
	LookupMovieFunc func(ctx context.Context, term string) ([]RadarrLookupResult, error)

	// NameFunc mocks the Name method.
	NameFunc func() string

	// SystemStatusFunc mocks the SystemStatus method.
	SystemStatusFunc func(ctx context.Context) (SystemStatus, error)

	// calls tracks calls to the methods.
	calls struct {
		// AddMovie holds details about calls to the AddMovie method.
		AddMovie []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// P is the p argument value.
			P AddMoviePayload
		}
		// CreateTag holds details about calls to the CreateTag method.
		CreateTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Label is the label argument value.
			Label string
		}
		// GetQualityProfile holds details about calls to the GetQualityProfile method.
		GetQualityProfile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int
		}
		// ListMovies holds details about calls to the ListMovies method.
		ListMovies []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListQualityProfiles holds details about calls to the ListQualityProfiles method.
		ListQualityProfiles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListRootFolders holds details about calls to the ListRootFolders method.
		ListRootFolders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListTags holds details about calls to the ListTags method.
		ListTags []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// LookupMovie holds details about calls to the LookupMovie method.
		LookupMovie []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Term is the term argument value.
			Term string
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// SystemStatus holds details about calls to the SystemStatus method.
		SystemStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockAddMovie            sync.RWMutex
	lockCreateTag           sync.RWMutex
	lockGetQualityProfile   sync.RWMutex
	lockListMovies          sync.RWMutex
	lockListQualityProfiles sync.RWMutex
	lockListRootFolders     sync.RWMutex
	lockListTags            sync.RWMutex
	lockLookupMovie         sync.RWMutex
	lockName                sync.RWMutex
	lockSystemStatus        sync.RWMutex
}

// AddMovie calls AddMovieFunc.
func (mock *RadarrClientMock) AddMovie(ctx context.Context, p AddMoviePayload) (AddMovieResult, error) {
	if mock.AddMovieFunc == nil {
		panic("RadarrClientMock.AddMovieFunc: method is nil but RadarrClient.AddMovie was just called")
	}
	callInfo := struct {
		Ctx context.Context
		P   AddMoviePayload
	}{
		Ctx: ctx,
		P:   p,
	}
	mock.lockAddMovie.Lock()
	mock.calls.AddMovie = append(mock.calls.AddMovie, callInfo)
	mock.lockAddMovie.Unlock()
	return mock.AddMovieFunc(ctx, p)
}

// AddMovieCalls gets all the calls that were made to AddMovie.
// Check the length with:
//
//	len(mockedRadarrClient.AddMovieCalls())
func (mock *RadarrClientMock) AddMovieCalls() []struct {
	Ctx context.Context
	P   AddMoviePayload
} {
	var calls []struct {
		Ctx context.Context
		P   AddMoviePayload
	}
	mock.lockAddMovie.RLock()
	calls = mock.calls.AddMovie
	mock.lockAddMovie.RUnlock()
	return calls
}

// CreateTag calls CreateTagFunc.
func (mock *RadarrClientMock) CreateTag(ctx context.Context, label string) (Tag, error) {
	if mock.CreateTagFunc == nil {
		panic("RadarrClientMock.CreateTagFunc: method is nil but RadarrClient.CreateTag was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Label string
	}{
		Ctx:   ctx,
		Label: label,
	}
	mock.lockCreateTag.Lock()
	mock.calls.CreateTag = append(mock.calls.CreateTag, callInfo)
	mock.lockCreateTag.Unlock()
	return mock.CreateTagFunc(ctx, label)
}

// CreateTagCalls gets all the calls that were made to CreateTag.
// Check the length with:
//
//	len(mockedRadarrClient.CreateTagCalls())
func (mock *RadarrClientMock) CreateTagCalls() []struct {
	Ctx   context.Context
	Label string
} {
	var calls []struct {
		Ctx   context.Context
		Label string
	}
	mock.lockCreateTag.RLock()
	calls = mock.calls.CreateTag
	mock.lockCreateTag.RUnlock()
	return calls
}

// GetQualityProfile calls GetQualityProfileFunc.
func (mock *RadarrClientMock) GetQualityProfile(ctx context.Context, id int) (QualityProfile, error) {
	if mock.GetQualityProfileFunc == nil {
		panic("RadarrClientMock.GetQualityProfileFunc: method is nil but RadarrClient.GetQualityProfile was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetQualityProfile.Lock()
	mock.calls.GetQualityProfile = append(mock.calls.GetQualityProfile, callInfo)
	mock.lockGetQualityProfile.Unlock()
	return mock.GetQualityProfileFunc(ctx, id)
}

// GetQualityProfileCalls gets all the calls that were made to GetQualityProfile.
// Check the length with:
//
//	len(mockedRadarrClient.GetQualityProfileCalls())
func (mock *RadarrClientMock) GetQualityProfileCalls() []struct {
	Ctx context.Context
	ID  int
} {
	var calls []struct {
		Ctx context.Context
		ID  int
	}
	mock.lockGetQualityProfile.RLock()
	calls = mock.calls.GetQualityProfile
	mock.lockGetQualityProfile.RUnlock()
	return calls
}

// ListMovies calls ListMoviesFunc.
func (mock *RadarrClientMock) ListMovies(ctx context.Context) ([]RadarrMovie, error) {
	if mock.ListMoviesFunc == nil {
		panic("RadarrClientMock.ListMoviesFunc: method is nil but RadarrClient.ListMovies was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListMovies.Lock()
	mock.calls.ListMovies = append(mock.calls.ListMovies, callInfo)
	mock.lockListMovies.Unlock()
	return mock.ListMoviesFunc(ctx)
}

// ListMoviesCalls gets all the calls that were made to ListMovies.
// Check the length with:
//
//	len(mockedRadarrClient.ListMoviesCalls())
func (mock *RadarrClientMock) ListMoviesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListMovies.RLock()
	calls = mock.calls.ListMovies
	mock.lockListMovies.RUnlock()
	return calls
}

// ListQualityProfiles calls ListQualityProfilesFunc.
func (mock *RadarrClientMock) ListQualityProfiles(ctx context.Context) ([]QualityProfile, error) {
	if mock.ListQualityProfilesFunc == nil {
		panic("RadarrClientMock.ListQualityProfilesFunc: method is nil but RadarrClient.ListQualityProfiles was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListQualityProfiles.Lock()
	mock.calls.ListQualityProfiles = append(mock.calls.ListQualityProfiles, callInfo)
	mock.lockListQualityProfiles.Unlock()
	return mock.ListQualityProfilesFunc(ctx)
}

// ListQualityProfilesCalls gets all the calls that were made to ListQualityProfiles.
// Check the length with:
//
//	len(mockedRadarrClient.ListQualityProfilesCalls())
func (mock *RadarrClientMock) ListQualityProfilesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListQualityProfiles.RLock()
	calls = mock.calls.ListQualityProfiles
	mock.lockListQualityProfiles.RUnlock()
	return calls
}

// ListRootFolders calls ListRootFoldersFunc.
func (mock *RadarrClientMock) ListRootFolders(ctx context.Context) ([]RootFolder, error) {
	if mock.ListRootFoldersFunc == nil {
		panic("RadarrClientMock.ListRootFoldersFunc: method is nil but RadarrClient.ListRootFolders was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListRootFolders.Lock()
	mock.calls.ListRootFolders = append(mock.calls.ListRootFolders, callInfo)
	mock.lockListRootFolders.Unlock()
	return mock.ListRootFoldersFunc(ctx)
}

// ListRootFoldersCalls gets all the calls that were made to ListRootFolders.
// Check the length with:
//
//	len(mockedRadarrClient.ListRootFoldersCalls())
func (mock *RadarrClientMock) ListRootFoldersCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListRootFolders.RLock()
	calls = mock.calls.ListRootFolders
	mock.lockListRootFolders.RUnlock()
	return calls
}

// ListTags calls ListTagsFunc.
func (mock *RadarrClientMock) ListTags(ctx context.Context) ([]Tag, error) {
	if mock.ListTagsFunc == nil {
		panic("RadarrClientMock.ListTagsFunc: method is nil but RadarrClient.ListTags was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListTags.Lock()
	mock.calls.ListTags = append(mock.calls.ListTags, callInfo)
	mock.lockListTags.Unlock()
	return mock.ListTagsFunc(ctx)
}

// ListTagsCalls gets all the calls that were made to ListTags.
// Check the length with:
//
//	len(mockedRadarrClient.ListTagsCalls())
func (mock *RadarrClientMock) ListTagsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListTags.RLock()
	calls = mock.calls.ListTags
	mock.lockListTags.RUnlock()
	return calls
}

// LookupMovie calls LookupMovieFunc.
func (mock *RadarrClientMock) LookupMovie(ctx context.Context, term string) ([]RadarrLookupResult, error) {
	if mock.LookupMovieFunc == nil {
		panic("RadarrClientMock.LookupMovieFunc: method is nil but RadarrClient.LookupMovie was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Term string
	}{
		Ctx:  ctx,
		Term: term,
	}
	mock.lockLookupMovie.Lock()
	mock.calls.LookupMovie = append(mock.calls.LookupMovie, callInfo)
	mock.lockLookupMovie.Unlock()
	return mock.LookupMovieFunc(ctx, term)
}

// LookupMovieCalls gets all the calls that were made to LookupMovie.
// Check the length with:
//
//	len(mockedRadarrClient.LookupMovieCalls())
func (mock *RadarrClientMock) LookupMovieCalls() []struct {
	Ctx  context.Context
	Term string
} {
	var calls []struct {
		Ctx  context.Context
		Term string
	}
	mock.lockLookupMovie.RLock()
	calls = mock.calls.LookupMovie
	mock.lockLookupMovie.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *RadarrClientMock) Name() string {
	if mock.NameFunc == nil {
		panic("RadarrClientMock.NameFunc: method is nil but RadarrClient.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedRadarrClient.NameCalls())
func (mock *RadarrClientMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// SystemStatus calls SystemStatusFunc.
func (mock *RadarrClientMock) SystemStatus(ctx context.Context) (SystemStatus, error) {
	if mock.SystemStatusFunc == nil {
		panic("RadarrClientMock.SystemStatusFunc: method is nil but RadarrClient.SystemStatus was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSystemStatus.Lock()
	mock.calls.SystemStatus = append(mock.calls.SystemStatus, callInfo)
	mock.lockSystemStatus.Unlock()
	return mock.SystemStatusFunc(ctx)
}

// SystemStatusCalls gets all the calls that were made to SystemStatus.
// Check the length with:
//
//	len(mockedRadarrClient.SystemStatusCalls())
func (mock *RadarrClientMock) SystemStatusCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSystemStatus.RLock()
	calls = mock.calls.SystemStatus
	mock.lockSystemStatus.RUnlock()
	return calls
}
