package dataports

import (
	"context"
	"errors"
	"time"

	"github.com/alexmorbo/seasonfill/internal/runtime"
	"github.com/alexmorbo/seasonfill/internal/runtime/crypto"
)

// RuntimeConfigRow mirrors RuntimeConfigModel for transport between
// the repo and its callers (no DB model leaks). UpdatedAt sources the
// Last-Modified header on the HTTP GET (027c).
type RuntimeConfigRow struct {
	Cron                       runtime.CronSnapshot
	Scan                       runtime.ScanSnapshot
	DryRun                     bool
	GlobalRateLimit            runtime.RateLimitSnapshot
	Auth                       runtime.AuthSnapshot
	OIDCClientSecretCiphertext []byte
	APIKeyCiphertext           []byte
	APIKeyAutoGenerated        bool
	UpdatedAt                  time.Time
	// GUIDRewrites — operator-curated tracker GUID substitutions (107).
	// Persisted as JSON on the singleton row; always non-nil after Get
	// (empty slice when no rules).
	GUIDRewrites []runtime.GUIDRewriteRule
}

// ErrStaleWrite is the sentinel repos return when an
// If-Unmodified-Since precondition fails inside the write
// transaction. Distinct from ErrNotFound (404 vs 412).
var ErrStaleWrite = errors.New("precondition failed: row was modified by another writer")

type RuntimeConfigRepository interface {
	// Get returns the singleton row. ErrNotFound when the row hasn't
	// been written yet.
	Get(ctx context.Context) (RuntimeConfigRow, error)

	// Upsert writes the singleton row from a runtime.Snapshot. Used
	// by both the seed-on-empty bootstrap path and the HTTP PUT
	// handler. When ifUnmodifiedSince != nil and the existing row's
	// updated_at (second-truncated) is strictly newer than the
	// header value, returns ErrStaleWrite without writing. Bootstrap
	// callers pass nil.
	Upsert(ctx context.Context, snap runtime.Snapshot, ifUnmodifiedSince *time.Time) error

	UpsertOIDCSecret(ctx context.Context, plaintext string) error
	DecryptOIDCSecret(ctx context.Context) (string, error)

	// SaveAPIKey stores the encrypted master-API-key probe. Used by
	// the bootstrap auto-gen flow (internal/wiring/apikey.go).
	SaveAPIKey(ctx context.Context, ciphertext []byte, autoGenerated bool) error

	// GetTimezone returns the operator-selected IANA timezone name
	// persisted in app_config.timezone (D-5 / 466b folded the legacy
	// app_settings singleton into app_config). Returns the empty
	// string (no error) when no override is set — the tz resolver
	// then falls back to TZ env / UTC. Returns ports.ErrNotFound
	// only when the app_config row itself is missing (pre-bootstrap
	// state).
	GetTimezone(ctx context.Context) (string, error)

	// SetTimezone persists name into app_config.timezone. Empty name
	// clears the override (writes SQL NULL). Implementations seed a
	// defaults-filled app_config row on first call so the timezone
	// can be set before the operator PUTs the rest of runtime_config.
	SetTimezone(ctx context.Context, name string) error
}

type SonarrInstanceRepository interface {
	List(ctx context.Context, c *crypto.Cipher) ([]runtime.InstanceSnapshot, error)
	GetByName(ctx context.Context, name string, c *crypto.Cipher) (runtime.InstanceSnapshot, error)
	Create(ctx context.Context, inst runtime.InstanceSnapshot, c *crypto.Cipher) (uint, error)
	// UpdateWithOptions writes parent + secret in a single
	// transaction. When ifUnmodifiedSince != nil and the existing
	// row's updated_at (second-truncated) is strictly newer than
	// the header value, returns ErrStaleWrite without writing.
	// preserveSecret=true skips the secret upsert (used when the
	// PUT body omits api_key).
	UpdateWithOptions(ctx context.Context, inst runtime.InstanceSnapshot, c *crypto.Cipher, preserveSecret bool, ifUnmodifiedSince *time.Time) error
	Delete(ctx context.Context, name string) error
	GetUpdatedAt(ctx context.Context, name string) (time.Time, error)
}
