/* eslint-disable */
// Generated by gen-types.mjs. DO NOT EDIT — run `make openapi`.

export type paths = {
    readonly "/auth/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Authenticate and issue a session cookie
         * @description Validates api_key (body or X-Api-Key header). On success
         *     sets HttpOnly seasonfill_session cookie and returns 200.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description API key (alternative to X-Api-Key header) */
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": components["schemas"]["dto.LoginRequest"];
                };
            };
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description HttpOnly session cookie */
                        readonly "Set-Cookie"?: string;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.OKResponse"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/auth/session": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Verify the current session */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.OKResponse"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        /** Clear the session cookie */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/decisions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List decisions */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Page size (default 50, max 200) */
                    readonly limit?: number;
                    /** @description Opaque next_cursor */
                    readonly cursor?: string;
                    /** @description Filter by instance */
                    readonly instance?: string;
                    /** @description Filter by parent scan_run UUID */
                    readonly scan_run_id?: string;
                    /** @description Filter by series ID */
                    readonly series_id?: number;
                    /** @description Filter by season */
                    readonly season_number?: number;
                    /** @description Filter by outcome */
                    readonly decision?: PathsDecisionsGetParametersQueryDecision;
                    /** @description RFC3339 lower bound */
                    readonly from?: string;
                    /** @description RFC3339 upper bound */
                    readonly to?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.DecisionList"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/decisions/{id}/grab": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Grab the release the decision selected
         * @description Explicit-confirm path that bypasses global dry_run for
         *     one decision. Idempotent on (instance, series, season,
         *     release_guid). Eligible only when decision == "grab",
         *     selected_guid != "" and dry_run_would_grab == true.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Decision UUID */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.Grab"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Bad Gateway */
                readonly 502: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/grabs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List grabs */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Page size (default 50, max 200) */
                    readonly limit?: number;
                    /** @description Opaque next_cursor */
                    readonly cursor?: string;
                    /** @description Filter by instance */
                    readonly instance?: string;
                    /** @description Filter by series ID */
                    readonly series_id?: number;
                    /** @description Filter by season */
                    readonly season_number?: number;
                    /** @description Filter by status */
                    readonly status?: PathsGrabsGetParametersQueryStatus;
                    /** @description RFC3339 lower bound */
                    readonly from?: string;
                    /** @description RFC3339 upper bound */
                    readonly to?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.GrabList"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/healthz": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Liveness probe */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.HealthStatus"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/instances": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Sonarr instance health
         * @description Latest snapshot from the in-memory checker.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.InstanceList"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/instances/{name}/missing": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List missing-aired series for an instance
         * @description Monitored series whose aired episode count exceeds
         *     the on-disk file count, with per-season breakdown.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Instance name */
                    readonly name: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.MissingSeriesList"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Bad Gateway */
                readonly 502: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/instances/{name}/series": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Search series in a Sonarr instance
         * @description Title-substring search with monitored filter. Returns
         *     a trimmed picker-specific DTO (series_id, title,
         *     monitored, season_count, missing_aired_count). `total`
         *     is the pre-limit count; clients narrow by typing more
         *     rather than paginating.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Title substring (case-insensitive) */
                    readonly q?: string;
                    /** @description true | false | any (default any) */
                    readonly monitored?: PathsInstancesNameSeriesGetParametersQueryMonitored;
                    /** @description 1..100 (default 30) */
                    readonly limit?: number;
                };
                readonly header?: never;
                readonly path: {
                    /** @description Instance name */
                    readonly name: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.SeriesSearchList"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Bad Gateway */
                readonly 502: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/readyz": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Readiness probe
         * @description 200 only when DB AND ≥1 Sonarr instance are healthy.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ReadyStatus"];
                    };
                };
                /** @description Service Unavailable */
                readonly 503: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ReadyStatus"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/scan": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Trigger a manual scan
         * @description Asynchronously schedules a scan across all configured
         *     instances or the named one. Returns 202 immediately
         *     with status="running"; clients poll /scans/{id} for
         *     live progress (series_scanned increments mid-scan).
         *     Optional `series_ids` narrows a per-instance scan;
         *     unknown IDs are silently dropped with a WARN.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description Optional instance + series filter */
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": components["schemas"]["dto.ScanTriggerRequest"];
                };
            };
            readonly responses: {
                /** @description Accepted */
                readonly 202: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": readonly components["schemas"]["dto.ScanTriggerItem"][];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ScanNotFoundResponse"];
                    };
                };
                /** @description SCAN_IN_PROGRESS */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ScanConflictResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/scans": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List scans
         * @description Keyset-paginated, newest first.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Page size (default 50, max 200) */
                    readonly limit?: number;
                    /** @description Opaque next_cursor */
                    readonly cursor?: string;
                    /** @description Filter by instance */
                    readonly instance?: string;
                    /** @description Filter by status */
                    readonly status?: PathsScansGetParametersQueryStatus;
                    /** @description RFC3339 lower bound */
                    readonly from?: string;
                    /** @description RFC3339 upper bound (exclusive) */
                    readonly to?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ScanList"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/scans/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get scan by ID */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Scan run UUID */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.Scan"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/scans/{id}/cancel": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Cancel a running scan
         * @description Signals cancellation of the named scan run. The goroutine
         *     observes the signal at the next ctx.Err() checkpoint and
         *     finalises with status="cancelled". Already-collected
         *     decisions are kept; already-issued grabs are NOT undone.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Scan run UUID */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Accepted */
                readonly 202: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.OKResponse"];
                    };
                };
                /** @description invalid id */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description scan not running */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        readonly "dto.Decision": {
            readonly candidates_count?: number;
            /**
             * @example action_taken
             * @enum {string}
             */
            readonly category?: DtoDecisionCategory;
            readonly created_at?: string;
            /**
             * @example grab
             * @enum {string}
             */
            readonly decision?: DtoDecisionDecision;
            readonly dry_run_would_grab?: boolean;
            readonly existing_count?: number;
            /** @example dec_001 */
            readonly id?: string;
            /** @example alpha */
            readonly instance?: string;
            readonly missing_count?: number;
            /** @example upgrade_available */
            readonly reason?: string;
            readonly releases_found?: number;
            readonly scan_run_id?: string;
            readonly season_number?: number;
            readonly selected_guid?: string;
            readonly series_id?: number;
            /** @example Severance */
            readonly series_title?: string;
        };
        readonly "dto.DecisionList": {
            readonly items?: readonly components["schemas"]["dto.Decision"][];
            readonly next_cursor?: string;
        };
        readonly "dto.ErrorResponse": {
            /** @example UNAUTHORIZED */
            readonly code?: string;
            /** @example unauthorized */
            readonly error?: string;
        };
        readonly "dto.Grab": {
            readonly attempts?: number;
            readonly coverage_count?: number;
            readonly created_at?: string;
            readonly custom_format_score?: number;
            readonly error_message?: string;
            /** @example grb_001 */
            readonly id?: string;
            readonly indexer_id?: number;
            /** @example tracker.x */
            readonly indexer_name?: string;
            /** @example alpha */
            readonly instance?: string;
            /** @example WEBDL-1080p */
            readonly quality?: string;
            readonly release_guid?: string;
            readonly release_title?: string;
            readonly scan_run_id?: string;
            readonly season_number?: number;
            readonly series_id?: number;
            /** @example Severance */
            readonly series_title?: string;
            /**
             * @example imported
             * @enum {string}
             */
            readonly status?: DtoGrabStatus;
            readonly updated_at?: string;
        };
        readonly "dto.GrabList": {
            readonly items?: readonly components["schemas"]["dto.Grab"][];
            readonly next_cursor?: string;
        };
        readonly "dto.HealthStatus": {
            /** @example ok */
            readonly status?: string;
        };
        readonly "dto.Instance": {
            /**
             * @example available
             * @enum {string}
             */
            readonly health?: DtoInstanceHealth;
            readonly last_check_at?: string;
            readonly last_error?: string;
            /**
             * @example auto
             * @enum {string}
             */
            readonly mode?: DtoInstanceMode;
            /** @example alpha */
            readonly name?: string;
            readonly transitions_count?: number;
        };
        readonly "dto.InstanceList": {
            readonly instances?: readonly components["schemas"]["dto.Instance"][];
        };
        readonly "dto.LoginRequest": {
            /** @example sf_abc123 */
            readonly api_key?: string;
        };
        readonly "dto.MissingSeasonStat": {
            readonly missing_aired_count?: number;
            readonly season_number?: number;
        };
        readonly "dto.MissingSeries": {
            /** @example true */
            readonly monitored?: boolean;
            readonly seasons?: readonly components["schemas"]["dto.MissingSeasonStat"][];
            /** @example 122 */
            readonly series_id?: number;
            /** @example Severance */
            readonly title?: string;
            readonly total_missing_aired?: number;
        };
        readonly "dto.MissingSeriesList": {
            readonly items?: readonly components["schemas"]["dto.MissingSeries"][];
            readonly total?: number;
        };
        readonly "dto.OKResponse": {
            /** @example true */
            readonly ok?: boolean;
        };
        readonly "dto.ReadyStatus": {
            /** @example true */
            readonly database?: boolean;
            readonly instances?: readonly components["schemas"]["dto.Instance"][];
            readonly reasons?: readonly string[];
            /** @example true */
            readonly sonarr?: boolean;
            /**
             * @example ok
             * @enum {string}
             */
            readonly status?: DtoReadyStatusStatus;
        };
        readonly "dto.Scan": {
            readonly candidates_found?: number;
            readonly created_at?: string;
            readonly dry_run?: boolean;
            readonly error_message?: string;
            readonly errors_count?: number;
            readonly finished_at?: string;
            readonly grabs_failed?: number;
            readonly grabs_performed?: number;
            /** @example 7b3d4a92-1234-4abc-9def-000000000001 */
            readonly id?: string;
            /** @example alpha */
            readonly instance?: string;
            readonly series_scanned?: number;
            readonly started_at?: string;
            /**
             * @example completed
             * @enum {string}
             */
            readonly status?: DtoScanStatus;
            /**
             * @example cron
             * @enum {string}
             */
            readonly trigger?: DtoScanTrigger;
        };
        readonly "dto.ScanConflictResponse": {
            /** @example SCAN_IN_PROGRESS */
            readonly code?: string;
            /** @example scan already running */
            readonly error?: string;
            /** @example alpha */
            readonly instance?: string;
        };
        readonly "dto.ScanList": {
            readonly items?: readonly components["schemas"]["dto.Scan"][];
            readonly next_cursor?: string;
        };
        readonly "dto.ScanNotFoundResponse": {
            /** @example unknown instance */
            readonly error?: string;
            /** @example alpha */
            readonly instance?: string;
        };
        readonly "dto.ScanTriggerItem": {
            readonly candidates_found?: number;
            readonly errors?: number;
            readonly finished_at?: string;
            /** @example alpha */
            readonly instance?: string;
            /** @example 7b3d4a92-1234-4abc-9def-000000000001 */
            readonly scan_run_id?: string;
            readonly series_scanned?: number;
            readonly started_at?: string;
            /**
             * @example completed
             * @enum {string}
             */
            readonly status?: DtoScanTriggerItemStatus;
        };
        readonly "dto.ScanTriggerRequest": {
            /** @example alpha */
            readonly instance?: string;
            readonly series_ids?: readonly number[];
        };
        readonly "dto.SeriesSearchItem": {
            /** @example 8 */
            readonly missing_aired_count?: number;
            /** @example true */
            readonly monitored?: boolean;
            /** @example 2 */
            readonly season_count?: number;
            /** @example 122 */
            readonly series_id?: number;
            /** @example Severance */
            readonly title?: string;
        };
        readonly "dto.SeriesSearchList": {
            readonly items?: readonly components["schemas"]["dto.SeriesSearchItem"][];
            /** @example 142 */
            readonly total?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export enum PathsDecisionsGetParametersQueryDecision {
    grab = "grab",
    skip = "skip",
    blocked_cooldown = "blocked_cooldown",
    already_optimal = "already_optimal",
    expired = "expired"
}
export enum PathsGrabsGetParametersQueryStatus {
    grabbed = "grabbed",
    imported = "imported",
    import_failed = "import_failed",
    grab_failed = "grab_failed",
    expired = "expired"
}
export enum PathsInstancesNameSeriesGetParametersQueryMonitored {
    true = "true",
    false = "false",
    any = "any"
}
export enum PathsScansGetParametersQueryStatus {
    running = "running",
    completed = "completed",
    failed = "failed",
    aborted = "aborted"
}
export enum DtoDecisionCategory {
    all_complete = "all_complete",
    sonarr_handles = "sonarr_handles",
    action_taken = "action_taken",
    blocked = "blocked",
    nothing_found = "nothing_found",
    error = "error",
    unknown = "unknown"
}
export enum DtoDecisionDecision {
    grab = "grab",
    skip = "skip",
    blocked_cooldown = "blocked_cooldown",
    already_optimal = "already_optimal",
    expired = "expired"
}
export enum DtoGrabStatus {
    grabbed = "grabbed",
    imported = "imported",
    import_failed = "import_failed",
    grab_failed = "grab_failed",
    expired = "expired"
}
export enum DtoInstanceHealth {
    available = "available",
    degraded = "degraded",
    unavailable = "unavailable",
    unknown = "unknown"
}
export enum DtoInstanceMode {
    auto = "auto",
    manual = "manual"
}
export enum DtoReadyStatusStatus {
    ok = "ok",
    unavailable = "unavailable"
}
export enum DtoScanStatus {
    running = "running",
    completed = "completed",
    failed = "failed",
    aborted = "aborted",
    cancelled = "cancelled"
}
export enum DtoScanTrigger {
    cron = "cron",
    manual = "manual",
    webhook = "webhook"
}
export enum DtoScanTriggerItemStatus {
    completed = "completed",
    failed = "failed",
    running = "running",
    aborted = "aborted",
    cancelled = "cancelled"
}
export type operations = Record<string, never>;
