/* eslint-disable */
// Generated by gen-types.mjs. DO NOT EDIT — run `make openapi`.

export type paths = {
    readonly "/auth/config": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Public auth-mode bootstrap */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.AuthConfigDTO"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/auth/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Authenticate and issue a session cookie
         * @description Validates username + password. On success sets HttpOnly
         *     seasonfill_session cookie and returns 200.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description Username and password */
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["dto.LoginRequest"];
                };
            };
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description HttpOnly session cookie */
                        readonly "Set-Cookie"?: string;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.OKResponse"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Too Many Requests */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/auth/oidc/callback": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** OIDC callback */
        readonly get: {
            readonly parameters: {
                readonly query: {
                    /** @description authorization code */
                    readonly code: string;
                    /** @description echoed state */
                    readonly state: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Found */
                readonly 302: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/auth/oidc/start": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** OIDC start */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description same-origin path to return to after login */
                    readonly next?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Found */
                readonly 302: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/auth/oidc/test": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** OIDC reachability test */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": Record<string, never>;
                };
            };
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["auth.OIDCTestResult"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/auth/password": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Change the admin password */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description Current + new password */
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["dto.PasswordChangeRequest"];
                };
            };
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/auth/session": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Verify the current session */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.SessionResponse"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        /** Clear the session cookie */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/config/runtime": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get runtime configuration */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description RFC1123 of updated_at */
                        readonly "Last-Modified"?: string;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.RuntimeConfigDTO"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        /** Update runtime configuration */
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description Runtime config */
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["dto.RuntimeConfigDTO"];
                };
            };
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description RFC1123 of updated_at */
                        readonly "Last-Modified"?: string;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.RuntimeConfigDTO"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Precondition Failed */
                readonly 412: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/decisions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List decisions */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Page size (default 50, max 200) */
                    readonly limit?: number;
                    /** @description Opaque next_cursor */
                    readonly cursor?: string;
                    /** @description Filter by instance */
                    readonly instance?: string;
                    /** @description Filter by parent scan_run UUID */
                    readonly scan_run_id?: string;
                    /** @description Filter by series ID */
                    readonly series_id?: number;
                    /** @description Filter by season */
                    readonly season_number?: number;
                    /** @description Filter by outcome */
                    readonly decision?: PathsDecisionsGetParametersQueryDecision;
                    /** @description RFC3339 lower bound */
                    readonly from?: string;
                    /** @description RFC3339 upper bound */
                    readonly to?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.DecisionList"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/decisions/{id}/grab": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Grab the release the decision selected
         * @description Explicit-confirm path that bypasses global dry_run for
         *     one decision. Idempotent on (instance, series, season,
         *     release_guid). Eligible only when decision == "grab",
         *     selected_guid != "" and dry_run_would_grab == true.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Decision UUID */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.Grab"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Bad Gateway */
                readonly 502: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/decisions/{id}/rescan": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Rescan a single decision
         * @description Asynchronously re-evaluates (instance, series, season).
         *     Bypasses GUID cooldowns. Returns 202 immediately with a
         *     fresh scan_run_id; the goroutine writes the new decision
         *     and marks the original superseded. 409 if the original
         *     already produced a grab_records row or if another scan
         *     is running on the same instance.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Decision UUID */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Accepted */
                readonly 202: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": readonly components["schemas"]["dto.ScanTriggerItem"][];
                    };
                };
                /** @description invalid id */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description decision or instance not found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description decision already superseded or already executed */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ScanConflictResponse"] | components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/grabs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List grabs */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Page size (default 50, max 200) */
                    readonly limit?: number;
                    /** @description Opaque next_cursor */
                    readonly cursor?: string;
                    /** @description Filter by instance */
                    readonly instance?: string;
                    /** @description Filter by series ID */
                    readonly series_id?: number;
                    /** @description Filter by season */
                    readonly season_number?: number;
                    /** @description Filter by status */
                    readonly status?: PathsGrabsGetParametersQueryStatus;
                    /** @description RFC3339 lower bound */
                    readonly from?: string;
                    /** @description RFC3339 upper bound */
                    readonly to?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.GrabList"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/healthz": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Liveness probe */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.HealthStatus"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/instances": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Sonarr instance health
         * @description Latest snapshot from the in-memory checker.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.InstanceList"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        /** Create a Sonarr instance */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description Instance fields */
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["dto.InstanceCreateRequest"];
                };
            };
            readonly responses: {
                /** @description Created */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.InstanceDetail"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/instances/{name}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get one Sonarr instance (masked) */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Instance name */
                    readonly name: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description RFC1123 of updated_at */
                        readonly "Last-Modified"?: string;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.InstanceDetail"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        /** Update a Sonarr instance */
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Instance name */
                    readonly name: string;
                };
                readonly cookie?: never;
            };
            /** @description Instance fields */
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["dto.InstanceUpdateRequest"];
                };
            };
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        /** @description RFC1123 of updated_at */
                        readonly "Last-Modified"?: string;
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.InstanceDetail"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Precondition Failed */
                readonly 412: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly post?: never;
        /** Delete a Sonarr instance and its history */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Instance name */
                    readonly name: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/instances/{name}/missing": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List missing-aired series for an instance
         * @description Monitored series whose aired episode count exceeds
         *     the on-disk file count, with per-season breakdown.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Instance name */
                    readonly name: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.MissingSeriesList"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Bad Gateway */
                readonly 502: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/instances/{name}/qbit/settings": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get qBit Watchdog settings for an instance */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Instance name */
                    readonly name: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.QbitSettingsDTO"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        /** Create or replace qBit Watchdog settings (upsert) */
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Instance name */
                    readonly name: string;
                };
                readonly cookie?: never;
            };
            /** @description Settings */
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["dto.QbitSettingsUpsertRequest"];
                };
            };
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.QbitSettingsDTO"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly post?: never;
        /** Delete qBit Watchdog settings */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Instance name */
                    readonly name: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description No Content */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/instances/{name}/series": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Search series in a Sonarr instance
         * @description Title-substring search with monitored filter. Returns
         *     a trimmed picker-specific DTO (series_id, title,
         *     monitored, season_count, missing_aired_count). `total`
         *     is the pre-limit count; clients narrow by typing more
         *     rather than paginating.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Title substring (case-insensitive) */
                    readonly q?: string;
                    /** @description true | false | any (default any) */
                    readonly monitored?: PathsInstancesNameSeriesGetParametersQueryMonitored;
                    /** @description 1..100 (default 30) */
                    readonly limit?: number;
                };
                readonly header?: never;
                readonly path: {
                    /** @description Instance name */
                    readonly name: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.SeriesSearchList"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Bad Gateway */
                readonly 502: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/instances/test": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Probe a Sonarr instance for reachability/auth */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description URL and api_key to probe */
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": components["schemas"]["dto.InstanceTestRequest"];
                };
            };
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.InstanceTestResponse"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Too Many Requests */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Gateway Timeout */
                readonly 504: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/readyz": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Readiness probe
         * @description 200 when pod-local dependencies (DB) are healthy.
         *     External Sonarr health is reported via /api/v1/instances.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ReadyStatus"];
                    };
                };
                /** @description Service Unavailable */
                readonly 503: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ReadyStatus"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/scan": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Trigger a manual scan
         * @description Asynchronously schedules a scan across all configured
         *     instances or the named one. Returns 202 immediately
         *     with status="running"; clients poll /scans/{id} for
         *     live progress (series_scanned increments mid-scan).
         *     Optional `series_ids` narrows a per-instance scan;
         *     unknown IDs are silently dropped with a WARN.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description Optional instance + series filter */
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": components["schemas"]["dto.ScanTriggerRequest"];
                };
            };
            readonly responses: {
                /** @description Accepted */
                readonly 202: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": readonly components["schemas"]["dto.ScanTriggerItem"][];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ScanNotFoundResponse"];
                    };
                };
                /** @description SCAN_IN_PROGRESS */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ScanConflictResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/scans": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List scans
         * @description Keyset-paginated, newest first.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Page size (default 50, max 200) */
                    readonly limit?: number;
                    /** @description Opaque next_cursor */
                    readonly cursor?: string;
                    /** @description Filter by instance */
                    readonly instance?: string;
                    /** @description Filter by status */
                    readonly status?: PathsScansGetParametersQueryStatus;
                    /** @description RFC3339 lower bound */
                    readonly from?: string;
                    /** @description RFC3339 upper bound (exclusive) */
                    readonly to?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ScanList"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/scans/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get scan by ID */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Scan run UUID */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description OK */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.Scan"];
                    };
                };
                /** @description Bad Request */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/scans/{id}/cancel": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Cancel a running scan
         * @description Signals cancellation of the named scan run. The goroutine
         *     observes the signal at the next ctx.Err() checkpoint and
         *     finalises with status="cancelled". Already-collected
         *     decisions are kept; already-issued grabs are NOT undone.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Scan run UUID */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Accepted */
                readonly 202: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.OKResponse"];
                    };
                };
                /** @description invalid id */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description scan not running */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        readonly "auth.CheckDiscovery": {
            readonly discovered_issuer?: string;
            readonly error?: string;
            readonly ok?: boolean;
        };
        readonly "auth.CheckIssuerMatch": {
            readonly expected?: string;
            readonly got?: string;
            readonly ok?: boolean;
        };
        readonly "auth.CheckJWKS": {
            readonly error?: string;
            readonly keys?: number;
            readonly ok?: boolean;
        };
        readonly "auth.CheckTokenEndpoint": {
            readonly error?: string;
            readonly ok?: boolean;
            readonly url?: string;
        };
        readonly "auth.OIDCTestResult": {
            readonly discovery?: components["schemas"]["auth.CheckDiscovery"];
            readonly issuer_match?: components["schemas"]["auth.CheckIssuerMatch"];
            readonly jwks?: components["schemas"]["auth.CheckJWKS"];
            readonly token_endpoint?: components["schemas"]["auth.CheckTokenEndpoint"];
        };
        readonly "dto.AuthConfigDTO": {
            /** @example false */
            readonly local_bypass?: boolean;
            /** @example /api/v1/auth/oidc/start */
            readonly login_url?: string;
            /** @example forms */
            readonly mode?: string;
            /**
             * @description OIDCReady mirrors middleware.OIDCRuntime.IsReady(). When true,
             *     LoginURL is also populated — SPA renders SSO button regardless of mode.
             * @example false
             */
            readonly oidc_ready?: boolean;
        };
        readonly "dto.Decision": {
            readonly candidates_count?: number;
            /**
             * @example action_taken
             * @enum {string}
             */
            readonly category?: DtoDecisionCategory;
            readonly created_at?: string;
            /**
             * @example grab
             * @enum {string}
             */
            readonly decision?: DtoDecisionDecision;
            readonly dry_run_would_grab?: boolean;
            /** @example sonarr: 503 service unavailable */
            readonly error_detail?: string;
            readonly existing_count?: number;
            /** @example dec_001 */
            readonly id?: string;
            /** @example alpha */
            readonly instance?: string;
            readonly missing_count?: number;
            /** @example upgrade_available */
            readonly reason?: string;
            readonly releases_found?: number;
            readonly scan_run_id?: string;
            readonly season_number?: number;
            readonly selected_guid?: string;
            readonly series_id?: number;
            /** @example Severance */
            readonly series_title?: string;
            /** @example 7b3d4a92-1234-4abc-9def-000000000005 */
            readonly superseded_by_id?: string;
        };
        readonly "dto.DecisionList": {
            readonly items?: readonly components["schemas"]["dto.Decision"][];
            readonly next_cursor?: string;
        };
        readonly "dto.ErrorResponse": {
            /** @example UNAUTHORIZED */
            readonly code?: string;
            /** @example unauthorized */
            readonly error?: string;
        };
        readonly "dto.Grab": {
            readonly attempts?: number;
            readonly coverage_count?: number;
            readonly created_at?: string;
            readonly custom_format_score?: number;
            readonly error_message?: string;
            /** @example grb_001 */
            readonly id?: string;
            readonly indexer_id?: number;
            /** @example tracker.x */
            readonly indexer_name?: string;
            /** @example alpha */
            readonly instance?: string;
            /** @example WEBDL-1080p */
            readonly quality?: string;
            readonly release_guid?: string;
            readonly release_title?: string;
            readonly scan_run_id?: string;
            readonly season_number?: number;
            readonly series_id?: number;
            /** @example Severance */
            readonly series_title?: string;
            /**
             * @example imported
             * @enum {string}
             */
            readonly status?: DtoGrabStatus;
            readonly updated_at?: string;
        };
        readonly "dto.GrabList": {
            readonly items?: readonly components["schemas"]["dto.Grab"][];
            readonly next_cursor?: string;
        };
        readonly "dto.HealthStatus": {
            /** @example ok */
            readonly status?: string;
        };
        readonly "dto.Instance": {
            /**
             * @example Available
             * @enum {string}
             */
            readonly health?: DtoInstanceHealth;
            readonly last_check_at?: string;
            readonly last_error?: string;
            /**
             * @example auto
             * @enum {string}
             */
            readonly mode?: DtoInstanceMode;
            /** @example alpha */
            readonly name?: string;
            readonly transitions_count?: number;
            /** @example http://sonarr:8989 */
            readonly url?: string;
        };
        readonly "dto.InstanceCooldown": {
            readonly guid_after_failed_grab_sec?: number;
            readonly guid_after_failed_import_sec?: number;
            /** @enum {string} */
            readonly mode?: DtoInstanceCooldownMode;
            readonly series_after_grab_sec?: number;
        };
        readonly "dto.InstanceCreateRequest": {
            /** @example abcd... */
            readonly api_key?: string;
            readonly cooldown?: components["schemas"]["dto.InstanceCooldown"];
            readonly dry_run?: boolean;
            readonly health_check?: components["schemas"]["dto.InstanceHealthCheck"];
            readonly limits?: components["schemas"]["dto.InstanceLimits"];
            /** @example auto */
            readonly mode?: string;
            /** @example alpha */
            readonly name?: string;
            readonly ranking?: components["schemas"]["dto.InstanceRanking"];
            readonly rate_limit_burst?: number;
            readonly rate_limit_rpm?: number;
            readonly retry?: components["schemas"]["dto.InstanceRetry"];
            readonly search?: components["schemas"]["dto.InstanceSearch"];
            readonly search_timeout_sec?: number;
            readonly tags?: components["schemas"]["dto.InstanceTags"];
            readonly timeout_sec?: number;
            /** @example http://sonarr:8989 */
            readonly url?: string;
        };
        readonly "dto.InstanceDetail": {
            /** @example *** */
            readonly api_key?: string;
            readonly cooldown?: components["schemas"]["dto.InstanceCooldown"];
            readonly dry_run?: boolean;
            readonly health_check?: components["schemas"]["dto.InstanceHealthCheck"];
            readonly limits?: components["schemas"]["dto.InstanceLimits"];
            /**
             * @example auto
             * @enum {string}
             */
            readonly mode?: DtoInstanceDetailMode;
            /** @example alpha */
            readonly name?: string;
            readonly ranking?: components["schemas"]["dto.InstanceRanking"];
            readonly rate_limit_burst?: number;
            readonly rate_limit_rpm?: number;
            readonly retry?: components["schemas"]["dto.InstanceRetry"];
            readonly search?: components["schemas"]["dto.InstanceSearch"];
            readonly search_timeout_sec?: number;
            readonly tags?: components["schemas"]["dto.InstanceTags"];
            readonly timeout_sec?: number;
            readonly updated_at?: string;
            /** @example http://sonarr:8989 */
            readonly url?: string;
        };
        readonly "dto.InstanceHealthCheck": {
            readonly recheck_auth_sec?: number;
            readonly recheck_network_sec?: number;
        };
        readonly "dto.InstanceLimits": {
            readonly max_grabs_per_scan?: number;
            readonly scan_max_series?: number;
        };
        readonly "dto.InstanceList": {
            readonly instances?: readonly components["schemas"]["dto.Instance"][];
        };
        readonly "dto.InstanceRanking": {
            readonly indexer_priority_enabled?: boolean;
            readonly origin_bonus?: number;
        };
        readonly "dto.InstanceRetry": {
            readonly initial_backoff_sec?: number;
            readonly max_attempts?: number;
            readonly max_backoff_sec?: number;
        };
        readonly "dto.InstanceSearch": {
            readonly min_custom_format_score?: number;
            readonly require_all_aired?: boolean;
            readonly skip_anime?: boolean;
            readonly skip_specials?: boolean;
        };
        readonly "dto.InstanceTags": {
            readonly exclude?: readonly string[];
            readonly include?: readonly string[];
            /**
             * @example include
             * @enum {string}
             */
            readonly mode?: DtoInstanceTagsMode;
        };
        readonly "dto.InstanceTestRequest": {
            /** @example abcd... */
            readonly api_key?: string;
            /** @example http://sonarr:8989 */
            readonly url?: string;
        };
        readonly "dto.InstanceTestResponse": {
            readonly ok?: boolean;
            readonly reason?: string;
            readonly version?: string;
        };
        readonly "dto.InstanceUpdateRequest": {
            /** @example abcd... */
            readonly api_key?: string;
            readonly cooldown?: components["schemas"]["dto.InstanceCooldown"];
            readonly dry_run?: boolean;
            readonly health_check?: components["schemas"]["dto.InstanceHealthCheck"];
            readonly limits?: components["schemas"]["dto.InstanceLimits"];
            /** @example auto */
            readonly mode?: string;
            /** @example alpha */
            readonly name?: string;
            readonly ranking?: components["schemas"]["dto.InstanceRanking"];
            readonly rate_limit_burst?: number;
            readonly rate_limit_rpm?: number;
            readonly retry?: components["schemas"]["dto.InstanceRetry"];
            readonly search?: components["schemas"]["dto.InstanceSearch"];
            readonly search_timeout_sec?: number;
            readonly tags?: components["schemas"]["dto.InstanceTags"];
            readonly timeout_sec?: number;
            /** @example http://sonarr:8989 */
            readonly url?: string;
        };
        readonly "dto.LoginRequest": {
            /** @example hunter2 */
            readonly password?: string;
            /** @example admin */
            readonly username?: string;
        };
        readonly "dto.MissingSeasonStat": {
            readonly missing_aired_count?: number;
            readonly season_number?: number;
        };
        readonly "dto.MissingSeries": {
            /** @example true */
            readonly monitored?: boolean;
            readonly seasons?: readonly components["schemas"]["dto.MissingSeasonStat"][];
            /** @example 122 */
            readonly series_id?: number;
            /** @example Severance */
            readonly title?: string;
            readonly total_missing_aired?: number;
        };
        readonly "dto.MissingSeriesList": {
            readonly items?: readonly components["schemas"]["dto.MissingSeries"][];
            readonly total?: number;
        };
        readonly "dto.OKResponse": {
            /** @example true */
            readonly ok?: boolean;
        };
        readonly "dto.PasswordChangeRequest": {
            /** @example hunter22 */
            readonly current?: string;
            /** @example NewSecretLongEnough */
            readonly new?: string;
        };
        readonly "dto.QbitSettingsDTO": {
            /** @example sonarr */
            readonly category?: string;
            readonly created_at?: string;
            readonly custom_unregistered_msgs?: readonly string[];
            /** @example true */
            readonly enabled?: boolean;
            /** @example 1 */
            readonly id?: number;
            /** @example 7 */
            readonly instance_id?: number;
            /** @example alpha */
            readonly instance_name?: string;
            /** @example 3 */
            readonly max_consecutive_no_better?: number;
            /** @example true */
            readonly password_set?: boolean;
            /** @example 30 */
            readonly poll_interval_minutes?: number;
            /** @example 120 */
            readonly regrab_cooldown_hours?: number;
            readonly updated_at?: string;
            /** @example http://qbit.local:8080 */
            readonly url?: string;
            /** @example admin */
            readonly username?: string;
        };
        readonly "dto.QbitSettingsUpsertRequest": {
            /** @example sonarr */
            readonly category?: string;
            readonly custom_unregistered_msgs?: readonly string[];
            /** @example true */
            readonly enabled?: boolean;
            /** @example 3 */
            readonly max_consecutive_no_better?: number;
            /** @example hunter2 */
            readonly password?: string;
            /** @example 30 */
            readonly poll_interval_minutes?: number;
            /** @example 120 */
            readonly regrab_cooldown_hours?: number;
            /** @example http://qbit.local:8080 */
            readonly url?: string;
            /** @example admin */
            readonly username?: string;
        };
        readonly "dto.ReadyStatus": {
            /** @example true */
            readonly database?: boolean;
            /**
             * @example ok
             * @enum {string}
             */
            readonly status?: DtoReadyStatusStatus;
        };
        readonly "dto.RuntimeAuthDTO": {
            /** @description LocalBypass enables the local-address bypass middleware (036c). */
            readonly local_bypass?: boolean;
            /**
             * @description LocalNetworks is the CIDR allow-list driving local-bypass.
             * @example [
             *       "127.0.0.0/8",
             *       "10.0.0.0/8"
             *     ]
             */
            readonly local_networks?: readonly string[];
            /**
             * @description Mode is one of "forms" | "basic" | "none" | "oidc". Default "forms".
             * @example forms
             */
            readonly mode?: string;
            readonly oidc?: components["schemas"]["dto.RuntimeOIDCDTO"];
            readonly secure_cookie?: boolean;
            /**
             * @description SessionEpoch is read-only — the server bumps it whenever any
             *     auth-invalidating field changes. PUT bodies that include it are
             *     silently ignored (the usecase manages the value).
             * @example 0
             */
            readonly session_epoch?: number;
            /** @example 12h */
            readonly session_ttl?: string;
            /**
             * @example [
             *       "127.0.0.1",
             *       "::1"
             *     ]
             */
            readonly trusted_proxies?: readonly string[];
        };
        readonly "dto.RuntimeConfigDTO": {
            readonly auth?: components["schemas"]["dto.RuntimeAuthDTO"];
            /** @example false */
            readonly auto_generated_api_key?: boolean;
            readonly cron?: components["schemas"]["dto.RuntimeCronDTO"];
            readonly dry_run?: boolean;
            readonly global_rate_limit?: components["schemas"]["dto.RuntimeRateLimitDTO"];
            readonly scan?: components["schemas"]["dto.RuntimeScanDTO"];
            readonly updated_at?: string;
        };
        readonly "dto.RuntimeCronDTO": {
            readonly enabled?: boolean;
            /** @example 1m */
            readonly jitter?: string;
            readonly on_start?: boolean;
            /** @example 0 *\/6 * * * */
            readonly schedule?: string;
        };
        readonly "dto.RuntimeOIDCDTO": {
            /**
             * @example [
             *       "admins"
             *     ]
             */
            readonly allowed_groups?: readonly string[];
            /** @example seasonfill */
            readonly client_id?: string;
            /** @description ClientSecret is write-only: GET responses NEVER contain a value. */
            readonly client_secret?: string;
            readonly client_secret_configured?: boolean;
            readonly client_secret_env_override?: boolean;
            /** @example groups */
            readonly groups_claim?: string;
            /** @example https://keycloak.example.com/realms/homelab */
            readonly issuer?: string;
            /** @example https://seasonfill.example.com/api/v1/auth/oidc/callback */
            readonly redirect_url?: string;
            /**
             * @example [
             *       "openid",
             *       "profile",
             *       "email"
             *     ]
             */
            readonly scopes?: readonly string[];
            /** @example preferred_username */
            readonly username_claim?: string;
        };
        readonly "dto.RuntimeRateLimitDTO": {
            /** @example 10 */
            readonly burst?: number;
            /** @example 30 */
            readonly rpm?: number;
        };
        readonly "dto.RuntimeScanDTO": {
            /** @example 15m */
            readonly cooldown_sweep?: string;
            /** @example 60s */
            readonly shutdown_grace?: string;
        };
        readonly "dto.Scan": {
            readonly candidates_found?: number;
            readonly created_at?: string;
            readonly dry_run?: boolean;
            readonly error_message?: string;
            readonly errors_count?: number;
            readonly finished_at?: string;
            readonly grabs_failed?: number;
            readonly grabs_performed?: number;
            /** @example 7b3d4a92-1234-4abc-9def-000000000001 */
            readonly id?: string;
            /** @example alpha */
            readonly instance?: string;
            readonly series_scanned?: number;
            readonly started_at?: string;
            /**
             * @example completed
             * @enum {string}
             */
            readonly status?: DtoScanStatus;
            /**
             * @example cron
             * @enum {string}
             */
            readonly trigger?: DtoScanTrigger;
        };
        readonly "dto.ScanConflictResponse": {
            /** @example SCAN_IN_PROGRESS */
            readonly code?: string;
            /** @example scan already running */
            readonly error?: string;
            /** @example alpha */
            readonly instance?: string;
        };
        readonly "dto.ScanList": {
            readonly items?: readonly components["schemas"]["dto.Scan"][];
            readonly next_cursor?: string;
        };
        readonly "dto.ScanNotFoundResponse": {
            /** @example unknown instance */
            readonly error?: string;
            /** @example alpha */
            readonly instance?: string;
        };
        readonly "dto.ScanTriggerItem": {
            readonly candidates_found?: number;
            readonly errors?: number;
            readonly finished_at?: string;
            /** @example alpha */
            readonly instance?: string;
            /** @example 7b3d4a92-1234-4abc-9def-000000000001 */
            readonly scan_run_id?: string;
            readonly series_scanned?: number;
            readonly started_at?: string;
            /**
             * @example completed
             * @enum {string}
             */
            readonly status?: DtoScanTriggerItemStatus;
        };
        readonly "dto.ScanTriggerRequest": {
            readonly dry_run?: boolean;
            /** @example alpha */
            readonly instance?: string;
            readonly series_ids?: readonly number[];
        };
        readonly "dto.SeriesSearchItem": {
            /** @example 8 */
            readonly missing_aired_count?: number;
            /** @example true */
            readonly monitored?: boolean;
            /** @example 2 */
            readonly season_count?: number;
            /** @example 122 */
            readonly series_id?: number;
            /** @example Severance */
            readonly title?: string;
        };
        readonly "dto.SeriesSearchList": {
            readonly items?: readonly components["schemas"]["dto.SeriesSearchItem"][];
            /** @example 142 */
            readonly total?: number;
        };
        readonly "dto.SessionResponse": {
            /** @example false */
            readonly auto_generated?: boolean;
            /** @example true */
            readonly ok?: boolean;
            /** @example admin */
            readonly username?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export enum PathsDecisionsGetParametersQueryDecision {
    grab = "grab",
    skip = "skip",
    blocked_cooldown = "blocked_cooldown",
    already_optimal = "already_optimal",
    expired = "expired",
    error = "error"
}
export enum PathsGrabsGetParametersQueryStatus {
    grabbed = "grabbed",
    imported = "imported",
    import_failed = "import_failed",
    grab_failed = "grab_failed",
    expired = "expired"
}
export enum PathsInstancesNameSeriesGetParametersQueryMonitored {
    true = "true",
    false = "false",
    any = "any"
}
export enum PathsScansGetParametersQueryStatus {
    running = "running",
    completed = "completed",
    failed = "failed",
    aborted = "aborted"
}
export enum DtoDecisionCategory {
    all_complete = "all_complete",
    sonarr_handles = "sonarr_handles",
    action_taken = "action_taken",
    blocked = "blocked",
    nothing_found = "nothing_found",
    error = "error",
    unknown = "unknown"
}
export enum DtoDecisionDecision {
    grab = "grab",
    skip = "skip",
    blocked_cooldown = "blocked_cooldown",
    already_optimal = "already_optimal",
    expired = "expired",
    error = "error"
}
export enum DtoGrabStatus {
    grabbed = "grabbed",
    imported = "imported",
    import_failed = "import_failed",
    grab_failed = "grab_failed",
    expired = "expired"
}
export enum DtoInstanceHealth {
    Available = "Available",
    UnavailableAuth = "UnavailableAuth",
    UnavailableNetwork = "UnavailableNetwork",
    UnavailableUnknown = "UnavailableUnknown"
}
export enum DtoInstanceMode {
    auto = "auto",
    manual = "manual"
}
export enum DtoInstanceCooldownMode {
    smart = "smart",
    strict = "strict"
}
export enum DtoInstanceDetailMode {
    auto = "auto",
    manual = "manual"
}
export enum DtoInstanceTagsMode {
    include = "include",
    exclude = "exclude",
    off = "off"
}
export enum DtoReadyStatusStatus {
    ok = "ok",
    unavailable = "unavailable"
}
export enum DtoScanStatus {
    running = "running",
    completed = "completed",
    failed = "failed",
    aborted = "aborted",
    cancelled = "cancelled"
}
export enum DtoScanTrigger {
    cron = "cron",
    manual = "manual",
    webhook = "webhook"
}
export enum DtoScanTriggerItemStatus {
    completed = "completed",
    failed = "failed",
    running = "running",
    aborted = "aborted",
    cancelled = "cancelled"
}
export type operations = Record<string, never>;
