import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { loginWithPassword, logout, getSession, changePassword } from './auth';

describe('lib/auth', () => {
  const origFetch = globalThis.fetch;
  let fetchMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    fetchMock = vi.fn();
    globalThis.fetch = fetchMock as unknown as typeof fetch;
  });
  afterEach(() => { globalThis.fetch = origFetch; });

  function ok(body: unknown, status = 200) {
    return new Response(JSON.stringify(body), {
      status, headers: { 'Content-Type': 'application/json' },
    });
  }
  function noContent() { return new Response(null, { status: 204 }); }

  it('loginWithPassword POSTs to /api/v1/auth/login with {username,password}', async () => {
    fetchMock.mockResolvedValue(ok({ ok: true, username: 'admin', auto_generated: false }));
    await loginWithPassword({ username: 'admin', password: 'hunter22' });
    expect(fetchMock).toHaveBeenCalledTimes(1);
    const [url, init] = fetchMock.mock.calls[0] as [string, RequestInit];
    expect(url).toBe('/api/v1/auth/login');
    expect(init.method).toBe('POST');
    expect(JSON.parse(init.body as string)).toEqual({ username: 'admin', password: 'hunter22' });
  });

  it('logout DELETEs /api/v1/auth/session', async () => {
    fetchMock.mockResolvedValue(noContent());
    await logout();
    const [url, init] = fetchMock.mock.calls[0] as [string, RequestInit];
    expect(url).toBe('/api/v1/auth/session');
    expect(init.method).toBe('DELETE');
  });

  it('getSession GETs /api/v1/auth/session and remaps auto_generated → autoGenerated', async () => {
    fetchMock.mockResolvedValue(ok({ ok: true, username: 'admin', auto_generated: true }));
    const s = await getSession();
    const [url, init] = fetchMock.mock.calls[0] as [string, RequestInit];
    expect(url).toBe('/api/v1/auth/session');
    expect(init.method ?? 'GET').toBe('GET');
    expect(s).toEqual({ username: 'admin', autoGenerated: true });
  });

  it('changePassword POSTs to /api/v1/auth/password with {current,new}', async () => {
    fetchMock.mockResolvedValue(noContent());
    await changePassword({ current: 'old', newPassword: 'newpassword123' });
    const [url, init] = fetchMock.mock.calls[0] as [string, RequestInit];
    expect(url).toBe('/api/v1/auth/password');
    expect(init.method).toBe('POST');
    expect(JSON.parse(init.body as string)).toEqual({ current: 'old', new: 'newpassword123' });
  });
});
