package repositories

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"gorm.io/gorm"

	"github.com/alexmorbo/seasonfill/application/ports"
	"github.com/alexmorbo/seasonfill/infrastructure/database"
	"github.com/alexmorbo/seasonfill/internal/runtime"
)

const runtimeConfigID = uint(1)

type RuntimeConfigRepository struct{ db *gorm.DB }

func NewRuntimeConfigRepository(db *gorm.DB) *RuntimeConfigRepository {
	return &RuntimeConfigRepository{db: db}
}

func (r *RuntimeConfigRepository) Get(ctx context.Context) (ports.RuntimeConfigRow, error) {
	var m database.RuntimeConfigModel
	err := dbFromContext(ctx, r.db).WithContext(ctx).
		Where("id = ?", runtimeConfigID).First(&m).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return ports.RuntimeConfigRow{}, ports.ErrNotFound
		}
		return ports.RuntimeConfigRow{}, fmt.Errorf("get runtime_config: %w", err)
	}
	row := ports.RuntimeConfigRow{
		Cron: runtime.CronSnapshot{
			Enabled: m.CronEnabled, Schedule: m.CronSchedule,
			OnStart: m.CronOnStart,
			Jitter:  time.Duration(m.CronJitterSeconds) * time.Second,
		},
		Scan: runtime.ScanSnapshot{
			ShutdownGrace: time.Duration(m.ScanShutdownGraceSec) * time.Second,
			CooldownSweep: time.Duration(m.ScanCooldownSweepSec) * time.Second,
		},
		DryRun: m.DryRun,
		GlobalRateLimit: runtime.RateLimitSnapshot{
			RPM: m.GlobalRPM, Burst: m.GlobalBurst,
		},
		Auth: runtime.AuthSnapshot{
			SessionTTL:   time.Duration(m.AuthSessionTTLSec) * time.Second,
			SecureCookie: m.AuthSecureCookie,
		},
		APIKeyCiphertext:    m.APIKeyCiphertext,
		APIKeyAutoGenerated: m.APIKeyAutoGenerated,
	}
	row.UpdatedAt = m.UpdatedAt
	if m.AuthTrustedProxies != "" {
		_ = json.Unmarshal([]byte(m.AuthTrustedProxies), &row.Auth.TrustedProxies)
	}
	return row, nil
}

func (r *RuntimeConfigRepository) Upsert(ctx context.Context, snap runtime.Snapshot) error {
	proxies, _ := json.Marshal(snap.Auth.TrustedProxies)
	now := time.Now().UTC()
	db := dbFromContext(ctx, r.db).WithContext(ctx)
	var existing database.RuntimeConfigModel
	err := db.Where("id = ?", runtimeConfigID).First(&existing).Error
	switch {
	case err == nil:
		existing.CronEnabled = snap.Cron.Enabled
		existing.CronSchedule = snap.Cron.Schedule
		existing.CronOnStart = snap.Cron.OnStart
		existing.CronJitterSeconds = int(snap.Cron.Jitter / time.Second)
		existing.ScanShutdownGraceSec = int(snap.Scan.ShutdownGrace / time.Second)
		existing.ScanCooldownSweepSec = int(snap.Scan.CooldownSweep / time.Second)
		existing.DryRun = snap.DryRun
		existing.GlobalRPM = snap.GlobalRateLimit.RPM
		existing.GlobalBurst = snap.GlobalRateLimit.Burst
		existing.AuthSessionTTLSec = int(snap.Auth.SessionTTL / time.Second)
		existing.AuthSecureCookie = snap.Auth.SecureCookie
		existing.AuthTrustedProxies = string(proxies)
		existing.UpdatedAt = now
		return db.Save(&existing).Error
	case errors.Is(err, gorm.ErrRecordNotFound):
		row := database.RuntimeConfigModel{
			ID: runtimeConfigID,
			CronEnabled: snap.Cron.Enabled, CronSchedule: snap.Cron.Schedule,
			CronOnStart:       snap.Cron.OnStart,
			CronJitterSeconds: int(snap.Cron.Jitter / time.Second),
			ScanShutdownGraceSec: int(snap.Scan.ShutdownGrace / time.Second),
			ScanCooldownSweepSec: int(snap.Scan.CooldownSweep / time.Second),
			DryRun:    snap.DryRun,
			GlobalRPM: snap.GlobalRateLimit.RPM, GlobalBurst: snap.GlobalRateLimit.Burst,
			AuthSessionTTLSec:  int(snap.Auth.SessionTTL / time.Second),
			AuthSecureCookie:   snap.Auth.SecureCookie,
			AuthTrustedProxies: string(proxies),
			CreatedAt:          now, UpdatedAt: now,
		}
		return db.Create(&row).Error
	default:
		return fmt.Errorf("upsert runtime_config: %w", err)
	}
}

func (r *RuntimeConfigRepository) SaveAPIKey(ctx context.Context, ct []byte, autoGen bool) error {
	now := time.Now().UTC()
	db := dbFromContext(ctx, r.db).WithContext(ctx)
	var existing database.RuntimeConfigModel
	err := db.Where("id = ?", runtimeConfigID).First(&existing).Error
	switch {
	case err == nil:
		existing.APIKeyCiphertext = ct
		existing.APIKeyAutoGenerated = autoGen
		existing.UpdatedAt = now
		return db.Save(&existing).Error
	case errors.Is(err, gorm.ErrRecordNotFound):
		// Seed defaults so a partial row is still loadable later.
		row := database.RuntimeConfigModel{
			ID:                  runtimeConfigID,
			APIKeyCiphertext:    ct,
			APIKeyAutoGenerated: autoGen,
			CreatedAt:           now, UpdatedAt: now,
			CronEnabled:       true,
			CronSchedule:      "0 */6 * * *",
			DryRun:            true,
			GlobalRPM:         30,
			GlobalBurst:       10,
			AuthSessionTTLSec: int((12 * time.Hour) / time.Second),
		}
		return db.Create(&row).Error
	default:
		return fmt.Errorf("save api key: %w", err)
	}
}

var _ ports.RuntimeConfigRepository = (*RuntimeConfigRepository)(nil)
