package repositories

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/alexmorbo/seasonfill/application/ports"
	"github.com/alexmorbo/seasonfill/internal/runtime"
)

func TestRuntimeConfigRepository_GetNotFound(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)

	_, err := repo.Get(context.Background())
	require.ErrorIs(t, err, ports.ErrNotFound)
}

func TestRuntimeConfigRepository_UpsertAndGet(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	snap := runtime.Snapshot{
		Cron: runtime.CronSnapshot{
			Enabled:  true,
			Schedule: "0 12 * * *",
			OnStart:  false,
			Jitter:   2 * time.Minute,
		},
		Scan: runtime.ScanSnapshot{
			ShutdownGrace: 90 * time.Second,
			CooldownSweep: 20 * time.Minute,
		},
		DryRun: false,
		GlobalRateLimit: runtime.RateLimitSnapshot{
			RPM: 60, Burst: 20,
		},
		Auth: runtime.AuthSnapshot{
			SessionTTL:     24 * time.Hour,
			SecureCookie:   true,
			TrustedProxies: []string{"10.0.0.1", "10.0.0.2"},
		},
	}

	require.NoError(t, repo.Upsert(ctx, snap, nil))

	row, err := repo.Get(ctx)
	require.NoError(t, err)
	assert.Equal(t, snap.Cron.Enabled, row.Cron.Enabled)
	assert.Equal(t, snap.Cron.Schedule, row.Cron.Schedule)
	assert.Equal(t, snap.Cron.Jitter, row.Cron.Jitter)
	assert.Equal(t, snap.DryRun, row.DryRun)
	assert.Equal(t, snap.GlobalRateLimit.RPM, row.GlobalRateLimit.RPM)
	assert.Equal(t, snap.Auth.SessionTTL, row.Auth.SessionTTL)
	assert.Equal(t, snap.Auth.SecureCookie, row.Auth.SecureCookie)
	assert.Equal(t, snap.Auth.TrustedProxies, row.Auth.TrustedProxies)
}

func TestRuntimeConfigRepository_SaveAPIKey_Fresh(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	ct := []byte{0x01, 0x02, 0x03}
	require.NoError(t, repo.SaveAPIKey(ctx, ct, true))

	row, err := repo.Get(ctx)
	require.NoError(t, err)
	assert.Equal(t, ct, row.APIKeyCiphertext)
	assert.True(t, row.APIKeyAutoGenerated)
	assert.True(t, row.Cron.Enabled)
	assert.Equal(t, "0 */6 * * *", row.Cron.Schedule)
}

func TestRuntimeConfigRepository_SaveAPIKey_Existing(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	snap := runtime.Defaults()
	require.NoError(t, repo.Upsert(ctx, snap, nil))

	ct := []byte{0x04, 0x05, 0x06}
	require.NoError(t, repo.SaveAPIKey(ctx, ct, false))

	row, err := repo.Get(ctx)
	require.NoError(t, err)
	assert.Equal(t, ct, row.APIKeyCiphertext)
	assert.False(t, row.APIKeyAutoGenerated)
	assert.Equal(t, snap.Cron.Schedule, row.Cron.Schedule)
}

func TestRuntimeConfigRepository_Upsert_StaleIUS_Rejects(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	snap := runtime.Defaults()
	require.NoError(t, repo.Upsert(ctx, snap, nil))
	row, err := repo.Get(ctx)
	require.NoError(t, err)
	staleHeader := row.UpdatedAt.Add(-1 * time.Second)

	snap.Cron.Schedule = "0 0 * * *"
	require.ErrorIs(t, repo.Upsert(ctx, snap, &staleHeader), ports.ErrStaleWrite)

	got, err := repo.Get(ctx)
	require.NoError(t, err)
	assert.NotEqual(t, "0 0 * * *", got.Cron.Schedule, "stale write must not persist")
}

func TestRuntimeConfigRepository_Upsert_FreshIUS_Writes(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	snap := runtime.Defaults()
	require.NoError(t, repo.Upsert(ctx, snap, nil))
	row, err := repo.Get(ctx)
	require.NoError(t, err)
	fresh := row.UpdatedAt.Truncate(time.Second)

	snap.Cron.Schedule = "0 0 * * *"
	require.NoError(t, repo.Upsert(ctx, snap, &fresh))
	got, err := repo.Get(ctx)
	require.NoError(t, err)
	assert.Equal(t, "0 0 * * *", got.Cron.Schedule)
}

func TestRuntimeConfigRepository_Upsert_NoIUS_LWW(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	snap := runtime.Defaults()
	require.NoError(t, repo.Upsert(ctx, snap, nil))
	snap.Cron.Schedule = "30 * * * *"
	require.NoError(t, repo.Upsert(ctx, snap, nil))
	got, err := repo.Get(ctx)
	require.NoError(t, err)
	assert.Equal(t, "30 * * * *", got.Cron.Schedule)
}

func TestRuntimeConfigRepository_Upsert_FreshRow_IgnoresIUS(t *testing.T) {
	// First ever PUT — no existing row to be stale against.
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	header := time.Now().UTC().Add(-time.Hour)
	snap := runtime.Defaults()
	require.NoError(t, repo.Upsert(ctx, snap, &header))
}

func TestRuntimeConfigRepository_AuthModes_RoundTrip(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	snap := runtime.Defaults()
	snap.Auth.Mode = runtime.AuthModeBasic
	snap.Auth.LocalBypass = true
	snap.Auth.LocalNetworks = []string{"127.0.0.0/8", "10.0.0.0/8"}
	snap.Auth.SessionEpoch = 123456789

	require.NoError(t, repo.Upsert(ctx, snap, nil))
	row, err := repo.Get(ctx)
	require.NoError(t, err)
	assert.Equal(t, runtime.AuthModeBasic, row.Auth.Mode)
	assert.True(t, row.Auth.LocalBypass)
	assert.Equal(t, []string{"127.0.0.0/8", "10.0.0.0/8"}, row.Auth.LocalNetworks)
	assert.Equal(t, int64(123456789), row.Auth.SessionEpoch)
}

func TestRuntimeConfigRepository_AuthModeNormalizesEmpty(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	snap := runtime.Defaults()
	snap.Auth.Mode = "" // legacy / mis-seeded row
	require.NoError(t, repo.Upsert(ctx, snap, nil))
	row, err := repo.Get(ctx)
	require.NoError(t, err)
	assert.Equal(t, runtime.AuthModeForms, row.Auth.Mode,
		"empty mode must normalize to forms")
}

func TestRuntimeConfigRepository_LocalNetworksFallback(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	snap := runtime.Defaults()
	snap.Auth.LocalNetworks = nil
	require.NoError(t, repo.Upsert(ctx, snap, nil))
	row, err := repo.Get(ctx)
	require.NoError(t, err)
	// Empty list → fall back to the hardcoded default network set so
	// the bypass middleware never operates on an empty allow-list by
	// accident.
	assert.NotEmpty(t, row.Auth.LocalNetworks)
	assert.Contains(t, row.Auth.LocalNetworks, "127.0.0.0/8")
}
