package repositories

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"gorm.io/gorm"

	"github.com/alexmorbo/seasonfill/application/ports"
	"github.com/alexmorbo/seasonfill/infrastructure/database"
	"github.com/alexmorbo/seasonfill/internal/runtime"
)

const runtimeConfigID = uint(1)

type RuntimeConfigRepository struct{ db *gorm.DB }

func NewRuntimeConfigRepository(db *gorm.DB) *RuntimeConfigRepository {
	return &RuntimeConfigRepository{db: db}
}

func (r *RuntimeConfigRepository) Get(ctx context.Context) (ports.RuntimeConfigRow, error) {
	var m database.RuntimeConfigModel
	err := dbFromContext(ctx, r.db).WithContext(ctx).
		Where("id = ?", runtimeConfigID).First(&m).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return ports.RuntimeConfigRow{}, ports.ErrNotFound
		}
		return ports.RuntimeConfigRow{}, fmt.Errorf("get runtime_config: %w", err)
	}
	row := ports.RuntimeConfigRow{
		Cron: runtime.CronSnapshot{
			Enabled: m.CronEnabled, Schedule: m.CronSchedule,
			OnStart: m.CronOnStart,
			Jitter:  time.Duration(m.CronJitterSeconds) * time.Second,
		},
		Scan: runtime.ScanSnapshot{
			ShutdownGrace: time.Duration(m.ScanShutdownGraceSec) * time.Second,
			CooldownSweep: time.Duration(m.ScanCooldownSweepSec) * time.Second,
		},
		DryRun: m.DryRun,
		GlobalRateLimit: runtime.RateLimitSnapshot{
			RPM: m.GlobalRPM, Burst: m.GlobalBurst,
		},
		Auth: runtime.AuthSnapshot{
			SessionTTL:   time.Duration(m.AuthSessionTTLSec) * time.Second,
			SecureCookie: m.AuthSecureCookie,
			Mode:         normalizeAuthMode(m.AuthMode),
			LocalBypass:  m.AuthLocalBypass,
			SessionEpoch: m.AuthSessionEpoch,
		},
		APIKeyCiphertext:    m.APIKeyCiphertext,
		APIKeyAutoGenerated: m.APIKeyAutoGenerated,
	}
	row.UpdatedAt = m.UpdatedAt
	if m.AuthTrustedProxies != "" {
		_ = json.Unmarshal([]byte(m.AuthTrustedProxies), &row.Auth.TrustedProxies)
	}
	if m.AuthLocalNetworks != "" {
		_ = json.Unmarshal([]byte(m.AuthLocalNetworks), &row.Auth.LocalNetworks)
	}
	if len(row.Auth.LocalNetworks) == 0 {
		row.Auth.LocalNetworks = runtime.DefaultAuthLocalNetworks()
	}
	row.Auth.OIDC = runtime.OIDCSnapshot{
		Issuer:        m.OIDCIssuer,
		ClientID:      m.OIDCClientID,
		RedirectURL:   m.OIDCRedirectURL,
		UsernameClaim: m.OIDCUsernameClaim,
	}
	if m.OIDCScopes != "" {
		_ = json.Unmarshal([]byte(m.OIDCScopes), &row.Auth.OIDC.Scopes)
	}
	if len(row.Auth.OIDC.Scopes) == 0 {
		row.Auth.OIDC.Scopes = runtime.DefaultOIDCSnapshot().Scopes
	}
	if row.Auth.OIDC.UsernameClaim == "" {
		row.Auth.OIDC.UsernameClaim = runtime.DefaultOIDCSnapshot().UsernameClaim
	}
	if m.OIDCAllowedGroups != "" {
		_ = json.Unmarshal([]byte(m.OIDCAllowedGroups), &row.Auth.OIDC.AllowedGroups)
	}
	if row.Auth.OIDC.AllowedGroups == nil {
		row.Auth.OIDC.AllowedGroups = []string{}
	}
	return row, nil
}

// normalizeAuthMode guards against legacy rows / SQLite upgrades that
// stored an empty string before the column had a default applied by
// the v2 migration. Falls back to forms (the safe pre-036 behaviour).
func normalizeAuthMode(raw string) string {
	switch raw {
	case runtime.AuthModeBasic, runtime.AuthModeNone, runtime.AuthModeForms, runtime.AuthModeOIDC:
		return raw
	default:
		return runtime.AuthModeForms
	}
}

// Upsert writes the singleton row. When ifUnmodifiedSince != nil and
// the existing row exists with updated_at strictly newer than the
// header value (second-truncated), returns ports.ErrStaleWrite
// without writing. The "row missing → create fresh" path is taken
// regardless of ifUnmodifiedSince (the first ever PUT can't be stale).
func (r *RuntimeConfigRepository) Upsert(
	ctx context.Context,
	snap runtime.Snapshot,
	ifUnmodifiedSince *time.Time,
) error {
	proxies, _ := json.Marshal(snap.Auth.TrustedProxies)
	networks, _ := json.Marshal(snap.Auth.LocalNetworks)
	oidcScopes, _ := json.Marshal(snap.Auth.OIDC.Scopes)
	oidcGroups, _ := json.Marshal(snap.Auth.OIDC.AllowedGroups)

	return dbFromContext(ctx, r.db).WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		now := time.Now().UTC()

		var existing database.RuntimeConfigModel
		err := tx.Where("id = ?", runtimeConfigID).First(&existing).Error
		switch {
		case err == nil:
			if ifUnmodifiedSince != nil {
				stored := existing.UpdatedAt.Truncate(time.Second)
				provided := ifUnmodifiedSince.Truncate(time.Second)
				if stored.After(provided) {
					return ports.ErrStaleWrite
				}
			}
			existing.CronEnabled = snap.Cron.Enabled
			existing.CronSchedule = snap.Cron.Schedule
			existing.CronOnStart = snap.Cron.OnStart
			existing.CronJitterSeconds = int(snap.Cron.Jitter / time.Second)
			existing.ScanShutdownGraceSec = int(snap.Scan.ShutdownGrace / time.Second)
			existing.ScanCooldownSweepSec = int(snap.Scan.CooldownSweep / time.Second)
			existing.DryRun = snap.DryRun
			existing.GlobalRPM = snap.GlobalRateLimit.RPM
			existing.GlobalBurst = snap.GlobalRateLimit.Burst
			existing.AuthSessionTTLSec = int(snap.Auth.SessionTTL / time.Second)
			existing.AuthSecureCookie = snap.Auth.SecureCookie
			existing.AuthTrustedProxies = string(proxies)
			existing.AuthMode = snap.Auth.Mode
			existing.AuthLocalBypass = snap.Auth.LocalBypass
			existing.AuthLocalNetworks = string(networks)
			existing.AuthSessionEpoch = snap.Auth.SessionEpoch
			existing.OIDCIssuer = snap.Auth.OIDC.Issuer
			existing.OIDCClientID = snap.Auth.OIDC.ClientID
			existing.OIDCRedirectURL = snap.Auth.OIDC.RedirectURL
			existing.OIDCScopes = string(oidcScopes)
			existing.OIDCUsernameClaim = snap.Auth.OIDC.UsernameClaim
			existing.OIDCAllowedGroups = string(oidcGroups)
			existing.UpdatedAt = now
			return tx.Save(&existing).Error
		case errors.Is(err, gorm.ErrRecordNotFound):
			row := database.RuntimeConfigModel{
				ID:          runtimeConfigID,
				CronEnabled: snap.Cron.Enabled, CronSchedule: snap.Cron.Schedule,
				CronOnStart:          snap.Cron.OnStart,
				CronJitterSeconds:    int(snap.Cron.Jitter / time.Second),
				ScanShutdownGraceSec: int(snap.Scan.ShutdownGrace / time.Second),
				ScanCooldownSweepSec: int(snap.Scan.CooldownSweep / time.Second),
				DryRun:               snap.DryRun,
				GlobalRPM:            snap.GlobalRateLimit.RPM, GlobalBurst: snap.GlobalRateLimit.Burst,
				AuthSessionTTLSec:  int(snap.Auth.SessionTTL / time.Second),
				AuthSecureCookie:   snap.Auth.SecureCookie,
				AuthTrustedProxies: string(proxies),
				AuthMode:           snap.Auth.Mode,
				AuthLocalBypass:    snap.Auth.LocalBypass,
				AuthLocalNetworks:  string(networks),
				AuthSessionEpoch:   snap.Auth.SessionEpoch,
				OIDCIssuer:         snap.Auth.OIDC.Issuer,
				OIDCClientID:       snap.Auth.OIDC.ClientID,
				OIDCRedirectURL:    snap.Auth.OIDC.RedirectURL,
				OIDCScopes:         string(oidcScopes),
				OIDCUsernameClaim:  snap.Auth.OIDC.UsernameClaim,
				OIDCAllowedGroups:  string(oidcGroups),
				CreatedAt:          now, UpdatedAt: now,
			}
			return tx.Create(&row).Error
		default:
			return fmt.Errorf("upsert runtime_config: %w", err)
		}
	})
}

func (r *RuntimeConfigRepository) SaveAPIKey(ctx context.Context, ct []byte, autoGen bool) error {
	now := time.Now().UTC()
	db := dbFromContext(ctx, r.db).WithContext(ctx)
	var existing database.RuntimeConfigModel
	err := db.Where("id = ?", runtimeConfigID).First(&existing).Error
	switch {
	case err == nil:
		existing.APIKeyCiphertext = ct
		existing.APIKeyAutoGenerated = autoGen
		existing.UpdatedAt = now
		return db.Save(&existing).Error
	case errors.Is(err, gorm.ErrRecordNotFound):
		// Seed defaults so a partial row is still loadable later.
		def := runtime.Defaults()
		proxiesJSON, _ := json.Marshal(def.Auth.TrustedProxies)
		networksJSON, _ := json.Marshal(def.Auth.LocalNetworks)
		row := database.RuntimeConfigModel{
			ID:                  runtimeConfigID,
			APIKeyCiphertext:    ct,
			APIKeyAutoGenerated: autoGen,
			CreatedAt:           now, UpdatedAt: now,
			CronEnabled:          def.Cron.Enabled,
			CronSchedule:         def.Cron.Schedule,
			CronJitterSeconds:    int(def.Cron.Jitter / time.Second),
			ScanShutdownGraceSec: int(def.Scan.ShutdownGrace / time.Second),
			ScanCooldownSweepSec: int(def.Scan.CooldownSweep / time.Second),
			DryRun:               def.DryRun,
			GlobalRPM:            def.GlobalRateLimit.RPM,
			GlobalBurst:          def.GlobalRateLimit.Burst,
			AuthSessionTTLSec:    int(def.Auth.SessionTTL / time.Second),
			AuthSecureCookie:     def.Auth.SecureCookie,
			AuthTrustedProxies:   string(proxiesJSON),
			AuthMode:             def.Auth.Mode,
			AuthLocalBypass:      def.Auth.LocalBypass,
			AuthLocalNetworks:    string(networksJSON),
			AuthSessionEpoch:     def.Auth.SessionEpoch,
			OIDCIssuer:           def.Auth.OIDC.Issuer,
			OIDCClientID:         def.Auth.OIDC.ClientID,
			OIDCRedirectURL:      def.Auth.OIDC.RedirectURL,
			OIDCScopes:           string(mustJSON(def.Auth.OIDC.Scopes)),
			OIDCUsernameClaim:    def.Auth.OIDC.UsernameClaim,
			OIDCAllowedGroups:    string(mustJSON(def.Auth.OIDC.AllowedGroups)),
		}
		return db.Create(&row).Error
	default:
		return fmt.Errorf("save api key: %w", err)
	}
}

func mustJSON(v any) []byte { b, _ := json.Marshal(v); return b }

var _ ports.RuntimeConfigRepository = (*RuntimeConfigRepository)(nil)
