package repositories

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/alexmorbo/seasonfill/application/ports"
	"github.com/alexmorbo/seasonfill/internal/runtime"
)

func TestRuntimeConfigRepository_GetNotFound(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)

	_, err := repo.Get(context.Background())
	require.ErrorIs(t, err, ports.ErrNotFound)
}

func TestRuntimeConfigRepository_UpsertAndGet(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	snap := runtime.Snapshot{
		Cron: runtime.CronSnapshot{
			Enabled:  true,
			Schedule: "0 12 * * *",
			OnStart:  false,
			Jitter:   2 * time.Minute,
		},
		Scan: runtime.ScanSnapshot{
			ShutdownGrace: 90 * time.Second,
			CooldownSweep: 20 * time.Minute,
		},
		DryRun: false,
		GlobalRateLimit: runtime.RateLimitSnapshot{
			RPM: 60, Burst: 20,
		},
		Auth: runtime.AuthSnapshot{
			SessionTTL:     24 * time.Hour,
			SecureCookie:   true,
			TrustedProxies: []string{"10.0.0.1", "10.0.0.2"},
		},
	}

	require.NoError(t, repo.Upsert(ctx, snap))

	row, err := repo.Get(ctx)
	require.NoError(t, err)
	assert.Equal(t, snap.Cron.Enabled, row.Cron.Enabled)
	assert.Equal(t, snap.Cron.Schedule, row.Cron.Schedule)
	assert.Equal(t, snap.Cron.Jitter, row.Cron.Jitter)
	assert.Equal(t, snap.DryRun, row.DryRun)
	assert.Equal(t, snap.GlobalRateLimit.RPM, row.GlobalRateLimit.RPM)
	assert.Equal(t, snap.Auth.SessionTTL, row.Auth.SessionTTL)
	assert.Equal(t, snap.Auth.SecureCookie, row.Auth.SecureCookie)
	assert.Equal(t, snap.Auth.TrustedProxies, row.Auth.TrustedProxies)
}

func TestRuntimeConfigRepository_SaveAPIKey_Fresh(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	ct := []byte{0x01, 0x02, 0x03}
	require.NoError(t, repo.SaveAPIKey(ctx, ct, true))

	row, err := repo.Get(ctx)
	require.NoError(t, err)
	assert.Equal(t, ct, row.APIKeyCiphertext)
	assert.True(t, row.APIKeyAutoGenerated)
	assert.True(t, row.Cron.Enabled)
	assert.Equal(t, "0 */6 * * *", row.Cron.Schedule)
}

func TestRuntimeConfigRepository_SaveAPIKey_Existing(t *testing.T) {
	db := setupTestDB(t)
	repo := NewRuntimeConfigRepository(db)
	ctx := context.Background()

	snap := runtime.Defaults()
	require.NoError(t, repo.Upsert(ctx, snap))

	ct := []byte{0x04, 0x05, 0x06}
	require.NoError(t, repo.SaveAPIKey(ctx, ct, false))

	row, err := repo.Get(ctx)
	require.NoError(t, err)
	assert.Equal(t, ct, row.APIKeyCiphertext)
	assert.False(t, row.APIKeyAutoGenerated)
	assert.Equal(t, snap.Cron.Schedule, row.Cron.Schedule)
}
