package database

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
)

type ScanRunModel struct {
	ID              string    `gorm:"primaryKey;size:36;index:idx_scan_runs_created_at_id,priority:2;index:idx_scan_runs_started_at_id,priority:2"`
	InstanceName    string    `gorm:"size:128;index"`
	Trigger         string    `gorm:"size:32"`
	StartedAt       time.Time `gorm:"index:idx_scan_runs_started_at_id,priority:1"`
	FinishedAt      *time.Time
	Status          string `gorm:"size:32"`
	SeriesScanned   int
	CandidatesFound int
	GrabsPerformed  int
	GrabsFailed     int
	ErrorsCount     int
	ErrorMessage    string `gorm:"type:text"`
	DryRun          bool
	CreatedAt       time.Time `gorm:"index:idx_scan_runs_created_at_id,priority:1"`
	UpdatedAt       time.Time
}

func (ScanRunModel) TableName() string { return "scan_runs" }

type DecisionModel struct {
	ID              string `gorm:"primaryKey;size:36;index:idx_decisions_created_at_id,priority:2"`
	ScanRunID       string `gorm:"size:36;index"`
	InstanceName    string `gorm:"size:128;index"`
	SeriesID        int    `gorm:"index"`
	SeriesTitle     string `gorm:"size:512"`
	SeasonNumber    int
	Decision        string `gorm:"size:32"`
	Reason          string `gorm:"size:128"`
	MissingCount    int
	ExistingCount   int
	ReleasesFound   int
	CandidatesCount int
	FilteredOut     datatypes.JSON
	SelectedGUID    string `gorm:"size:512"`
	SelectedData    datatypes.JSON
	DryRunWouldGrab bool `gorm:"column:would_grab"`
	// ErrorDetail mirrors domain/decision.Decision.ErrorDetail. size:300
	// is intentional slack above the 256-rune application-layer cap so a
	// future truncation tweak does not require a schema migration.
	ErrorDetail    string    `gorm:"size:300"`
	SupersededByID *string   `gorm:"size:36"`
	CreatedAt      time.Time `gorm:"index:idx_decisions_created_at_id,priority:1"`
}

func (DecisionModel) TableName() string { return "decisions" }

type GrabRecordModel struct {
	ID                string `gorm:"primaryKey;size:36;index:idx_grab_records_created_at_id,priority:2"`
	InstanceName      string `gorm:"size:128;index:idx_grab_inst_series,priority:1;index:idx_grab_dedupe_lookup,priority:1"`
	SeriesID          int    `gorm:"index:idx_grab_inst_series,priority:2;index:idx_grab_dedupe_lookup,priority:2"`
	SeriesTitle       string `gorm:"size:512"`
	SeasonNumber      int    `gorm:"index:idx_grab_inst_series,priority:3;index:idx_grab_dedupe_lookup,priority:3"`
	ReleaseGUID       string `gorm:"size:512;index;index:idx_grab_dedupe_lookup,priority:4"`
	ReleaseTitle      string `gorm:"size:1024"`
	DownloadID        string `gorm:"size:128;index;column:download_id"`
	IndexerID         int
	IndexerName       string `gorm:"size:256"`
	CustomFormatScore int
	Quality           string `gorm:"size:128"`
	CoverageCount     int
	Status            string `gorm:"size:32;index"`
	ErrorMessage      string `gorm:"type:text"`
	ScanRunID         string `gorm:"size:36;index"`
	Attempts          int
	// TorrentHash is the qBit infohash (40-char lowercase hex) populated
	// by the OnGrab webhook handler in 039c. Nullable on purpose: rows
	// created before Phase 10 have no recorded hash and are intentionally
	// ignored by the Watchdog (D63 hash-required gate, no backfill).
	TorrentHash *string   `gorm:"column:torrent_hash;size:64"`
	CreatedAt   time.Time `gorm:"index:idx_grab_records_created_at_id,priority:1"`
	UpdatedAt   time.Time
}

func (GrabRecordModel) TableName() string { return "grab_records" }

type OriginReleaseModel struct {
	InstanceName string `gorm:"primaryKey;size:128"`
	SeriesID     int    `gorm:"primaryKey"`
	SeasonNumber int    `gorm:"primaryKey"`
	GUID         string `gorm:"size:512"`
	IndexerID    int
	IndexerName  string `gorm:"size:256"`
	Source       string `gorm:"size:32"`
	FirstSeenAt  time.Time
	LastSeenAt   time.Time
	LastUsedAt   *time.Time
}

func (OriginReleaseModel) TableName() string { return "origin_releases" }

type CooldownModel struct {
	Scope     string    `gorm:"primaryKey;size:16"`
	Key       string    `gorm:"primaryKey;size:512"`
	ExpiresAt time.Time `gorm:"index"`
	Reason    string    `gorm:"size:128"`
	CreatedAt time.Time
}

func (CooldownModel) TableName() string { return "cooldowns" }

type AdminUserModel struct {
	ID            uint   `gorm:"primaryKey"`
	Username      string `gorm:"size:128;uniqueIndex"`
	PasswordHash  string `gorm:"size:128"`
	AutoGenerated bool
	OIDCSubject   *string `gorm:"column:oidc_subject;type:text;uniqueIndex:idx_admin_users_oidc_subject,where:oidc_subject IS NOT NULL"`
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (AdminUserModel) TableName() string { return "admin_users" }

// RuntimeConfigModel — singleton row (id=1) holding all DB-stored
// runtime config except per-instance details.
type RuntimeConfigModel struct {
	ID                         uint `gorm:"primaryKey"`
	CronEnabled                bool
	CronSchedule               string `gorm:"size:64"`
	CronOnStart                bool
	CronJitterSeconds          int
	ScanShutdownGraceSec       int
	ScanCooldownSweepSec       int
	DryRun                     bool
	GlobalRPM                  int
	GlobalBurst                int
	AuthSessionTTLSec          int
	AuthSecureCookie           bool
	AuthTrustedProxies         string `gorm:"type:text"`
	AuthMode                   string `gorm:"size:16;default:forms"`
	AuthLocalBypass            bool
	AuthLocalNetworks          string `gorm:"type:text"`
	AuthSessionEpoch           int64
	OIDCIssuer                 string `gorm:"column:oidc_issuer;type:text"`
	OIDCClientID               string `gorm:"column:oidc_client_id;type:text"`
	OIDCRedirectURL            string `gorm:"column:oidc_redirect_url;type:text"`
	OIDCScopes                 string `gorm:"column:oidc_scopes;type:text"`
	OIDCUsernameClaim          string `gorm:"column:oidc_username_claim;type:text"`
	OIDCAllowedGroups          string `gorm:"column:oidc_allowed_groups;type:text"`
	OIDCGroupsClaim            string `gorm:"column:oidc_groups_claim;type:text;default:groups"`
	OIDCClientSecretCiphertext []byte `gorm:"column:oidc_client_secret_ciphertext"`
	APIKeyCiphertext           []byte
	APIKeyAutoGenerated        bool
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

func (RuntimeConfigModel) TableName() string { return "runtime_config" }

// SonarrInstanceModel — one row per Sonarr instance. Secret api_key
// is held in instance_secret to keep this row free of PII.
type SonarrInstanceModel struct {
	ID                            uint   `gorm:"primaryKey"`
	Name                          string `gorm:"size:128;uniqueIndex"`
	URL                           string `gorm:"size:512"`
	Mode                          string `gorm:"size:16"`
	TimeoutSeconds                int
	SearchTimeoutSeconds          int
	DryRun                        *bool
	TagsMode                      string `gorm:"size:16"`
	TagsInclude                   string `gorm:"type:text"`
	TagsExclude                   string `gorm:"type:text"`
	SearchRequireAllAired         bool
	SearchSkipSpecials            bool
	SearchSkipAnime               bool
	SearchMinCustomFormatScore    int
	RankingIndexerPriorityEnabled bool
	RankingOriginBonus            float64
	LimitsScanMaxSeries           int
	LimitsMaxGrabsPerScan         int
	RateLimitRPM                  int
	RateLimitBurst                int
	CooldownMode                  string `gorm:"size:16"`
	CooldownSeriesAfterGrabSec    int
	CooldownGUIDFailedGrabSec     int
	CooldownGUIDFailedImportSec   int
	RetryMaxAttempts              int
	RetryInitialBackoffSec        int
	RetryMaxBackoffSec            int
	HealthCheckRecheckAuthSec     int
	HealthCheckRecheckNetSec      int
	CreatedAt                     time.Time
	UpdatedAt                     time.Time
}

func (SonarrInstanceModel) TableName() string { return "sonarr_instance" }

// InstanceSecretModel — encrypted secret(s) per instance.
type InstanceSecretModel struct {
	InstanceID uint   `gorm:"primaryKey"`
	SecretName string `gorm:"primaryKey;size:64"`
	Ciphertext []byte `gorm:"not null"`
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (InstanceSecretModel) TableName() string { return "instance_secret" }

func NewScanID() string { return uuid.New().String() }

// InstanceQbitSettingsModel is the per-instance Watchdog configuration row.
// One row per Sonarr instance enforced by the unique index on instance_id.
// PasswordEncrypted is opaque AES-GCM ciphertext (nonce|ciphertext|tag)
// produced by the 039d HTTP handler with the `-aes-gcm-v1` HKDF subkey;
// the repo treats it as bytes.
type InstanceQbitSettingsModel struct {
	ID                     uint   `gorm:"primaryKey"`
	InstanceID             uint   `gorm:"uniqueIndex:idx_instance_qbit_settings_instance_id"`
	Enabled                bool   `gorm:"not null;default:false"`
	URL                    string `gorm:"type:text;not null"`
	Username               *string
	PasswordEncrypted      []byte         `gorm:"column:password_encrypted"`
	Category               string         `gorm:"type:text;not null;default:'sonarr'"`
	PollIntervalMinutes    int            `gorm:"not null;default:30"`
	RegrabCooldownHours    int            `gorm:"not null;default:120"`
	MaxConsecutiveNoBetter int            `gorm:"not null;default:3"`
	CustomUnregisteredMsgs datatypes.JSON `gorm:"not null"`
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (InstanceQbitSettingsModel) TableName() string { return "instance_qbit_settings" }

// WatchdogBlacklistModel parks (instance, series, season) triples that
// exhausted the consecutive-no-better budget or whose parent qBit is
// persistently unreachable. ExpiresAt is *time.Time because v1 always
// writes NULL (manual unblock only per parent 039 §Out of scope).
type WatchdogBlacklistModel struct {
	ID           uint   `gorm:"primaryKey"`
	InstanceID   uint   `gorm:"uniqueIndex:idx_watchdog_blacklist_triple,priority:1;index:idx_watchdog_blacklist_instance_id"`
	SeriesID     int    `gorm:"uniqueIndex:idx_watchdog_blacklist_triple,priority:2"`
	SeasonNumber int    `gorm:"uniqueIndex:idx_watchdog_blacklist_triple,priority:3"`
	Reason       string `gorm:"type:text;not null"`
	Consecutive  int    `gorm:"not null"`
	CreatedAt    time.Time
	ExpiresAt    *time.Time
}

func (WatchdogBlacklistModel) TableName() string { return "watchdog_blacklist" }
