package admin

import "time"

// AdminUser is the single-user admin record (Phase 7 ships single-user).
// AutoGenerated stays true while the password is still the first-run
// generated value; flips to false on explicit password set.
type AdminUser struct {
	ID            uint
	Username      string
	PasswordHash  string
	AutoGenerated bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
