-- create "app_config" table
CREATE TABLE `app_config` (
  `id` integer NOT NULL DEFAULT 1,
  `cron_enabled` boolean NOT NULL DEFAULT true,
  `cron_schedule` text NOT NULL DEFAULT '0 */6 * * *',
  `cron_on_start` boolean NOT NULL DEFAULT false,
  `cron_jitter_seconds` integer NOT NULL DEFAULT 60,
  `scan_shutdown_grace_sec` integer NOT NULL DEFAULT 60,
  `scan_cooldown_sweep_sec` integer NOT NULL DEFAULT 900,
  `dry_run` boolean NOT NULL DEFAULT true,
  `global_rpm` integer NOT NULL DEFAULT 30,
  `global_burst` integer NOT NULL DEFAULT 10,
  `auth_session_ttl_sec` integer NOT NULL DEFAULT 43200,
  `auth_secure_cookie` boolean NOT NULL DEFAULT false,
  `auth_trusted_proxies` text NOT NULL DEFAULT '[]',
  `auth_mode` text NOT NULL DEFAULT 'forms',
  `auth_local_bypass` boolean NOT NULL DEFAULT false,
  `auth_local_networks` text NOT NULL DEFAULT '[]',
  `auth_session_epoch` bigint NOT NULL DEFAULT 0,
  `oidc_issuer` text NOT NULL DEFAULT '',
  `oidc_client_id` text NOT NULL DEFAULT '',
  `oidc_redirect_url` text NOT NULL DEFAULT '',
  `oidc_scopes` text NOT NULL DEFAULT '[]',
  `oidc_username_claim` text NOT NULL DEFAULT '',
  `oidc_allowed_groups` text NOT NULL DEFAULT '[]',
  `oidc_groups_claim` text NOT NULL DEFAULT 'groups',
  `guid_rewrites` text NOT NULL DEFAULT '[]',
  `api_key_auto_generated` boolean NOT NULL DEFAULT false,
  `timezone` text NULL,
  `created_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  `updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY (`id`),
  CONSTRAINT `app_config_singleton` CHECK (id = 1)
);
-- create "sonarr_instance_settings" table
CREATE TABLE `sonarr_instance_settings` (
  `instance_name` text NOT NULL,
  `timeout_seconds` integer NOT NULL DEFAULT 10,
  `search_timeout_seconds` integer NOT NULL DEFAULT 60,
  `dry_run` boolean NULL,
  `tags_mode` text NOT NULL DEFAULT 'any',
  `tags_include` text NOT NULL DEFAULT '',
  `tags_exclude` text NOT NULL DEFAULT '',
  `search_require_all_aired` boolean NOT NULL DEFAULT false,
  `search_skip_specials` boolean NOT NULL DEFAULT true,
  `search_skip_anime` boolean NOT NULL DEFAULT false,
  `search_min_custom_format_score` integer NOT NULL DEFAULT 0,
  `ranking_indexer_priority_enabled` boolean NOT NULL DEFAULT false,
  `ranking_origin_bonus` double precision NOT NULL DEFAULT 0,
  `limits_scan_max_series` integer NOT NULL DEFAULT 0,
  `limits_max_grabs_per_scan` integer NOT NULL DEFAULT 0,
  `rate_limit_rpm` integer NOT NULL DEFAULT 30,
  `rate_limit_burst` integer NOT NULL DEFAULT 10,
  `cooldown_mode` text NOT NULL DEFAULT '',
  `cooldown_series_after_grab_sec` integer NOT NULL DEFAULT 0,
  `cooldown_guid_failed_grab_sec` integer NOT NULL DEFAULT 0,
  `cooldown_guid_failed_import_sec` integer NOT NULL DEFAULT 0,
  `retry_max_attempts` integer NOT NULL DEFAULT 0,
  `retry_initial_backoff_sec` integer NOT NULL DEFAULT 0,
  `retry_max_backoff_sec` integer NOT NULL DEFAULT 0,
  `healthcheck_recheck_auth_sec` integer NOT NULL DEFAULT 0,
  `healthcheck_recheck_net_sec` integer NOT NULL DEFAULT 0,
  `public_url` text NULL,
  `webhook_install_enabled` boolean NOT NULL DEFAULT true,
  `webhook_url_override` text NULL,
  `parse_on_grab_enabled` boolean NOT NULL DEFAULT true,
  `scan_skip_handled_seasons` boolean NOT NULL DEFAULT true,
  `updated_at` datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY (`instance_name`),
  CONSTRAINT `sonarr_instance_settings_instance_name_fkey` FOREIGN KEY (`instance_name`) REFERENCES `sonarr_instance` (`name`) ON UPDATE NO ACTION ON DELETE CASCADE
);
