//go:build integration

// D-1-5 (story 458) — verifies 000001..000007 apply cleanly on both
// backends, exercises insert + FK + composite PK + soft-delete behavior
// on the 3 per-instance projection tables (series_cache, episode_states,
// season_stats).
package integration

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
)

func TestD15_InstanceProjectionsMigrationRoundTrip(t *testing.T) {
	for _, b := range allD1Backends(t) {
		t.Run(b.name, func(t *testing.T) {
			ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
			defer cancel()

			db, m, cleanup := b.migrate(t)
			t.Cleanup(cleanup)

			// UP — applies 000001..000007 in sequence.
			require.NoError(t, m.Up())

			// Seed a series + episode row to satisfy FK targets.
			seriesTitle := "d1-5-" + uuid.NewString()
			seriesID := insertSeriesAndScanID(t, ctx, db, b.name, seriesTitle)
			episodeID := insertEpisodeAndScanID(t, ctx, db, b.name, seriesID, 1, 1)

			instance := "inst-" + uuid.NewString()[:8]
			sonarrSeriesID := int64(101)

			// series_cache happy path.
			_, err := db.ExecContext(ctx, insertSeriesCacheSQL(b.name),
				instance, sonarrSeriesID, seriesID, "the-slug")
			require.NoError(t, err, "series_cache insert should succeed")

			// series_cache dup-PK violation.
			_, err = db.ExecContext(ctx, insertSeriesCacheSQL(b.name),
				instance, sonarrSeriesID, seriesID, "the-slug-2")
			require.Error(t, err, "duplicate (instance_name, sonarr_series_id) should fail")

			// series_cache FK violation: orphan series_id.
			_, err = db.ExecContext(ctx, insertSeriesCacheSQL(b.name),
				instance, int64(999), int64(9999999), "orphan-slug")
			require.Error(t, err, "orphan series_cache series_id should fail FK")

			// episode_states happy path.
			_, err = db.ExecContext(ctx, insertEpisodeStateSQL(b.name),
				instance, episodeID, true, false)
			require.NoError(t, err, "episode_states insert should succeed")

			// episode_states dup-PK violation.
			_, err = db.ExecContext(ctx, insertEpisodeStateSQL(b.name),
				instance, episodeID, false, true)
			require.Error(t, err, "duplicate (instance_name, episode_id) should fail")

			// episode_states FK violation: orphan episode_id.
			_, err = db.ExecContext(ctx, insertEpisodeStateSQL(b.name),
				instance, int64(9999999), false, false)
			require.Error(t, err, "orphan episode_states episode_id should fail FK")

			// season_stats happy path.
			_, err = db.ExecContext(ctx, insertSeasonStatSQL(b.name),
				instance, sonarrSeriesID, 1, 10, 7)
			require.NoError(t, err, "season_stats insert should succeed")

			// season_stats dup-PK violation.
			_, err = db.ExecContext(ctx, insertSeasonStatSQL(b.name),
				instance, sonarrSeriesID, 1, 11, 8)
			require.Error(t, err, "duplicate (instance_name, sonarr_series_id, season_number) should fail")

			// season_stats NO-FK invariant: sonarr_series_id with no series_cache row succeeds.
			_, err = db.ExecContext(ctx, insertSeasonStatSQL(b.name),
				instance, int64(9999999), 1, 5, 3)
			require.NoError(t, err, "season_stats with orphan (instance, sonarr_series_id) should succeed (no FK)")

			// Soft-delete: stamp deleted_at and assert partial-index covers
			// WHERE deleted_at IS NULL by reading back exactly one active row.
			_, err = db.ExecContext(ctx, softDeleteSeriesCacheSQL(b.name),
				instance, sonarrSeriesID)
			require.NoError(t, err)
			active := countActiveSeriesCache(t, ctx, db, b.name, instance)
			require.Equal(t, 0, active, "after soft-delete, instance has 0 active series_cache rows")

			// DOWN — rolls back 000007 then earlier migrations.
			require.NoError(t, m.Down())
			for _, table := range []string{"series_cache", "episode_states", "season_stats"} {
				_, err = db.ExecContext(ctx, "SELECT 1 FROM "+table+" LIMIT 1")
				require.Errorf(t, err, "%s should be dropped after Down", table)
			}
		})
	}
}

// insertEpisodeAndScanID seeds one episode row for the given series and
// returns its autogenerated id. Portably across drivers (PG via
// RETURNING, SQLite via LastInsertId). Local helper (NOT in d1_helpers
// — out of scope from helper extraction; the only other consumer is
// d1_2_core_series_apply_test.go which has its own inline insert).
func insertEpisodeAndScanID(t *testing.T, ctx context.Context, db *sql.DB, driver string, seriesID int64, seasonNum, episodeNum int) int64 {
	t.Helper()
	var id int64
	var stmt string
	switch driver {
	case "postgres":
		stmt = `INSERT INTO episodes (series_id, season_number, episode_number, created_at, updated_at)
		        VALUES ($1, $2, $3, now(), now()) RETURNING id`
		row := db.QueryRowContext(ctx, stmt, seriesID, seasonNum, episodeNum)
		require.NoError(t, row.Scan(&id))
	case "sqlite":
		stmt = `INSERT INTO episodes (series_id, season_number, episode_number, created_at, updated_at)
		        VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)`
		res, err := db.ExecContext(ctx, stmt, seriesID, seasonNum, episodeNum)
		require.NoError(t, err)
		id, err = res.LastInsertId()
		require.NoError(t, err)
	default:
		t.Fatalf("unknown driver %q", driver)
	}
	require.Greater(t, id, int64(0))
	return id
}

func insertSeriesCacheSQL(driver string) string {
	switch driver {
	case "postgres":
		return `INSERT INTO series_cache (instance_name, sonarr_series_id, series_id, title_slug, updated_at)
		        VALUES ($1, $2, $3, $4, now())`
	case "sqlite":
		return `INSERT INTO series_cache (instance_name, sonarr_series_id, series_id, title_slug, updated_at)
		        VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)`
	}
	panic("unknown driver " + driver)
}

func insertEpisodeStateSQL(driver string) string {
	switch driver {
	case "postgres":
		return `INSERT INTO episode_states (instance_name, episode_id, monitored, has_file, updated_at)
		        VALUES ($1, $2, $3, $4, now())`
	case "sqlite":
		return `INSERT INTO episode_states (instance_name, episode_id, monitored, has_file, updated_at)
		        VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)`
	}
	panic("unknown driver " + driver)
}

func insertSeasonStatSQL(driver string) string {
	switch driver {
	case "postgres":
		return `INSERT INTO season_stats (instance_name, sonarr_series_id, season_number, episode_count, episode_file_count, updated_at)
		        VALUES ($1, $2, $3, $4, $5, now())`
	case "sqlite":
		return `INSERT INTO season_stats (instance_name, sonarr_series_id, season_number, episode_count, episode_file_count, updated_at)
		        VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)`
	}
	panic("unknown driver " + driver)
}

func softDeleteSeriesCacheSQL(driver string) string {
	switch driver {
	case "postgres":
		return `UPDATE series_cache SET deleted_at = now() WHERE instance_name = $1 AND sonarr_series_id = $2`
	case "sqlite":
		return `UPDATE series_cache SET deleted_at = CURRENT_TIMESTAMP WHERE instance_name = ? AND sonarr_series_id = ?`
	}
	panic("unknown driver " + driver)
}

func countActiveSeriesCache(t *testing.T, ctx context.Context, db *sql.DB, driver, instance string) int {
	t.Helper()
	var q string
	switch driver {
	case "postgres":
		q = `SELECT COUNT(*) FROM series_cache WHERE instance_name = $1 AND deleted_at IS NULL`
	case "sqlite":
		q = `SELECT COUNT(*) FROM series_cache WHERE instance_name = ? AND deleted_at IS NULL`
	default:
		t.Fatalf("unknown driver %q", driver)
	}
	var cnt int
	row := db.QueryRowContext(ctx, q, instance)
	require.NoError(t, row.Scan(&cnt))
	return cnt
}
