package bootstrap

import (
	"bytes"
	"context"
	"io"
	"log/slog"
	"os"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/alexmorbo/seasonfill/application/ports"
	"github.com/alexmorbo/seasonfill/internal/runtime"
	"github.com/alexmorbo/seasonfill/internal/runtime/crypto"
)

type mockRuntimeConfigRepository struct {
	row    ports.RuntimeConfigRow
	hasRow bool
	err    error
}

func (m *mockRuntimeConfigRepository) Get(ctx context.Context) (ports.RuntimeConfigRow, error) {
	if !m.hasRow {
		return ports.RuntimeConfigRow{}, ports.ErrNotFound
	}
	return m.row, m.err
}

func (m *mockRuntimeConfigRepository) Upsert(ctx context.Context, snap runtime.Snapshot, ifUnmodifiedSince *time.Time) error {
	return nil
}

func (m *mockRuntimeConfigRepository) SaveAPIKey(ctx context.Context, ct []byte, autoGen bool) error {
	m.row.APIKeyCiphertext = ct
	m.row.APIKeyAutoGenerated = autoGen
	m.hasRow = true
	return nil
}

func TestResolveAPIKey_ProvidedKeyValidatesProbe(t *testing.T) {
	ctx := context.Background()
	log := slog.Default()

	key := "my-master-key"
	cipher, err := crypto.New(key)
	require.NoError(t, err)

	probe, err := cipher.Seal([]byte(key))
	require.NoError(t, err)

	repo := &mockRuntimeConfigRepository{
		hasRow: true,
		row:    ports.RuntimeConfigRow{APIKeyCiphertext: probe},
	}

	resolved, err := ResolveAPIKey(ctx, key, repo, log)
	require.NoError(t, err)
	assert.Equal(t, key, resolved)
}

func TestResolveAPIKey_ProvidedKeyMismatch(t *testing.T) {
	ctx := context.Background()
	log := slog.Default()

	correctKey := "correct-key"
	cipher, err := crypto.New(correctKey)
	require.NoError(t, err)

	probe, err := cipher.Seal([]byte(correctKey))
	require.NoError(t, err)

	repo := &mockRuntimeConfigRepository{
		hasRow: true,
		row:    ports.RuntimeConfigRow{APIKeyCiphertext: probe},
	}

	_, err = ResolveAPIKey(ctx, "wrong-key", repo, log)
	require.Error(t, err)
	assert.ErrorIs(t, err, ErrAPIKeyMismatch)
}

func TestResolveAPIKey_NoKeyNoRowAutoGen(t *testing.T) {
	ctx := context.Background()
	log := slog.Default()

	repo := &mockRuntimeConfigRepository{hasRow: false}

	resolved, err := ResolveAPIKey(ctx, "", repo, log)
	require.NoError(t, err)
	assert.NotEmpty(t, resolved)
	assert.True(t, repo.hasRow)
	assert.True(t, repo.row.APIKeyAutoGenerated)
	assert.NotEmpty(t, repo.row.APIKeyCiphertext)
}

func TestResolveAPIKey_NoKeyWithRowFails(t *testing.T) {
	ctx := context.Background()
	log := slog.Default()

	cipher, err := crypto.New("existing-key")
	require.NoError(t, err)
	probe, err := cipher.Seal([]byte("existing-key"))
	require.NoError(t, err)

	repo := &mockRuntimeConfigRepository{
		hasRow: true,
		row:    ports.RuntimeConfigRow{APIKeyCiphertext: probe},
	}

	_, err = ResolveAPIKey(ctx, "", repo, log)
	require.ErrorIs(t, err, ErrAPIKeyMismatch)
}

func TestResolveAPIKey_ProvidedKeySavesProbe(t *testing.T) {
	ctx := context.Background()
	log := slog.Default()

	repo := &mockRuntimeConfigRepository{hasRow: false}

	key := "new-key"
	resolved, err := ResolveAPIKey(ctx, key, repo, log)
	require.NoError(t, err)
	assert.Equal(t, key, resolved)
	assert.True(t, repo.hasRow)
	assert.False(t, repo.row.APIKeyAutoGenerated)
	assert.NotEmpty(t, repo.row.APIKeyCiphertext)

	// Verify the saved probe can be opened with the same key.
	cipher, err := crypto.New(key)
	require.NoError(t, err)
	plaintext, err := cipher.Open(repo.row.APIKeyCiphertext)
	require.NoError(t, err)
	assert.Equal(t, key, string(plaintext))
}

// captureStdout temporarily redirects os.Stdout to a pipe. The returned
// function restores the original and returns whatever was written.
func captureStdout(t *testing.T) (restore func() string) {
	t.Helper()
	orig := os.Stdout
	r, w, err := os.Pipe()
	require.NoError(t, err)
	os.Stdout = w

	var buf bytes.Buffer
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		_, _ = io.Copy(&buf, r)
	}()

	return func() string {
		_ = w.Close()
		wg.Wait()
		_ = r.Close()
		os.Stdout = orig
		return buf.String()
	}
}

// captureSlogHandler is a slog.Handler that buffers every Record so tests
// can inspect attributes. Concurrency-safe — ResolveAPIKey is single-goroutine
// but slog itself may dispatch on a goroutine in future versions.
type captureSlogHandler struct {
	mu      sync.Mutex
	records []slog.Record
}

func (c *captureSlogHandler) Enabled(_ context.Context, _ slog.Level) bool { return true }
func (c *captureSlogHandler) Handle(_ context.Context, r slog.Record) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.records = append(c.records, r.Clone())
	return nil
}
func (c *captureSlogHandler) WithAttrs(_ []slog.Attr) slog.Handler { return c }
func (c *captureSlogHandler) WithGroup(_ string) slog.Handler      { return c }

// stringifyRecord renders every attribute (key + value) into a single string
// suitable for substring search. Group walks are not needed — ResolveAPIKey
// uses flat attributes.
func stringifyRecord(r slog.Record) string {
	var b strings.Builder
	b.WriteString(r.Message)
	r.Attrs(func(a slog.Attr) bool {
		b.WriteString(" ")
		b.WriteString(a.Key)
		b.WriteString("=")
		b.WriteString(a.Value.String())
		return true
	})
	return b.String()
}

func TestResolveAPIKey_AutoGenKeyNotInSlog(t *testing.T) {
	// NOT t.Parallel: this test captures os.Stdout, which is process-global.
	restore := captureStdout(t)
	defer func() { _ = restore() }() // ensure restoration even on assertion failure

	capture := &captureSlogHandler{}
	log := slog.New(capture)

	repo := &mockRuntimeConfigRepository{hasRow: false}
	resolved, err := ResolveAPIKey(context.Background(), "", repo, log)
	require.NoError(t, err)
	require.NotEmpty(t, resolved)

	stdout := restore()

	// AC5 part 1: key appears on stdout, prefixed with the marker.
	assert.Contains(t, stdout, "SEASONFILL_API_KEY="+resolved)

	// AC5 part 2: key absent from every captured slog record (message + attrs).
	capture.mu.Lock()
	defer capture.mu.Unlock()
	require.NotEmpty(t, capture.records, "log.Info must still fire (without the key)")
	for i, rec := range capture.records {
		rendered := stringifyRecord(rec)
		assert.NotContains(t, rendered, resolved,
			"slog record %d must not contain the master key: %q", i, rendered)
	}
}
