package wiring

import (
	"context"
	"fmt"
	"log/slog"

	authapp "github.com/alexmorbo/seasonfill/internal/admin/app"
	infraoidc "github.com/alexmorbo/seasonfill/internal/admin/infrastructure/oidc"
	adminpersistence "github.com/alexmorbo/seasonfill/internal/admin/persistence"
	adminrest "github.com/alexmorbo/seasonfill/internal/admin/rest"
	"github.com/alexmorbo/seasonfill/internal/config"
	"github.com/alexmorbo/seasonfill/internal/runtime"
	"github.com/alexmorbo/seasonfill/internal/shared/http/middleware"
	sharedports "github.com/alexmorbo/seasonfill/internal/shared/ports"
)

// admin.go owns the wiring for the admin bounded context: the auth
// stack (Story 333 — admin user repo, OIDC provider cache, login UC,
// IP limiters, password bootstrap seed). Audit / health / metrics
// wiring belongs here once those subsystems acquire their own Build*
// wirers (currently they live inside the HTTP server construction).

// AuthBundle holds the auth-domain collaborators wired by BuildAuth.
// All six handles are passed-through to httpserver.NewServer (AdminRepo,
// LoginLimiter, WebhookLimiter, OIDCUC, MeHandler, AuthRuntime) and to
// the reload OIDC provider subscriber (OIDCCache) constructed in
// server.go's Run flow.
//
// AdminRepo  — users CRUD (greenfield D-5 rename of admin_users CRUD),
//
//	also the UserRepository port the OIDC login use case
//	verifies against on group-ACL match.
//
// OIDCCache  — shared provider/discovery cache; the reload subscriber
//
//	invalidates it on issuer change.
//
// OIDCUC     — Authorization Code + PKCE use case, stateless beyond the
//
//	provider cache.
//
// LoginLimiter / WebhookLimiter — IP-keyed token bucket limiters with
//
//	the standard LoginLimit() / WebhookLimit() rates.
//
// MeHandler — owner of GET /api/v1/me + PATCH /me/settings +
//
//	POST /me/change-password (story 485, N-7a).
//
// AuthRuntime — shared atomic the reload subscriber publishes into.
//
//	Allocated here so BOTH the MeHandler (built here) and the
//	AuthHandler (built inside edge.NewServer via
//	WithAuthRuntimePointer) read the SAME pointer.
type AuthBundle struct {
	AdminRepo      *adminpersistence.UserRepository
	OIDCCache      *infraoidc.ProviderCache
	OIDCUC         *authapp.OIDCLoginUseCase
	LoginLimiter   *authapp.IPLimiter
	WebhookLimiter *authapp.IPLimiter
	MeHandler      *adminrest.MeHandler
	AuthRuntime    *middleware.AuthRuntimePointer
}

// BuildAuth constructs the admin user repo, the OIDC provider cache,
// the OIDC login use case, the login + webhook IP limiters, and runs
// the admin password bootstrap (first-run seed; idempotent across
// restarts).
//
// The `bus` parameter is reserved — admin bootstrap does not currently
// publish runtime events. Keeping it in the signature matches the other
// wirers (BuildRuntimeConfig) so future auth events have a take-up path.
//
// The ctx parameter is reserved for future use. The current body uses a
// background context for the Bootstrap call to mirror the pre-refactor
// behaviour in Server.New: the seed must complete even if the parent
// ctx already carries a deadline applied by an outer test harness.
// Plumbing the parent ctx here would change the cancel semantics. Same
// pattern as BuildPersistence / BuildRuntimeConfig.
func BuildAuth(
	ctx context.Context,
	persistence *PersistenceBundle,
	bootCfg *config.Bootstrap,
	bus *runtime.Bus,
	log *slog.Logger,
) (*AuthBundle, error) {
	_ = ctx
	_ = bus
	bgCtx := context.Background()

	adminRepo := adminpersistence.NewUserRepository(persistence.DB)
	oidcCache := infraoidc.NewProviderCache()
	oidcUC := authapp.NewOIDCLoginUseCase(oidcCache, adminRepo)

	// F-4b-8: bootstrap admin seeder emits auth-domain records
	// (user-row creation, password-reset bootstrap). The autoGenerated
	// return value is ignored here — Bootstrap already WARN-logged the
	// plaintext + emitted auth.bootstrap.created with the flag; surface
	// it as a separate runtime signal once the watchdog needs it.
	authLog := sharedports.DomainLogger(log, "auth")
	if _, err := authapp.Bootstrap(bgCtx, adminRepo, authapp.BootstrapConfig{
		WebUser:         bootCfg.Auth.WebUser,
		WebPassword:     bootCfg.Auth.WebPassword,
		WebPasswordHash: bootCfg.Auth.WebPasswordHash,
		WebEmail:        bootCfg.Auth.WebEmail,
	}, authLog); err != nil {
		return nil, fmt.Errorf("auth bootstrap: %w", err)
	}

	loginLimiter := authapp.NewIPLimiter(authapp.LoginLimit(), 5)
	webhookLimiter := authapp.NewIPLimiter(authapp.WebhookLimit(), 60)

	// Story 485 (N-7a): allocate the shared AuthRuntime atomic here so
	// the MeHandler (built next) and the AuthHandler (built inside
	// edge.NewServer via WithAuthRuntimePointer) read the SAME pointer.
	// Seeded with mode=forms so the dispatcher and MeHandler agree on
	// the default before the reload subscriber publishes a snapshot.
	authRuntime := &middleware.AuthRuntimePointer{}
	authRuntime.Store(&middleware.AuthRuntime{Mode: runtime.AuthModeForms})

	meUC := authapp.NewMeUseCase(adminRepo)
	meHandler := adminrest.NewMeHandler(meUC, authRuntime, authLog)

	return &AuthBundle{
		AdminRepo:      adminRepo,
		OIDCCache:      oidcCache,
		OIDCUC:         oidcUC,
		LoginLimiter:   loginLimiter,
		WebhookLimiter: webhookLimiter,
		MeHandler:      meHandler,
		AuthRuntime:    authRuntime,
	}, nil
}
