package auth

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"log/slog"

	"golang.org/x/crypto/bcrypt"

	"github.com/alexmorbo/seasonfill/application/ports"
	"github.com/alexmorbo/seasonfill/domain/admin"
	sharedErrors "github.com/alexmorbo/seasonfill/internal/shared/errors"
	sharedports "github.com/alexmorbo/seasonfill/internal/shared/ports"
)

const (
	BcryptCost           = 12
	GeneratedPasswordLen = 24
	MinPasswordLen       = 8
)

const passwordAlphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789!@#$%&*+-="

// DummyHash is a valid bcrypt-cost-12 hash kept for constant-latency
// login on user-not-found. Plaintext is unguessable and irrelevant.
// Impl note: regenerate locally if you prefer:
//
//	bcrypt.GenerateFromPassword([]byte("placeholder"), 12)
const DummyHash = "$2a$12$Eq8N9zKj2pQXwGv5tA8xKuJ2nKf7yQp3xZbV5W8sH3oL9mN1qR4Te"

type BootstrapConfig struct {
	WebUser         string
	WebPassword     string
	WebPasswordHash string
}

// Bootstrap is the first-run password seed. Idempotent across restarts.
// Order: existing row → no-op; WebPasswordHash → use as-is;
// WebPassword → bcrypt; else → auto-generate + WARN-log plaintext once.
func Bootstrap(ctx context.Context, repo ports.AdminUserRepository, cfg BootstrapConfig, logger *slog.Logger) error {
	if logger == nil {
		logger = sharedports.DomainLogger(slog.Default(), "auth")
	}
	if cfg.WebUser == "" {
		cfg.WebUser = "admin"
	}

	_, err := repo.Get(ctx)
	if err == nil {
		logger.InfoContext(ctx, "auth.bootstrap.skipped",
			slog.String("reason", "admin_users row already present"))
		return nil
	}
	if !errors.Is(err, ports.ErrNotFound) {
		return fmt.Errorf("auth.bootstrap: get admin user: %w", err)
	}
	var adminNF *sharedErrors.AdminUserNotFoundError
	if errors.As(err, &adminNF) {
		logger.InfoContext(ctx, "auth.bootstrap.first_run",
			slog.String("code", adminNF.Code()),
			slog.String("reason", "no admin row yet, seeding first-run password"))
	} else {
		logger.InfoContext(ctx, "auth.bootstrap.first_run",
			slog.String("code", "not_found"),
			slog.String("reason", "no admin row yet, seeding first-run password"))
	}

	hash := cfg.WebPasswordHash
	autoGen := false
	switch {
	case cfg.WebPasswordHash != "":
	case cfg.WebPassword != "":
		h, hashErr := bcrypt.GenerateFromPassword([]byte(cfg.WebPassword), BcryptCost)
		if hashErr != nil {
			return fmt.Errorf("auth.bootstrap: hash configured password: %w", hashErr)
		}
		hash = string(h)
	default:
		plain, genErr := GeneratePassword(GeneratedPasswordLen)
		if genErr != nil {
			return fmt.Errorf("auth.bootstrap: generate password: %w", genErr)
		}
		h, hashErr := bcrypt.GenerateFromPassword([]byte(plain), BcryptCost)
		if hashErr != nil {
			return fmt.Errorf("auth.bootstrap: hash generated password: %w", hashErr)
		}
		hash = string(h)
		autoGen = true
		logger.Warn("=== FIRST-RUN PASSWORD ===",
			slog.String("username", cfg.WebUser),
			slog.String("password", plain),
			slog.String("notice", "save this — it will not be shown again; change via Settings or `seasonfill reset-password --set <pw>`"),
		)
	}

	if err := repo.Create(ctx, admin.AdminUser{
		Username: cfg.WebUser, PasswordHash: hash, AutoGenerated: autoGen,
	}); err != nil {
		return fmt.Errorf("auth.bootstrap: create admin user: %w", err)
	}
	logger.InfoContext(ctx, "auth.bootstrap.created",
		slog.String("username", cfg.WebUser),
		slog.Bool("auto_generated", autoGen),
	)
	return nil
}

// GeneratePassword draws n runes from passwordAlphabet via crypto/rand.
func GeneratePassword(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		fb := make([]byte, n)
		if _, err2 := rand.Read(fb); err2 != nil {
			return "", fmt.Errorf("read random bytes: %w", err)
		}
		return base64.RawURLEncoding.EncodeToString(fb)[:n], nil
	}
	out := make([]byte, n)
	a := byte(len(passwordAlphabet))
	for i := 0; i < n; i++ {
		out[i] = passwordAlphabet[buf[i]%a]
	}
	return string(out), nil
}

func HashPassword(plain string) (string, error) {
	h, err := bcrypt.GenerateFromPassword([]byte(plain), BcryptCost)
	if err != nil {
		return "", fmt.Errorf("hash password: %w", err)
	}
	return string(h), nil
}

// VerifyPassword returns true iff plain matches hash. Empty plain
// always returns false.
func VerifyPassword(hash, plain string) bool {
	if plain == "" {
		return false
	}
	return bcrypt.CompareHashAndPassword([]byte(hash), []byte(plain)) == nil
}

// ConstantLatencyVerify burns bcrypt CPU even on unknown-user so the
// response time doesn't leak existence.
func ConstantLatencyVerify(realHash, plain string) bool {
	hash := realHash
	if hash == "" {
		hash = DummyHash
	}
	ok := VerifyPassword(hash, plain)
	return ok && realHash != ""
}
