import { describe, expect, it, vi, beforeEach, afterEach } from "vitest"
import { screen } from "@testing-library/react"

import { renderWithProviders } from "@/test-utils"
import { AppShell } from "./AppShell"
import { PageTitleProvider } from "./page-title-context"
import { InstanceFilterProvider } from "@/lib/instance-filter-context"
import * as auth from "@/lib/auth"

beforeEach(() => {
  vi.spyOn(auth, "useSession").mockReturnValue({
    data: { username: "admin", autoGenerated: false },
    isSuccess: true,
    isPending: false,
    isError: false,
    error: null,
  } as unknown as ReturnType<typeof auth.useSession>)

  globalThis.fetch = vi.fn().mockResolvedValue(
    new Response(
      JSON.stringify({
        instances: [
          { name: "alpha", health: "Available", mode: "auto" },
          { name: "beta", health: "UnavailableNetwork", mode: "manual" },
        ],
      }),
      { status: 200, headers: { "Content-Type": "application/json" } },
    ),
  ) as typeof fetch
})

afterEach(() => {
  vi.restoreAllMocks()
})

const ui = (
  <InstanceFilterProvider>
    <PageTitleProvider defaultTitle="Dashboard">
      <AppShell>
        <div data-testid="page-body">page body</div>
      </AppShell>
    </PageTitleProvider>
  </InstanceFilterProvider>
)

describe("<AppShell />", () => {
  it("renders three nav-group labels", async () => {
    renderWithProviders(ui)
    expect(await screen.findByText(/overview/i)).toBeInTheDocument()
    expect(await screen.findByText(/activity/i)).toBeInTheDocument()
    expect(await screen.findByText(/setup/i)).toBeInTheDocument()
  })

  it("renders the topbar h1 with the page title from context", async () => {
    renderWithProviders(ui)
    expect(
      await screen.findByRole("heading", { level: 1, name: "Dashboard" }),
    ).toBeInTheDocument()
  })

  it("renders the brand wordmark and favicon", async () => {
    renderWithProviders(ui)
    expect(await screen.findByText("seasonfill")).toBeInTheDocument()
    const img = screen.getByAltText("")
    expect(img.getAttribute("src")).toBe("/favicon.svg")
  })

  it("renders the page children inside the scroll region", async () => {
    renderWithProviders(ui)
    expect(await screen.findByTestId("page-body")).toBeInTheDocument()
  })

  it("renders the instance switcher with the first instance name", async () => {
    renderWithProviders(ui)
    expect(await screen.findByText("alpha")).toBeInTheDocument()
  })
})
