import { describe, it, expect, vi, beforeEach } from "vitest"
import { screen } from "@testing-library/react"

import { renderWithProviders } from "@/test-utils"
import { AppSidebar } from "./AppSidebar"
import { InstanceFilterCtx } from "@/lib/instance-filter-context-internal"
import * as auth from "@/lib/auth"
import * as instances from "@/lib/instances"

vi.mock("@/lib/api/webhookStatus", () => ({
  useWebhookStatusAggregate: vi.fn(),
}))
vi.mock("./InstanceSwitcher", () => ({
  InstanceSwitcher: () => <div data-testid="instance-switcher" />,
}))
import { useWebhookStatusAggregate } from "@/lib/api/webhookStatus"
const useWh = vi.mocked(useWebhookStatusAggregate)

function wrapWithFilter(node: React.ReactElement, filter: string | null) {
  return (
    <InstanceFilterCtx.Provider value={{ filter, setFilter: vi.fn() }}>
      {node}
    </InstanceFilterCtx.Provider>
  )
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const ok = <T,>(d: T) => ({ data: d, isPending: false, isError: false } as any)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const pending = () => ({ data: undefined, isPending: true, isError: false } as any)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const err = () => ({ data: undefined, isPending: false, isError: true } as any)

beforeEach(() => {
  useWh.mockReset()
  vi.spyOn(auth, "useSession").mockReturnValue({
    data: { username: "admin", autoGenerated: false },
    isSuccess: true,
    isPending: false,
    isError: false,
    error: null,
  } as unknown as ReturnType<typeof auth.useSession>)
  vi.spyOn(instances, "useInstances").mockReturnValue({
    data: { instances: [{ name: "homelab", mode: "auto", health: "available" }] },
    isPending: false,
    isError: false,
  } as unknown as ReturnType<typeof instances.useInstances>)
})

describe("<AppSidebar /> webhook count", () => {
  it("renders ok badge with total when all healthy", () => {
    useWh.mockReturnValue(
      ok({
        items: [
          { instance_name: "a", installed: true, healthy: true },
          { instance_name: "b", installed: true, healthy: true },
        ],
        healthy_count: 2,
        unhealthy_count: 0,
      }),
    )
    renderWithProviders(wrapWithFilter(<AppSidebar />, null))
    const badge = screen.getByTestId("sidebar-webhook-ok")
    expect(badge).toBeInTheDocument()
    expect(badge.textContent).toMatch(/2/)
    expect(screen.queryByTestId("sidebar-webhook-warn")).toBeNull()
  })

  it("renders warn badge with M/N when some unhealthy", () => {
    useWh.mockReturnValue(
      ok({
        items: [
          { instance_name: "a", installed: true, healthy: true },
          { instance_name: "b", installed: true, healthy: false, error: "503" },
          { instance_name: "c", installed: true, healthy: false, error: "x" },
        ],
        healthy_count: 1,
        unhealthy_count: 2,
      }),
    )
    renderWithProviders(wrapWithFilter(<AppSidebar />, null))
    const badge = screen.getByTestId("sidebar-webhook-warn")
    expect(badge).toBeInTheDocument()
    expect(badge.textContent).toMatch(/2/)
    expect(badge.textContent).toMatch(/3/)
    expect(screen.queryByTestId("sidebar-webhook-ok")).toBeNull()
  })

  it("renders nothing when there are no items", () => {
    useWh.mockReturnValue(ok({ items: [], healthy_count: 0, unhealthy_count: 0 }))
    renderWithProviders(wrapWithFilter(<AppSidebar />, null))
    expect(screen.queryByTestId("sidebar-webhook-ok")).toBeNull()
    expect(screen.queryByTestId("sidebar-webhook-warn")).toBeNull()
  })

  it("renders nothing while pending", () => {
    useWh.mockReturnValue(pending())
    renderWithProviders(wrapWithFilter(<AppSidebar />, null))
    expect(screen.queryByTestId("sidebar-webhook-ok")).toBeNull()
    expect(screen.queryByTestId("sidebar-webhook-warn")).toBeNull()
  })

  it("renders nothing on error (no placeholder leftover)", () => {
    useWh.mockReturnValue(err())
    renderWithProviders(wrapWithFilter(<AppSidebar />, null))
    expect(screen.queryByTestId("sidebar-webhook-ok")).toBeNull()
    expect(screen.queryByTestId("sidebar-webhook-warn")).toBeNull()
    expect(screen.queryByText(/—/)).toBeNull()
  })
})

describe("<AppSidebar /> queue nav entry", () => {
  beforeEach(() => {
    useWh.mockReturnValue(ok({ items: [], healthy_count: 0, unhealthy_count: 0 }))
  })

  it("renders a Queue link pointing at the active instance", () => {
    renderWithProviders(wrapWithFilter(<AppSidebar />, "homelab"))
    const link = screen.getByRole("link", { name: /queue/i })
    expect(link).toHaveAttribute("href", "/instances/homelab/queue")
  })

  it("falls back to the first instance when no filter is set", () => {
    renderWithProviders(wrapWithFilter(<AppSidebar />, null))
    const link = screen.getByRole("link", { name: /queue/i })
    expect(link).toHaveAttribute("href", "/instances/homelab/queue")
  })

  it("falls back to /instances when no instances exist at all", () => {
    vi.spyOn(instances, "useInstances").mockReturnValue({
      data: { instances: [] },
      isPending: false,
      isError: false,
    } as unknown as ReturnType<typeof instances.useInstances>)
    renderWithProviders(wrapWithFilter(<AppSidebar />, null))
    const link = screen.getByRole("link", { name: /queue/i })
    expect(link).toHaveAttribute("href", "/instances")
  })
})
