package persistence

import (
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	admin "github.com/alexmorbo/seasonfill/internal/admin/domain"
	ports "github.com/alexmorbo/seasonfill/internal/shared/dataports"
	sharedErrors "github.com/alexmorbo/seasonfill/internal/shared/errors"
	"github.com/alexmorbo/seasonfill/internal/shared/testhelpers"
)

func TestAdminUserRepo_GetEmpty(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			repo := NewAdminUserRepository(backend.NewDB(t))
			_, err := repo.Get(t.Context())
			require.True(t, errors.Is(err, ports.ErrNotFound))

			var typed *sharedErrors.AdminUserNotFoundError
			require.True(t, errors.As(err, &typed),
				"Get on empty table must expose typed AdminUserNotFoundError via errors.As")
		})
	}
}

func TestAdminUserRepo_CreateThenGet(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			repo := NewAdminUserRepository(backend.NewDB(t))
			want := admin.AdminUser{Username: "admin", PasswordHash: "$2a$10$abc", AutoGenerated: true}
			require.NoError(t, repo.Create(t.Context(), want))
			got, err := repo.Get(t.Context())
			require.NoError(t, err)
			assert.Equal(t, want.Username, got.Username)
			assert.Equal(t, want.PasswordHash, got.PasswordHash)
			assert.True(t, got.AutoGenerated)
			assert.NotZero(t, got.CreatedAt)
		})
	}
}

func TestAdminUserRepo_UpdatePassword(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			repo := NewAdminUserRepository(backend.NewDB(t))
			require.NoError(t, repo.Create(t.Context(), admin.AdminUser{
				Username: "admin", PasswordHash: "old", AutoGenerated: true,
			}))
			require.NoError(t, repo.UpdatePassword(t.Context(), "new", false))
			got, err := repo.Get(t.Context())
			require.NoError(t, err)
			assert.Equal(t, "new", got.PasswordHash)
			assert.False(t, got.AutoGenerated)
		})
	}
}

func TestAdminUserRepo_UpdatePassword_NoRow(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			repo := NewAdminUserRepository(backend.NewDB(t))
			err := repo.UpdatePassword(t.Context(), "hash", false)
			require.True(t, errors.Is(err, ports.ErrNotFound))

			var typed *sharedErrors.AdminUserNotFoundError
			require.True(t, errors.As(err, &typed),
				"UpdatePassword on empty table must expose typed AdminUserNotFoundError via errors.As")
		})
	}
}

// --- OIDC repository tests ---

func TestAdminUserRepo_GetByOIDCSubject_Found(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			repo := NewAdminUserRepository(backend.NewDB(t))
			got, err := repo.CreateFromOIDC(t.Context(), "sub|abc123", "alice")
			require.NoError(t, err)
			require.NotZero(t, got.ID)

			found, err := repo.GetByOIDCSubject(t.Context(), "sub|abc123")
			require.NoError(t, err)
			assert.Equal(t, "alice", found.Username)
			assert.Equal(t, "sub|abc123", *found.OIDCSubject)
			assert.Empty(t, found.PasswordHash, "OIDC user must have no password hash")
			assert.False(t, found.AutoGenerated)
		})
	}
}

func TestAdminUserRepo_GetByOIDCSubject_NotFound(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			repo := NewAdminUserRepository(backend.NewDB(t))
			_, err := repo.GetByOIDCSubject(t.Context(), "nonexistent|subject")
			require.True(t, errors.Is(err, ports.ErrNotFound))

			var typed *sharedErrors.AdminUserNotFoundError
			require.True(t, errors.As(err, &typed),
				"GetByOIDCSubject NotFound must expose typed AdminUserNotFoundError via errors.As")
		})
	}
}

func TestAdminUserRepo_CreateFromOIDC_PopulatesSubject(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			repo := NewAdminUserRepository(backend.NewDB(t))
			got, err := repo.CreateFromOIDC(t.Context(), "sub|xyz", "bob")
			require.NoError(t, err)
			require.NotNil(t, got.OIDCSubject)
			assert.Equal(t, "sub|xyz", *got.OIDCSubject)
			assert.Equal(t, "bob", got.Username)
			assert.Empty(t, got.PasswordHash)
			assert.False(t, got.AutoGenerated)
			assert.NotZero(t, got.CreatedAt)
		})
	}
}

func TestAdminUserRepo_CreateFromOIDC_MultipleUsers(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			repo := NewAdminUserRepository(backend.NewDB(t))
			u1, err := repo.CreateFromOIDC(t.Context(), "sub|1", "user1")
			require.NoError(t, err)
			u2, err := repo.CreateFromOIDC(t.Context(), "sub|2", "user2")
			require.NoError(t, err)

			assert.NotEqual(t, u1.ID, u2.ID)
			assert.Equal(t, "sub|1", *u1.OIDCSubject)
			assert.Equal(t, "sub|2", *u2.OIDCSubject)

			// GetByOIDCSubject resolves each one independently.
			r1, err := repo.GetByOIDCSubject(t.Context(), "sub|1")
			require.NoError(t, err)
			assert.Equal(t, "user1", r1.Username)

			r2, err := repo.GetByOIDCSubject(t.Context(), "sub|2")
			require.NoError(t, err)
			assert.Equal(t, "user2", r2.Username)
		})
	}
}
