package handlers

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/time/rate"

	"github.com/alexmorbo/seasonfill/application/auth"
	"github.com/alexmorbo/seasonfill/application/ports"
	"github.com/alexmorbo/seasonfill/domain/admin"
	"github.com/alexmorbo/seasonfill/interface/http/middleware"
)

type fakeAdminRepoV2 struct {
	mu   sync.Mutex
	user *admin.AdminUser
	err  error
}

func (r *fakeAdminRepoV2) Get(_ context.Context) (admin.AdminUser, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.err != nil {
		return admin.AdminUser{}, r.err
	}
	if r.user == nil {
		return admin.AdminUser{}, ports.ErrNotFound
	}
	return *r.user, nil
}
func (r *fakeAdminRepoV2) Create(_ context.Context, u admin.AdminUser) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.user = &u
	return nil
}
func (r *fakeAdminRepoV2) UpdatePassword(_ context.Context, hash string, ag bool) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.user == nil {
		return ports.ErrNotFound
	}
	r.user.PasswordHash = hash
	r.user.AutoGenerated = ag
	return nil
}

var v2HandlerOnce sync.Once

func setupV2Handler(t *testing.T, repo ports.AdminUserRepository, lim *auth.IPLimiter) (*gin.Engine, *AuthHandlerV2) {
	t.Helper()
	v2HandlerOnce.Do(func() { gin.SetMode(gin.TestMode) })
	r := gin.New()
	h := NewAuthHandlerV2("apikey-xyz", repo, time.Hour, false, lim, slog.Default())
	r.POST("/api/v1/auth/login", h.Login)
	g := r.Group("")
	g.Use(middleware.RequireAuthV2("apikey-xyz"))
	g.DELETE("/api/v1/auth/session", h.Logout)
	g.GET("/api/v1/auth/session", h.Session)
	g.POST("/api/v1/auth/password", h.PasswordChange)
	return r, h
}

func seedV2(t *testing.T) *fakeAdminRepoV2 {
	t.Helper()
	hash, err := auth.HashPassword("hunter22")
	require.NoError(t, err)
	return &fakeAdminRepoV2{user: &admin.AdminUser{
		Username: "admin", PasswordHash: hash, AutoGenerated: false,
	}}
}

func postJSONV2(t *testing.T, r *gin.Engine, path string, body any, c *http.Cookie) *httptest.ResponseRecorder {
	t.Helper()
	raw, _ := json.Marshal(body)
	req := httptest.NewRequestWithContext(t.Context(), http.MethodPost, path, bytes.NewReader(raw))
	req.Header.Set("Content-Type", "application/json")
	if c != nil {
		req.AddCookie(c)
	}
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	return w
}

func TestV2Login_Success(t *testing.T) {
	t.Parallel()
	r, _ := setupV2Handler(t, seedV2(t), nil)
	w := postJSONV2(t, r, "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "hunter22"}, nil)
	require.Equal(t, http.StatusOK, w.Code, "body=%s", w.Body.String())
	var found *http.Cookie
	for _, c := range w.Result().Cookies() {
		if c.Name == middleware.NewSessionCookieName {
			found = c
		}
	}
	require.NotNil(t, found)
	assert.True(t, found.HttpOnly)
	assert.Equal(t, http.SameSiteStrictMode, found.SameSite)
}

func TestV2Login_WrongPassword(t *testing.T) {
	t.Parallel()
	r, _ := setupV2Handler(t, seedV2(t), nil)
	w := postJSONV2(t, r, "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "wrong"}, nil)
	assert.Equal(t, http.StatusUnauthorized, w.Code)
	assert.Contains(t, w.Body.String(), "Invalid credentials")
}

func TestV2Login_UnknownUser_GenericError(t *testing.T) {
	t.Parallel()
	r, _ := setupV2Handler(t, &fakeAdminRepoV2{}, nil)
	w := postJSONV2(t, r, "/api/v1/auth/login",
		map[string]string{"username": "ghost", "password": "x"}, nil)
	assert.Equal(t, http.StatusUnauthorized, w.Code)
	assert.Contains(t, w.Body.String(), "Invalid credentials")
}

func TestV2Login_RateLimit(t *testing.T) {
	t.Parallel()
	lim := auth.NewIPLimiter(rate.Every(time.Hour), 2)
	r, _ := setupV2Handler(t, seedV2(t), lim)
	for i := 0; i < 2; i++ {
		w := postJSONV2(t, r, "/api/v1/auth/login",
			map[string]string{"username": "admin", "password": "wrong"}, nil)
		assert.Equal(t, http.StatusUnauthorized, w.Code, "attempt %d", i+1)
	}
	w := postJSONV2(t, r, "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "hunter22"}, nil)
	assert.Equal(t, http.StatusTooManyRequests, w.Code)
}

func TestV2Login_MalformedBody(t *testing.T) {
	t.Parallel()
	r, _ := setupV2Handler(t, seedV2(t), nil)
	req := httptest.NewRequestWithContext(t.Context(), http.MethodPost,
		"/api/v1/auth/login", strings.NewReader("not json"))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	assert.Equal(t, http.StatusBadRequest, w.Code)
}

func TestV2Login_RepoError_500(t *testing.T) {
	t.Parallel()
	r, _ := setupV2Handler(t, &fakeAdminRepoV2{err: errors.New("db down")}, nil)
	w := postJSONV2(t, r, "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "x"}, nil)
	assert.Equal(t, http.StatusInternalServerError, w.Code)
}

func TestV2PasswordChange_Success(t *testing.T) {
	t.Parallel()
	repo := seedV2(t)
	r, h := setupV2Handler(t, repo, nil)
	tok, _ := middleware.SignSession([]byte(h.apiKey), "admin", time.Now().Add(time.Hour))
	w := postJSONV2(t, r, "/api/v1/auth/password",
		map[string]string{"current": "hunter22", "new": "newpassword123"},
		&http.Cookie{Name: middleware.NewSessionCookieName, Value: tok})
	require.Equal(t, http.StatusNoContent, w.Code, "body=%s", w.Body.String())
	assert.True(t, auth.VerifyPassword(repo.user.PasswordHash, "newpassword123"))
	assert.False(t, repo.user.AutoGenerated)
}

func TestV2PasswordChange_WrongCurrent(t *testing.T) {
	t.Parallel()
	repo := seedV2(t)
	r, h := setupV2Handler(t, repo, nil)
	tok, _ := middleware.SignSession([]byte(h.apiKey), "admin", time.Now().Add(time.Hour))
	w := postJSONV2(t, r, "/api/v1/auth/password",
		map[string]string{"current": "wrong", "new": "longenoughpw"},
		&http.Cookie{Name: middleware.NewSessionCookieName, Value: tok})
	assert.Equal(t, http.StatusUnauthorized, w.Code)
}

func TestV2PasswordChange_WeakNew(t *testing.T) {
	t.Parallel()
	repo := seedV2(t)
	r, h := setupV2Handler(t, repo, nil)
	tok, _ := middleware.SignSession([]byte(h.apiKey), "admin", time.Now().Add(time.Hour))
	w := postJSONV2(t, r, "/api/v1/auth/password",
		map[string]string{"current": "hunter22", "new": "short"},
		&http.Cookie{Name: middleware.NewSessionCookieName, Value: tok})
	assert.Equal(t, http.StatusBadRequest, w.Code)
}

func TestV2Session_ReturnsAutoGenerated(t *testing.T) {
	t.Parallel()
	repo := seedV2(t)
	repo.user.AutoGenerated = true
	r, h := setupV2Handler(t, repo, nil)
	tok, _ := middleware.SignSession([]byte(h.apiKey), "admin", time.Now().Add(time.Hour))
	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet,
		"/api/v1/auth/session", nil)
	req.AddCookie(&http.Cookie{Name: middleware.NewSessionCookieName, Value: tok})
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	require.Equal(t, http.StatusOK, w.Code)
	var resp map[string]any
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &resp))
	assert.Equal(t, true, resp["auto_generated"])
	assert.Equal(t, "admin", resp["username"])
}
