package handlers

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/time/rate"

	"github.com/alexmorbo/seasonfill/application/auth"
	"github.com/alexmorbo/seasonfill/application/ports"
	"github.com/alexmorbo/seasonfill/domain/admin"
	"github.com/alexmorbo/seasonfill/interface/http/middleware"
	"github.com/alexmorbo/seasonfill/internal/runtime/crypto"
)

type fakeAdminRepo struct {
	mu   sync.Mutex
	user *admin.AdminUser
	err  error
}

func (r *fakeAdminRepo) Get(_ context.Context) (admin.AdminUser, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.err != nil {
		return admin.AdminUser{}, r.err
	}
	if r.user == nil {
		return admin.AdminUser{}, ports.ErrNotFound
	}
	return *r.user, nil
}
func (r *fakeAdminRepo) Create(_ context.Context, u admin.AdminUser) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.user = &u
	return nil
}
func (r *fakeAdminRepo) UpdatePassword(_ context.Context, hash string, ag bool) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.user == nil {
		return ports.ErrNotFound
	}
	r.user.PasswordHash = hash
	r.user.AutoGenerated = ag
	return nil
}

func setupAuth(t *testing.T, repo ports.AdminUserRepository, lim *auth.IPLimiter) (*gin.Engine, *AuthHandler) {
	return setupAuthWithOpts(t, repo, lim)
}

func setupAuthWithOpts(t *testing.T, repo ports.AdminUserRepository, lim *auth.IPLimiter, opts ...AuthOption) (*gin.Engine, *AuthHandler) {
	t.Helper()
	const testAPIKey = "apikey-xyz"
	sessionKey, err := crypto.DeriveSessionHMACKey(testAPIKey)
	require.NoError(t, err)
	r := gin.New()
	h := NewAuthHandler(testAPIKey, repo, time.Hour, false, lim, slog.Default(), opts...)
	r.POST("/api/v1/auth/login", h.Login)
	g := r.Group("")
	g.Use(middleware.RequireAuth(testAPIKey, sessionKey))
	g.DELETE("/api/v1/auth/session", h.Logout)
	g.GET("/api/v1/auth/session", h.Session)
	g.POST("/api/v1/auth/password", h.PasswordChange)
	return r, h
}

func seedRepo(t *testing.T) *fakeAdminRepo {
	t.Helper()
	hash, err := auth.HashPassword("hunter22")
	require.NoError(t, err)
	return &fakeAdminRepo{user: &admin.AdminUser{
		Username: "admin", PasswordHash: hash, AutoGenerated: false,
	}}
}

func postJSON(t *testing.T, r *gin.Engine, path string, body any, c *http.Cookie) *httptest.ResponseRecorder {
	t.Helper()
	raw, _ := json.Marshal(body)
	req := httptest.NewRequestWithContext(t.Context(), http.MethodPost, path, bytes.NewReader(raw))
	req.Header.Set("Content-Type", "application/json")
	if c != nil {
		req.AddCookie(c)
	}
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	return w
}

func TestAuthLogin_Success(t *testing.T) {
	t.Parallel()
	r, _ := setupAuth(t, seedRepo(t), nil)
	w := postJSON(t, r, "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "hunter22"}, nil)
	require.Equal(t, http.StatusOK, w.Code, "body=%s", w.Body.String())
	var found *http.Cookie
	for _, c := range w.Result().Cookies() {
		if c.Name == middleware.SessionCookieName {
			found = c
		}
	}
	require.NotNil(t, found)
	assert.True(t, found.HttpOnly)
	assert.Equal(t, http.SameSiteStrictMode, found.SameSite)
}

func TestAuthLogin_WrongPassword(t *testing.T) {
	t.Parallel()
	r, _ := setupAuth(t, seedRepo(t), nil)
	w := postJSON(t, r, "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "wrong"}, nil)
	assert.Equal(t, http.StatusUnauthorized, w.Code)
	assert.Contains(t, w.Body.String(), "Invalid credentials")
}

func TestAuthLogin_UnknownUser_GenericError(t *testing.T) {
	t.Parallel()
	r, _ := setupAuth(t, &fakeAdminRepo{}, nil)
	w := postJSON(t, r, "/api/v1/auth/login",
		map[string]string{"username": "ghost", "password": "x"}, nil)
	assert.Equal(t, http.StatusUnauthorized, w.Code)
	assert.Contains(t, w.Body.String(), "Invalid credentials")
}

func TestAuthLogin_RateLimit(t *testing.T) {
	t.Parallel()
	lim := auth.NewIPLimiter(rate.Every(time.Hour), 2)
	r, _ := setupAuth(t, seedRepo(t), lim)
	for i := 0; i < 2; i++ {
		w := postJSON(t, r, "/api/v1/auth/login",
			map[string]string{"username": "admin", "password": "wrong"}, nil)
		assert.Equal(t, http.StatusUnauthorized, w.Code, "attempt %d", i+1)
	}
	w := postJSON(t, r, "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "hunter22"}, nil)
	assert.Equal(t, http.StatusTooManyRequests, w.Code)
}

func TestAuthLogin_MalformedBody(t *testing.T) {
	t.Parallel()
	r, _ := setupAuth(t, seedRepo(t), nil)
	req := httptest.NewRequestWithContext(t.Context(), http.MethodPost,
		"/api/v1/auth/login", strings.NewReader("not json"))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	assert.Equal(t, http.StatusBadRequest, w.Code)
}

func TestAuthLogin_RepoError_500(t *testing.T) {
	t.Parallel()
	r, _ := setupAuth(t, &fakeAdminRepo{err: errors.New("db down")}, nil)
	w := postJSON(t, r, "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "x"}, nil)
	assert.Equal(t, http.StatusInternalServerError, w.Code)
}

func TestAuthPasswordChange_Success(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t)
	r, h := setupAuth(t, repo, nil)
	tok, _ := middleware.SignSession(h.sessionKey, "admin", time.Now().Add(time.Hour), 0)
	w := postJSON(t, r, "/api/v1/auth/password",
		map[string]string{"current": "hunter22", "new": "newpassword123"},
		&http.Cookie{Name: middleware.SessionCookieName, Value: tok})
	require.Equal(t, http.StatusNoContent, w.Code, "body=%s", w.Body.String())
	assert.True(t, auth.VerifyPassword(repo.user.PasswordHash, "newpassword123"))
	assert.False(t, repo.user.AutoGenerated)
}

func TestAuthPasswordChange_WrongCurrent(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t)
	r, h := setupAuth(t, repo, nil)
	tok, _ := middleware.SignSession(h.sessionKey, "admin", time.Now().Add(time.Hour), 0)
	w := postJSON(t, r, "/api/v1/auth/password",
		map[string]string{"current": "wrong", "new": "longenoughpw"},
		&http.Cookie{Name: middleware.SessionCookieName, Value: tok})
	assert.Equal(t, http.StatusUnauthorized, w.Code)
}

func TestAuthPasswordChange_WeakNew(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t)
	r, h := setupAuth(t, repo, nil)
	tok, _ := middleware.SignSession(h.sessionKey, "admin", time.Now().Add(time.Hour), 0)
	w := postJSON(t, r, "/api/v1/auth/password",
		map[string]string{"current": "hunter22", "new": "short"},
		&http.Cookie{Name: middleware.SessionCookieName, Value: tok})
	assert.Equal(t, http.StatusBadRequest, w.Code)
}

func TestAuthSession_ReturnsAutoGenerated(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t)
	repo.user.AutoGenerated = true
	r, h := setupAuth(t, repo, nil)
	tok, _ := middleware.SignSession(h.sessionKey, "admin", time.Now().Add(time.Hour), 0)
	req := httptest.NewRequestWithContext(t.Context(), http.MethodGet,
		"/api/v1/auth/session", nil)
	req.AddCookie(&http.Cookie{Name: middleware.SessionCookieName, Value: tok})
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	require.Equal(t, http.StatusOK, w.Code)
	var resp map[string]any
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &resp))
	assert.Equal(t, true, resp["auto_generated"])
	assert.Equal(t, "admin", resp["username"])
}

// TestAuthPasswordChange_SameAsCurrent covers M4: a request whose new
// password equals the current one is a no-op and returns 400. The
// envelope mirrors other 4xx with the BAD_REQUEST code.
func TestAuthPasswordChange_SameAsCurrent(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t)
	r, h := setupAuth(t, repo, nil)
	tok, _ := middleware.SignSession(h.sessionKey, "admin", time.Now().Add(time.Hour), 0)
	w := postJSON(t, r, "/api/v1/auth/password",
		map[string]string{"current": "hunter22", "new": "hunter22"},
		&http.Cookie{Name: middleware.SessionCookieName, Value: tok})
	require.Equal(t, http.StatusBadRequest, w.Code)
	assert.Contains(t, w.Body.String(), "must differ")
	assert.Contains(t, w.Body.String(), "BAD_REQUEST")
}

// TestAuthPasswordChange_RateLimit covers M1: after burst exhaustion
// the endpoint MUST return 429 without touching bcrypt or the repo.
func TestAuthPasswordChange_RateLimit(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t)
	// Burst 2, refill once per hour — guaranteed exhaustion mid-test.
	pwLim := auth.NewIPLimiter(rate.Every(time.Hour), 2)
	r, h := setupAuthWithOpts(t, repo, nil, WithPasswordLimiter(pwLim))
	tok, _ := middleware.SignSession(h.sessionKey, "admin", time.Now().Add(time.Hour), 0)
	cookie := &http.Cookie{Name: middleware.SessionCookieName, Value: tok}
	// Two wrong-current attempts consume the burst.
	for i := 0; i < 2; i++ {
		w := postJSON(t, r, "/api/v1/auth/password",
			map[string]string{"current": "wrong", "new": "newpassword123"}, cookie)
		assert.Equal(t, http.StatusUnauthorized, w.Code, "attempt %d", i+1)
	}
	// Third — even with correct credentials — is throttled.
	w := postJSON(t, r, "/api/v1/auth/password",
		map[string]string{"current": "hunter22", "new": "newpassword123"}, cookie)
	require.Equal(t, http.StatusTooManyRequests, w.Code, "body=%s", w.Body.String())
	assert.Contains(t, w.Body.String(), "RATE_LIMITED")
}

// TestLogin_SecureCookieAtomicLive — flipping AuthRuntime.SecureCookie via
// the shared atomic (the reload subscriber's only side effect) must take
// effect on the very next Login without rebuilding the handler.
func TestLogin_SecureCookieAtomicLive(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t)
	r, h := setupAuth(t, repo, nil)
	// Boot atomic = SecureCookie:false (setupAuth passes false).
	w := postJSON(t, r, "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "hunter22"}, nil)
	require.Equal(t, http.StatusOK, w.Code, "body=%s", w.Body.String())
	var cookie *http.Cookie
	for _, c := range w.Result().Cookies() {
		if c.Name == middleware.SessionCookieName {
			cookie = c
		}
	}
	require.NotNil(t, cookie)
	assert.False(t, cookie.Secure, "boot=false → Secure must be false on plain HTTP")

	// Flip via the atomic (simulates AuthMiddlewareSubscriber.apply).
	h.authRuntime.Store(&middleware.AuthRuntime{
		SessionTTL:   time.Hour,
		SecureCookie: true,
	})
	w = postJSON(t, r, "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "hunter22"}, nil)
	require.Equal(t, http.StatusOK, w.Code)
	cookie = nil
	for _, c := range w.Result().Cookies() {
		if c.Name == middleware.SessionCookieName {
			cookie = c
		}
	}
	require.NotNil(t, cookie)
	assert.True(t, cookie.Secure, "after atomic flip → next Login must set Secure")
}

// E-4: Logout

// TestLogout_ClearsCookie asserts that DELETE /api/v1/auth/session responds
// 204 and sets the session cookie to Max-Age=-1 (clearing it).
func TestLogout_ClearsCookie(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t)
	r, h := setupAuth(t, repo, nil)

	// First obtain a valid session cookie via Login.
	w := postJSON(t, r, "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "hunter22"}, nil)
	require.Equal(t, http.StatusOK, w.Code, "login must succeed: %s", w.Body.String())
	var sessionCookie *http.Cookie
	for _, c := range w.Result().Cookies() {
		if c.Name == middleware.SessionCookieName {
			sessionCookie = c
		}
	}
	require.NotNil(t, sessionCookie, "login response must set session cookie")

	// Build a signed token via the handler's session key (same key the
	// middleware uses for validation) and call Logout with it.
	tok, err := middleware.SignSession(h.sessionKey, "admin", time.Now().Add(time.Hour), 0)
	require.NoError(t, err)
	req := httptest.NewRequestWithContext(t.Context(), http.MethodDelete,
		"/api/v1/auth/session", nil)
	req.AddCookie(&http.Cookie{Name: middleware.SessionCookieName, Value: tok})
	wLogout := httptest.NewRecorder()
	r.ServeHTTP(wLogout, req)
	require.Equal(t, http.StatusNoContent, wLogout.Code, "body=%s", wLogout.Body.String())

	// The response must contain a Set-Cookie header that clears the cookie
	// (MaxAge < 0, indicated by the raw header containing "max-age=-1").
	var clearedCookie *http.Cookie
	for _, c := range wLogout.Result().Cookies() {
		if c.Name == middleware.SessionCookieName {
			clearedCookie = c
		}
	}
	require.NotNil(t, clearedCookie, "Logout must emit Set-Cookie for session cookie")
	assert.True(t, clearedCookie.MaxAge < 0,
		"Logout must set Max-Age < 0 to clear the cookie, got %d", clearedCookie.MaxAge)
}

// TestLogout_Unauthenticated asserts that DELETE /api/v1/auth/session without
// a valid session still responds 204 — Logout is idempotent.
func TestLogout_Unauthenticated(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t)
	r, _ := setupAuth(t, repo, nil)

	req := httptest.NewRequestWithContext(t.Context(), http.MethodDelete,
		"/api/v1/auth/session", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	// Middleware returns 401 for unauthenticated requests on protected routes.
	assert.Equal(t, http.StatusUnauthorized, w.Code)
}

// TestLogin_TLSAlwaysSecure — a TLS-marked request (or X-Forwarded-Proto:
// https) MUST get Secure even when SecureCookie=false. Defense in depth:
// never downgrade.
func TestLogin_TLSAlwaysSecure(t *testing.T) {
	t.Parallel()
	repo := seedRepo(t)
	r, _ := setupAuth(t, repo, nil)
	raw, _ := json.Marshal(map[string]string{"username": "admin", "password": "hunter22"})
	req := httptest.NewRequestWithContext(t.Context(), http.MethodPost,
		"/api/v1/auth/login", bytes.NewReader(raw))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Forwarded-Proto", "https")
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	require.Equal(t, http.StatusOK, w.Code, "body=%s", w.Body.String())
	var cookie *http.Cookie
	for _, c := range w.Result().Cookies() {
		if c.Name == middleware.SessionCookieName {
			cookie = c
		}
	}
	require.NotNil(t, cookie)
	assert.True(t, cookie.Secure, "X-Forwarded-Proto=https must force Secure regardless of flag")
}

// TestAuthRuntime_ReturnsPointer covers the AuthRuntime() accessor, which
// wires the shared atomic between cmd/server and reload subscribers.
func TestAuthRuntime_ReturnsPointer(t *testing.T) {
	t.Parallel()
	_, h := setupAuth(t, seedRepo(t), nil)
	ptr := h.AuthRuntime()
	require.NotNil(t, ptr)
	rt := ptr.Load()
	require.NotNil(t, rt)
	assert.Equal(t, time.Hour, rt.SessionTTL)
}

// TestWithClock_SetsCustomClock verifies the WithClock option wires a
// caller-supplied clock function into the handler.
func TestWithClock_SetsCustomClock(t *testing.T) {
	t.Parallel()
	fixed := time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)
	_, h := setupAuthWithOpts(t, seedRepo(t), nil, WithClock(func() time.Time { return fixed }))
	assert.Equal(t, fixed, h.now())
}

// TestWithAuthRuntimePointer_WiresSharedAtomic verifies that a shared
// AuthRuntimePointer installed via the option is the one the handler uses.
func TestWithAuthRuntimePointer_WiresSharedAtomic(t *testing.T) {
	t.Parallel()
	shared := &middleware.AuthRuntimePointer{}
	shared.Store(&middleware.AuthRuntime{SessionTTL: 3 * time.Hour})
	_, h := setupAuthWithOpts(t, seedRepo(t), nil, WithAuthRuntimePointer(shared))
	assert.Equal(t, 3*time.Hour, h.sessionTTL())
}
