package handlers

import (
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"net/http"
	"strings"
	"time"

	"github.com/gin-gonic/gin"

	"github.com/alexmorbo/seasonfill/application/auth"
	"github.com/alexmorbo/seasonfill/application/ports"
	"github.com/alexmorbo/seasonfill/interface/http/dto"
	"github.com/alexmorbo/seasonfill/interface/http/middleware"
)

const (
	v2LoginBodyLimit = 4 << 10
	v2JSONPrefix     = "application/json"
)

// AuthHandlerV2 — D48 handler. 021a-2 renames to AuthHandler and
// removes the old auth.go file.
type AuthHandlerV2 struct {
	apiKey       string
	repo         ports.AdminUserRepository
	sessionTTL   time.Duration
	secureCookie bool
	limiter      *auth.IPLimiter
	logger       *slog.Logger
	now          func() time.Time
}

type AuthV2Option func(*AuthHandlerV2)

func WithClockV2(now func() time.Time) AuthV2Option {
	return func(h *AuthHandlerV2) {
		if now != nil {
			h.now = now
		}
	}
}

// NewAuthHandlerV2 — panics on empty apiKey or nil repo.
func NewAuthHandlerV2(
	apiKey string, repo ports.AdminUserRepository, sessionTTL time.Duration,
	secureCookie bool, limiter *auth.IPLimiter, logger *slog.Logger, opts ...AuthV2Option,
) *AuthHandlerV2 {
	if apiKey == "" {
		panic("handlers.NewAuthHandlerV2: apiKey must not be empty")
	}
	if repo == nil {
		panic("handlers.NewAuthHandlerV2: repo must not be nil")
	}
	if sessionTTL <= 0 {
		sessionTTL = 12 * time.Hour
	}
	if logger == nil {
		logger = slog.Default()
	}
	h := &AuthHandlerV2{
		apiKey: apiKey, repo: repo, sessionTTL: sessionTTL,
		secureCookie: secureCookie, limiter: limiter, logger: logger, now: time.Now,
	}
	for _, opt := range opts {
		opt(h)
	}
	return h
}

func (h *AuthHandlerV2) Login(c *gin.Context) {
	ip := c.ClientIP()
	if h.limiter != nil && !h.limiter.Allow(ip) {
		h.logger.WarnContext(c.Request.Context(), "auth.login.rate_limited",
			slog.String("ip", ip))
		c.AbortWithStatusJSON(http.StatusTooManyRequests, gin.H{
			"error": "Invalid credentials", "code": "UNAUTHORIZED",
		})
		return
	}

	username, password, ok := h.readLoginBody(c)
	if !ok {
		return
	}

	user, err := h.repo.Get(c.Request.Context())
	if err != nil && !errors.Is(err, ports.ErrNotFound) {
		h.logger.ErrorContext(c.Request.Context(), "auth.login.repo_failed",
			slog.String("error", err.Error()))
		c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": "internal server error"})
		return
	}

	usernameMatches := err == nil && user.Username == username
	hashToCompare := user.PasswordHash
	if !usernameMatches {
		hashToCompare = ""
	}
	if !auth.ConstantLatencyVerify(hashToCompare, password) {
		h.logger.WarnContext(c.Request.Context(), "auth.login.failed",
			slog.String("ip", ip))
		c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{
			"error": "Invalid credentials", "code": "UNAUTHORIZED",
		})
		return
	}

	exp := h.now().Add(h.sessionTTL)
	tok, err := middleware.SignSession([]byte(h.apiKey), user.Username, exp)
	if err != nil {
		h.logger.ErrorContext(c.Request.Context(), "auth.login.sign_failed",
			slog.String("error", err.Error()))
		c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": "internal server error"})
		return
	}

	c.SetSameSite(http.SameSiteStrictMode)
	c.SetCookie(middleware.NewSessionCookieName, tok,
		int(h.sessionTTL.Seconds()), "/", "",
		h.secureCookie || v2RequestIsTLS(c.Request), true)
	h.logger.InfoContext(c.Request.Context(), "auth.login.success",
		slog.String("username", user.Username))
	c.JSON(http.StatusOK, gin.H{
		"ok": true, "username": user.Username, "auto_generated": user.AutoGenerated,
	})
}

func (h *AuthHandlerV2) readLoginBody(c *gin.Context) (string, string, bool) {
	ct := c.GetHeader("Content-Type")
	if !strings.HasPrefix(ct, v2JSONPrefix) {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{
			"error": "content-type must be application/json",
		})
		return "", "", false
	}
	c.Request.Body = http.MaxBytesReader(c.Writer, c.Request.Body, v2LoginBodyLimit)
	raw, err := io.ReadAll(c.Request.Body)
	if err != nil {
		var maxErr *http.MaxBytesError
		if errors.As(err, &maxErr) {
			c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": "payload too large"})
			return "", "", false
		}
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": "cannot read body"})
		return "", "", false
	}
	var body dto.LoginRequest
	if err := json.Unmarshal(raw, &body); err != nil {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": "malformed body"})
		return "", "", false
	}
	return body.Username, body.Password, true
}

func (h *AuthHandlerV2) Logout(c *gin.Context) {
	c.SetSameSite(http.SameSiteStrictMode)
	c.SetCookie(middleware.NewSessionCookieName, "", -1, "/", "",
		h.secureCookie || v2RequestIsTLS(c.Request), true)
	h.logger.InfoContext(c.Request.Context(), "auth.logout.success")
	c.Status(http.StatusNoContent)
}

func (h *AuthHandlerV2) Session(c *gin.Context) {
	username := c.GetString(middleware.UsernameContextKey)
	autoGen := false
	if username != "" && username != "api-key" {
		if u, err := h.repo.Get(c.Request.Context()); err == nil {
			autoGen = u.AutoGenerated
		}
	}
	c.JSON(http.StatusOK, dto.SessionResponse{
		OK: true, Username: username, AutoGenerated: autoGen,
	})
}

func (h *AuthHandlerV2) PasswordChange(c *gin.Context) {
	ct := c.GetHeader("Content-Type")
	if !strings.HasPrefix(ct, v2JSONPrefix) {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{
			"error": "content-type must be application/json",
		})
		return
	}
	c.Request.Body = http.MaxBytesReader(c.Writer, c.Request.Body, v2LoginBodyLimit)
	raw, err := io.ReadAll(c.Request.Body)
	if err != nil {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": "cannot read body"})
		return
	}
	var body dto.PasswordChangeRequest
	if err := json.Unmarshal(raw, &body); err != nil {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": "malformed body"})
		return
	}
	if len(body.New) < auth.MinPasswordLen {
		c.AbortWithStatusJSON(http.StatusBadRequest, gin.H{
			"error": "password too short (min 8 chars)",
		})
		return
	}
	user, err := h.repo.Get(c.Request.Context())
	if err != nil {
		c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"error": "Invalid credentials"})
		return
	}
	if !auth.VerifyPassword(user.PasswordHash, body.Current) {
		c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"error": "Invalid credentials"})
		return
	}
	newHash, err := auth.HashPassword(body.New)
	if err != nil {
		c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": "internal server error"})
		return
	}
	if err := h.repo.UpdatePassword(c.Request.Context(), newHash, false); err != nil {
		c.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": "internal server error"})
		return
	}
	h.logger.InfoContext(c.Request.Context(), "auth.password_change.success",
		slog.String("username", user.Username))
	c.Status(http.StatusNoContent)
}

func v2RequestIsTLS(r *http.Request) bool {
	if r.TLS != nil {
		return true
	}
	return strings.EqualFold(r.Header.Get("X-Forwarded-Proto"), "https")
}
