package admin

import "time"

// AdminUser is the single-user admin record (Phase 7 ships single-user).
// AutoGenerated stays true while the password is still the first-run
// generated value; flips to false on explicit password set. OIDCSubject
// is non-nil only for admin rows created via OIDC first-login; for the
// Forms admin it stays nil (password-based auth path).
type AdminUser struct {
	ID            uint
	Username      string
	PasswordHash  string
	AutoGenerated bool
	OIDCSubject   *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
