// Package dto defines the JSON shapes the seasonfill HTTP layer
// emits and consumes. Types are framework-free apart from swag
// struct-tag annotations consumed by the spec generator.
package dto

import "time"

// OKResponse — canonical success envelope.
type OKResponse struct {
	OK bool `json:"ok" example:"true"`
}

// ErrorResponse — canonical 4xx/5xx envelope. Code is populated only
// for the auth 401; other handlers emit `{"error":msg}`. dto_test.go
// asserts byte parity with middleware/auth.go.
type ErrorResponse struct {
	Error string `json:"error" example:"unauthorized"`
	Code  string `json:"code,omitempty" example:"UNAUTHORIZED"`
}

// ScanConflictResponse — POST /scan 409 envelope. The `instance` key
// is preserved on the wire so clients can identify the busy target;
// dedicated DTO so the generated TS sees the field.
type ScanConflictResponse struct {
	Error    string `json:"error"    example:"scan already running"`
	Instance string `json:"instance" example:"alpha"`
	Code     string `json:"code"     example:"SCAN_IN_PROGRESS"`
}

// ScanNotFoundResponse — POST /scan 404 envelope (unknown instance).
// No Code field — historical wire shape is just error+instance.
type ScanNotFoundResponse struct {
	Error    string `json:"error"    example:"unknown instance"`
	Instance string `json:"instance" example:"alpha"`
}

// LoginRequest — JSON body for POST /auth/login (D48).
type LoginRequest struct {
	Username string `json:"username" example:"admin"`
	Password string `json:"password" example:"hunter2"`
}

// PasswordChangeRequest — JSON body for POST /auth/password.
type PasswordChangeRequest struct {
	Current string `json:"current" example:"hunter22"`
	New     string `json:"new"     example:"NewSecretLongEnough"`
}

// SessionResponse — body of GET /auth/session.
type SessionResponse struct {
	OK            bool   `json:"ok"             example:"true"`
	Username      string `json:"username"       example:"admin"`
	AutoGenerated bool   `json:"auto_generated" example:"false"`
}

// ScanTriggerRequest — optional body for POST /scan.
// SeriesIDs narrows the scan to specific IDs; empty = all. Unknown
// IDs are skipped with a WARN (Q-010-3); response stays 202.
// DryRun is an optional override of the instance/global dry_run
// setting. nil = use instance default; *true = force dry run;
// *false = force real grab regardless of instance config.
type ScanTriggerRequest struct {
	Instance  string `json:"instance,omitempty"   example:"alpha"`
	SeriesIDs []int  `json:"series_ids,omitempty"`
	DryRun    *bool  `json:"dry_run,omitempty"`
}

// ScanTriggerItem — one row in the 202 array response of POST /scan.
type ScanTriggerItem struct {
	ScanRunID    string    `json:"scan_run_id" example:"7b3d4a92-1234-4abc-9def-000000000001"`
	InstanceName string    `json:"instance"    example:"alpha"`
	Status       string    `json:"status"      example:"completed" enums:"completed,failed,running,aborted,cancelled"`
	Series       int       `json:"series_scanned"`
	Candidates   int       `json:"candidates_found"`
	Errors       int       `json:"errors"`
	Started      time.Time `json:"started_at"`
	Finished     time.Time `json:"finished_at"`
}

// Instance — Sonarr-instance health snapshot. Mode always emitted
// (Q-010-1) so the UI doesn't branch on field absence. URL is the
// configured Sonarr base URL — read-only echo from the runtime
// snapshot, populated by the handler from the static URLs map (see
// known limitation note in 028g).
type Instance struct {
	Name             string     `json:"name"   example:"alpha"`
	URL              string     `json:"url"    example:"http://sonarr:8989"`
	Mode             string     `json:"mode"   example:"auto" enums:"auto,manual"`
	Health           string     `json:"health" example:"Available" enums:"Available,UnavailableAuth,UnavailableNetwork,UnavailableUnknown"`
	LastCheckAt      *time.Time `json:"last_check_at,omitempty"`
	LastError        string     `json:"last_error,omitempty"`
	TransitionsCount int        `json:"transitions_count"`
}

// InstanceList — body of GET /instances.
type InstanceList struct {
	Instances []Instance `json:"instances"`
}

// Scan — one ScanRun row.
type Scan struct {
	ID              string     `json:"id"               example:"7b3d4a92-1234-4abc-9def-000000000001"`
	Instance        string     `json:"instance"         example:"alpha"`
	Trigger         string     `json:"trigger"          example:"cron" enums:"cron,manual,webhook"`
	CreatedAt       time.Time  `json:"created_at"`
	StartedAt       time.Time  `json:"started_at"`
	FinishedAt      *time.Time `json:"finished_at,omitempty"`
	Status          string     `json:"status"           example:"completed" enums:"running,completed,failed,aborted,cancelled"`
	SeriesScanned   int        `json:"series_scanned"`
	CandidatesFound int        `json:"candidates_found"`
	GrabsPerformed  int        `json:"grabs_performed"`
	GrabsFailed     int        `json:"grabs_failed"`
	ErrorsCount     int        `json:"errors_count"`
	ErrorMessage    string     `json:"error_message,omitempty"`
	DryRun          bool       `json:"dry_run"`
}

// Decision — one decisions row.
type Decision struct {
	ID              string    `json:"id"               example:"dec_001"`
	ScanRunID       string    `json:"scan_run_id"`
	Instance        string    `json:"instance"         example:"alpha"`
	SeriesID        int       `json:"series_id"`
	SeriesTitle     string    `json:"series_title"     example:"Severance"`
	SeasonNumber    int       `json:"season_number"`
	Decision        string    `json:"decision"         example:"grab" enums:"grab,skip,blocked_cooldown,already_optimal,expired,error"`
	Reason          string    `json:"reason"           example:"upgrade_available"`
	Category        string    `json:"category"         example:"action_taken" enums:"all_complete,sonarr_handles,action_taken,blocked,nothing_found,error,unknown"`
	MissingCount    int       `json:"missing_count"`
	ExistingCount   int       `json:"existing_count"`
	ReleasesFound   int       `json:"releases_found"`
	CandidatesCount int       `json:"candidates_count"`
	SelectedGUID    string    `json:"selected_guid,omitempty"`
	DryRunWouldGrab bool      `json:"dry_run_would_grab"`
	ErrorDetail     string    `json:"error_detail,omitempty" example:"sonarr: 503 service unavailable"`
	SupersededByID  string    `json:"superseded_by_id,omitempty" example:"7b3d4a92-1234-4abc-9def-000000000005"`
	CreatedAt       time.Time `json:"created_at"`
}

// Grab — one grab_records row.
type Grab struct {
	ID                string    `json:"id"                  example:"grb_001"`
	Instance          string    `json:"instance"            example:"alpha"`
	SeriesID          int       `json:"series_id"`
	SeriesTitle       string    `json:"series_title"        example:"Severance"`
	SeasonNumber      int       `json:"season_number"`
	ReleaseGUID       string    `json:"release_guid"`
	ReleaseTitle      string    `json:"release_title"`
	IndexerID         int       `json:"indexer_id"`
	IndexerName       string    `json:"indexer_name"        example:"tracker.x"`
	CustomFormatScore int       `json:"custom_format_score"`
	Quality           string    `json:"quality"             example:"WEBDL-1080p"`
	CoverageCount     int       `json:"coverage_count"`
	Status            string    `json:"status"              example:"imported" enums:"grabbed,imported,import_failed,grab_failed,expired"`
	ErrorMessage      string    `json:"error_message,omitempty"`
	ScanRunID         string    `json:"scan_run_id"`
	Attempts          int       `json:"attempts"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	// TorrentHash — qBit info-hash (40-char lowercase hex) captured
	// by the OnGrab webhook (Phase 10) or stamped at force-grab time.
	// Omitted from wire when nil so pre-Phase-10 rows stay clean.
	TorrentHash *string `json:"torrent_hash,omitempty" example:"0123456789abcdef0123456789abcdef01234567"`
	// ReplayOfID — uuid of the original row this row re-grabs.
	// Populated by the Watchdog regrab path (039f-2); nil for scan /
	// rescan / manual paths. Omitted when nil.
	ReplayOfID *string `json:"replay_of_id,omitempty" example:"7b3d4a92-1234-4abc-9def-000000000003"`
	// ReplayedBy — uuids of newer grab_records rows that re-grab THIS
	// row (reverse of replay_of_id). Derived at read time by the
	// audit handler — a single batched SELECT covers the page. Capped
	// at ports.MaxReplaysPerParent (50); SPA renders "+N more" past
	// that. Empty slice omitted from wire.
	ReplayedBy []string `json:"replayed_by,omitempty"`
	// SizeBytes — release size in bytes (Sonarr OnGrab `release.size`
	// or manual-grab `releaseDTO.size`). Omitted when nil; SPA
	// renders "—" for missing values.
	SizeBytes *int64 `json:"size_bytes,omitempty" example:"13325829734"`
}

// ScanList — keyset-paginated GET /scans response.
type ScanList struct {
	Items      []Scan `json:"items"`
	NextCursor string `json:"next_cursor,omitempty"`
}

// DecisionList — keyset-paginated GET /decisions response.
type DecisionList struct {
	Items      []Decision `json:"items"`
	NextCursor string     `json:"next_cursor,omitempty"`
}

// GrabList — keyset-paginated GET /grabs response.
type GrabList struct {
	Items      []Grab `json:"items"`
	NextCursor string `json:"next_cursor,omitempty"`
}

// HealthStatus — body of GET /healthz.
type HealthStatus struct {
	Status string `json:"status" example:"ok"`
}

// ReadyStatus — body of GET /readyz (200 or 503). Reports ONLY
// pod-local dependencies (currently: DB). External Sonarr instance
// health is operational status, not readiness — it is surfaced via
// GET /api/v1/instances and the seasonfill_instance_health Prometheus
// gauge. Keeping the readiness probe decoupled from upstream Sonarr
// ensures a misconfigured instance can't kick the pod out of the K8s
// Service and lock the operator out of the Settings UI.
type ReadyStatus struct {
	Status   string `json:"status"   example:"ok" enums:"ok,unavailable"`
	Database bool   `json:"database" example:"true"`
}

// MissingSeasonStat — per-season aired-missing count. Season 0 = specials.
type MissingSeasonStat struct {
	SeasonNumber      int `json:"season_number"`
	MissingAiredCount int `json:"missing_aired_count"`
}

// MissingSeries — one row of GET /instances/:name/missing.
// TotalMissingAired is precomputed sum of Seasons[].MissingAiredCount.
// TitleSlug / Year / PosterPath are joined from series_cache (041g).
// TitleSlug is a plain string with empty fallback (NOT pointer) so the
// frontend renders the link the moment it is non-empty without nil
// checks. Year / PosterPath are *T with omitempty so cache misses don't
// bloat the wire payload.
type MissingSeries struct {
	SeriesID          int                 `json:"series_id"             example:"122"`
	Title             string              `json:"title"                 example:"Severance"`
	Monitored         bool                `json:"monitored"             example:"true"`
	TotalMissingAired int                 `json:"total_missing_aired"`
	Seasons           []MissingSeasonStat `json:"seasons"`
	TitleSlug         string              `json:"title_slug"            example:"severance"`
	Year              *int                `json:"year,omitempty"        example:"2022"`
	PosterPath        *string             `json:"poster_path,omitempty" example:"/MediaCover/122/poster.jpg"`
}

// MissingSeriesList — body of GET /instances/:name/missing.
type MissingSeriesList struct {
	Items []MissingSeries `json:"items"`
	Total int             `json:"total"`
}

// SeriesSearchItem — one row of GET /instances/:name/series. Trimmed
// to picker-specific fields (Q-013a-3) so 013b's Combobox doesn't have
// to ignore noise. SeasonCount is monitored-season count; MissingAired
// is derived from series-level statistics (same source as Missing).
type SeriesSearchItem struct {
	SeriesID     int    `json:"series_id"            example:"122"`
	Title        string `json:"title"                example:"Severance"`
	Monitored    bool   `json:"monitored"            example:"true"`
	SeasonCount  int    `json:"season_count"         example:"2"`
	MissingAired int    `json:"missing_aired_count"  example:"8"`
}

// SeriesSearchList — body of GET /instances/:name/series. `Total` is
// the count BEFORE `limit` is applied so 013b can render
// "showing N of M". `Items` is empty-array-never-null (matches
// ScanList behaviour for TS codegen).
type SeriesSearchList struct {
	Items []SeriesSearchItem `json:"items"`
	Total int                `json:"total" example:"142"`
}

// InstanceDetail — full per-instance shape returned by
// GET /api/v1/instances/:name. APIKey is always the literal "***"
// mask (027b round-2). NEVER carries the encrypted ciphertext or the
// decrypted plaintext. `UpdatedAt` is the source for the
// Last-Modified header (handler-side, not part of body — but kept on
// the DTO so the SPA can render "last edited" without a HEAD).
type InstanceDetail struct {
	Name             string              `json:"name"             example:"alpha"`
	URL              string              `json:"url"              example:"http://sonarr:8989"`
	APIKey           string              `json:"api_key"          example:"***"`
	Mode             string              `json:"mode"             example:"auto"  enums:"auto,manual"`
	TimeoutSec       int                 `json:"timeout_sec"`
	SearchTimeoutSec int                 `json:"search_timeout_sec"`
	DryRun           *bool               `json:"dry_run,omitempty"`
	Tags             InstanceTags        `json:"tags"`
	Search           InstanceSearch      `json:"search"`
	Ranking          InstanceRanking     `json:"ranking"`
	Limits           InstanceLimits      `json:"limits"`
	RateLimitRPM     int                 `json:"rate_limit_rpm"`
	RateLimitBurst   int                 `json:"rate_limit_burst"`
	Cooldown         InstanceCooldown    `json:"cooldown"`
	Retry            InstanceRetry       `json:"retry"`
	HealthCheck      InstanceHealthCheck `json:"health_check"`
	// PublicURL is the optional browser-facing URL (D64). Always
	// emitted; the JSON value is `null` when no override is stored.
	PublicURL *string `json:"public_url" example:"https://sonarr.example.com"`
	// WebhookInstallEnabled toggles the 041c reconciler (D65). Always
	// emitted as a concrete bool; defaults to true on fresh rows.
	WebhookInstallEnabled bool `json:"webhook_install_enabled" example:"true"`
	// WebhookURLOverride is the optional base URL for the auto-installed
	// Sonarr webhook (D65). Always emitted; `null` when unset.
	WebhookURLOverride *string `json:"webhook_url_override" example:"https://seasonfill.example.com"`
	// UIURL is the derived browser-facing URL the SPA links to. Equals
	// PublicURL when set, otherwise URL. Always emitted as a non-empty
	// string so the SPA never has to compute the fallback itself.
	UIURL     string    `json:"ui_url" example:"https://sonarr.example.com"`
	UpdatedAt time.Time `json:"updated_at"`
}

type InstanceTags struct {
	Mode    string   `json:"mode"    example:"include" enums:"include,exclude,off"`
	Include []string `json:"include"`
	Exclude []string `json:"exclude"`
}

type InstanceSearch struct {
	RequireAllAired      bool `json:"require_all_aired"`
	SkipSpecials         bool `json:"skip_specials"`
	SkipAnime            bool `json:"skip_anime"`
	MinCustomFormatScore int  `json:"min_custom_format_score"`
}

type InstanceRanking struct {
	IndexerPriorityEnabled bool    `json:"indexer_priority_enabled"`
	OriginBonus            float64 `json:"origin_bonus"`
}

type InstanceLimits struct {
	ScanMaxSeries   int `json:"scan_max_series"`
	MaxGrabsPerScan int `json:"max_grabs_per_scan"`
}

type InstanceCooldown struct {
	Mode                     string `json:"mode" enums:"smart,strict"`
	SeriesAfterGrabSec       int    `json:"series_after_grab_sec"`
	GUIDAfterFailedGrabSec   int    `json:"guid_after_failed_grab_sec"`
	GUIDAfterFailedImportSec int    `json:"guid_after_failed_import_sec"`
}

type InstanceRetry struct {
	MaxAttempts       int `json:"max_attempts"`
	InitialBackoffSec int `json:"initial_backoff_sec"`
	MaxBackoffSec     int `json:"max_backoff_sec"`
}

type InstanceHealthCheck struct {
	RecheckAuthSec    int `json:"recheck_auth_sec"`
	RecheckNetworkSec int `json:"recheck_network_sec"`
}

// InstanceCreateRequest — body of POST /api/v1/instances. `api_key`
// is required on create; everything else has server-side defaults
// applied via runtime.ApplyInstanceDefaults.
type InstanceCreateRequest struct {
	Name             string              `json:"name"             example:"alpha"`
	URL              string              `json:"url"              example:"http://sonarr:8989"`
	APIKey           string              `json:"api_key"          example:"abcd..."`
	Mode             string              `json:"mode,omitempty"   example:"auto"`
	TimeoutSec       int                 `json:"timeout_sec,omitempty"`
	SearchTimeoutSec int                 `json:"search_timeout_sec,omitempty"`
	DryRun           *bool               `json:"dry_run,omitempty"`
	Tags             InstanceTags        `json:"tags"`
	Search           InstanceSearch      `json:"search"`
	Ranking          InstanceRanking     `json:"ranking"`
	Limits           InstanceLimits      `json:"limits"`
	RateLimitRPM     int                 `json:"rate_limit_rpm"`
	RateLimitBurst   int                 `json:"rate_limit_burst"`
	Cooldown         InstanceCooldown    `json:"cooldown"`
	Retry            InstanceRetry       `json:"retry"`
	HealthCheck      InstanceHealthCheck `json:"health_check"`
	// PublicURL — optional browser-facing URL. Omitted/null = no
	// override. Empty string is rejected at the application layer with
	// INVALID_INSTANCE_PUBLIC_URL so a client cannot accidentally
	// downgrade the override into a silent no-op.
	PublicURL *string `json:"public_url,omitempty" example:"https://sonarr.example.com"`
	// WebhookInstallEnabled — pointer so omitted is distinguishable
	// from explicit `false`. Omitted/null defaults to true (matches the
	// migration default). Concrete false explicitly disables the 041c
	// reconciler.
	WebhookInstallEnabled *bool `json:"webhook_install_enabled,omitempty" example:"true"`
	// WebhookURLOverride — optional base URL for the auto-installed
	// Sonarr webhook. Omitted/null = use derived public URL from
	// runtime config. Empty-string rejected as for PublicURL.
	WebhookURLOverride *string `json:"webhook_url_override,omitempty" example:"https://seasonfill.example.com"`
}

// InstanceUpdateRequest — body of PUT /api/v1/instances/:name.
// `api_key` is optional ("" = preserve stored secret).
type InstanceUpdateRequest = InstanceCreateRequest

type InstanceTestRequest struct {
	URL    string `json:"url"     example:"http://sonarr:8989"`
	APIKey string `json:"api_key" example:"abcd..."`
}

type InstanceTestResponse struct {
	OK      bool   `json:"ok"`
	Version string `json:"version,omitempty"`
	Reason  string `json:"reason,omitempty"`
}

// RuntimeConfigDTO is the wire shape of GET/PUT /api/v1/config/runtime.
// Mirrors runtime.Snapshot minus Instances; bootstrap-only env-driven
// fields (WebUser, WebPassword*, APIKey, database, http.bind,
// log.level) are deliberately excluded. Durations are Go-style strings
// (e.g. "30s", "12h"). AutoGeneratedAPIKey is read-only on GET — any
// value the client sends on PUT is ignored.
type RuntimeConfigDTO struct {
	Cron                RuntimeCronDTO      `json:"cron"`
	Scan                RuntimeScanDTO      `json:"scan"`
	DryRun              bool                `json:"dry_run"`
	GlobalRateLimit     RuntimeRateLimitDTO `json:"global_rate_limit"`
	Auth                RuntimeAuthDTO      `json:"auth"`
	AutoGeneratedAPIKey bool                `json:"auto_generated_api_key" example:"false"`
	UpdatedAt           time.Time           `json:"updated_at"`
}

type RuntimeCronDTO struct {
	Enabled  bool   `json:"enabled"`
	Schedule string `json:"schedule" example:"0 */6 * * *"`
	OnStart  bool   `json:"on_start"`
	Jitter   string `json:"jitter"   example:"1m"`
}

type RuntimeScanDTO struct {
	ShutdownGrace string `json:"shutdown_grace" example:"60s"`
	CooldownSweep string `json:"cooldown_sweep" example:"15m"`
}

type RuntimeRateLimitDTO struct {
	RPM   int `json:"rpm"   example:"30"`
	Burst int `json:"burst" example:"10"`
}

type RuntimeAuthDTO struct {
	SessionTTL     string   `json:"session_ttl"     example:"12h"`
	SecureCookie   bool     `json:"secure_cookie"`
	TrustedProxies []string `json:"trusted_proxies" example:"127.0.0.1,::1"`
	// Mode is one of "forms" | "basic" | "none" | "oidc". Default "forms".
	Mode string `json:"mode" example:"forms"`
	// LocalBypass enables the local-address bypass middleware (036c).
	LocalBypass bool `json:"local_bypass"`
	// LocalNetworks is the CIDR allow-list driving local-bypass.
	LocalNetworks []string `json:"local_networks" example:"127.0.0.0/8,10.0.0.0/8"`
	// SessionEpoch is read-only — the server bumps it whenever any
	// auth-invalidating field changes. PUT bodies that include it are
	// silently ignored (the usecase manages the value).
	SessionEpoch int64          `json:"session_epoch" example:"0"`
	OIDC         RuntimeOIDCDTO `json:"oidc"`
}

type RuntimeOIDCDTO struct {
	Issuer        string   `json:"issuer"          example:"https://keycloak.example.com/realms/homelab"`
	ClientID      string   `json:"client_id"       example:"seasonfill"`
	RedirectURL   string   `json:"redirect_url"    example:"https://seasonfill.example.com/api/v1/auth/oidc/callback"`
	Scopes        []string `json:"scopes"          example:"openid,profile,email"`
	UsernameClaim string   `json:"username_claim"  example:"preferred_username"`
	AllowedGroups []string `json:"allowed_groups"  example:"admins"`
	GroupsClaim   string   `json:"groups_claim"    example:"groups"`
	// ClientSecret is write-only: GET responses NEVER contain a value.
	ClientSecret            *string `json:"client_secret,omitempty"`
	ClientSecretConfigured  bool    `json:"client_secret_configured"`
	ClientSecretEnvOverride bool    `json:"client_secret_env_override"`
}

// AuthConfigDTO is the wire shape of GET /api/v1/auth/config. Public
// endpoint — no secrets, no auth required. Used by the SPA bootstrap
// path to decide whether to render Login / Logout / banners.
type AuthConfigDTO struct {
	Mode        string `json:"mode" example:"forms"`
	LocalBypass bool   `json:"local_bypass" example:"false"`
	// OIDCReady mirrors middleware.OIDCRuntime.IsReady(). When true,
	// LoginURL is also populated — SPA renders SSO button regardless of mode.
	OIDCReady bool   `json:"oidc_ready" example:"false"`
	LoginURL  string `json:"login_url,omitempty" example:"/api/v1/auth/oidc/start"`
}

// QbitDiscoverDTO is the response shape for
// GET /api/v1/instances/{name}/discover/qbit. Password is never
// returned — Sonarr redacts it server-side.
type QbitDiscoverDTO struct {
	Name     string `json:"name"`
	URL      string `json:"url"`
	Username string `json:"username,omitempty"`
	Category string `json:"category"`
}

// WebhookInstallDTO is the response shape for
// POST /api/v1/instances/{name}/webhook/install. Created=false means
// a matching webhook already existed (no-op); Created=true means a
// new one was POSTed to Sonarr.
type WebhookInstallDTO struct {
	Installed      bool `json:"installed" example:"true"`
	Created        bool `json:"created"   example:"true"`
	NotificationID int  `json:"notification_id" example:"42"`
}

// WebhookStatusDTO is the response shape for
// GET /api/v1/instances/{name}/webhook/status. Queries Sonarr's
// /api/v3/notification list and reports whether our canonical webhook
// URL is already present. NotificationID and URL are only populated
// when Installed is true.
type WebhookStatusDTO struct {
	Installed      bool    `json:"installed"                  example:"true"`
	NotificationID *int    `json:"notification_id,omitempty"  example:"42"`
	URL            *string `json:"url,omitempty"              example:"https://sf.example.com/api/v1/webhook/sonarr/homelab"`
	// Error carries the last reconcile failure message (041c). nil on
	// success. Served on 200 so the UI can render an "install failed"
	// badge without a separate fetch.
	Error *string `json:"error,omitempty" example:"sonarr unauthorized"`
}

// EpisodeFileDetail — one on-disk file row from the 043c
// episode-files endpoint. Mirrors Sonarr's episodeFile resource +
// derived episode_numbers grouping. NOT persisted — fetched lazily
// per drawer open (PRD decision #6).
type EpisodeFileDetail struct {
	ID             int    `json:"id"             example:"7001"`
	RelativePath   string `json:"relative_path"  example:"Season 02/Severance.S02E01.mkv"`
	SeasonNumber   int    `json:"season_number"  example:"2"`
	EpisodeNumbers []int  `json:"episode_numbers" example:"1,2"`
	SizeBytes      int64  `json:"size_bytes"     example:"13325829734"`
	Quality        string `json:"quality"        example:"WEBDL-2160p"`
}

// EpisodeFileList — body of GET /api/v1/instances/:name/grabs/:id/episode-files.
type EpisodeFileList struct {
	Items []EpisodeFileDetail `json:"items"`
}

// SeriesCacheItem — one row of GET /api/v1/instances/:name/series-cache.
// Lean shape: omits overview/genres/banner/fanart so a 24-item Dashboard
// poster response stays under ~20 KB. F11 will introduce a separate
// detail endpoint if richer fields are needed per series.
//
// LastGrabAt / LastImportedEpisode are derived at read time from
// grab_records (imported status, latest created_at per series). Empty
// means "no imported grab on file".
type SeriesCacheItem struct {
	SonarrSeriesID      int        `json:"sonarr_series_id"        example:"122"`
	InstanceName        string     `json:"instance_name"           example:"homelab"`
	Title               string     `json:"title"                   example:"For All Mankind"`
	TitleSlug           string     `json:"title_slug"              example:"for-all-mankind"`
	Year                *int       `json:"year,omitempty"          example:"2019"`
	Network             *string    `json:"network,omitempty"       example:"Apple TV+"`
	Status              *string    `json:"status,omitempty"        example:"continuing" enums:"continuing,ended,upcoming"`
	PosterPath          *string    `json:"poster_path,omitempty"   example:"/MediaCover/122/poster.jpg"`
	Monitored           bool       `json:"monitored"               example:"true"`
	MissingCount        int        `json:"missing_count"           example:"0"`
	LastGrabAt          *time.Time `json:"last_grab_at,omitempty"`
	LastImportedEpisode string     `json:"last_imported_episode,omitempty" example:"S05"`
	UpdatedAt           time.Time  `json:"updated_at"`
}

// SeriesCacheList — body of GET /api/v1/instances/:name/series-cache.
// Total is the pre-limit count (renders "showing N of M" in the UI).
// HasMore signals an additional page exists; NextCursor encodes the
// keyset position for the next request.
type SeriesCacheList struct {
	Items      []SeriesCacheItem `json:"items"`
	Total      int               `json:"total"      example:"42"`
	HasMore    bool              `json:"has_more"   example:"true"`
	NextCursor string            `json:"next_cursor,omitempty"`
}
