// Package dto defines the JSON shapes the seasonfill HTTP layer
// emits and consumes. Types are framework-free apart from swag
// struct-tag annotations consumed by the spec generator.
package dto

import (
	"time"

	"github.com/alexmorbo/seasonfill/internal/shared/domain"
)

// OKResponse — canonical success envelope.
type OKResponse struct {
	OK bool `json:"ok" example:"true"`
}

// ErrorResponse — canonical 4xx/5xx envelope. Code is populated only
// for the auth 401; other handlers emit `{"error":msg}`. dto_test.go
// asserts byte parity with middleware/auth.go.
type ErrorResponse struct {
	Error string `json:"error" example:"unauthorized"`
	Code  string `json:"code,omitempty" example:"UNAUTHORIZED"`
}

// ScanConflictResponse — POST /scan 409 envelope. The `instance` key
// is preserved on the wire so clients can identify the busy target;
// dedicated DTO so the generated TS sees the field.
type ScanConflictResponse struct {
	Error    string              `json:"error"    example:"scan already running"`
	Instance domain.InstanceName `json:"instance" example:"alpha"`
	Code     string              `json:"code"     example:"SCAN_IN_PROGRESS"`
}

// ScanNotFoundResponse — POST /scan 404 envelope (unknown instance).
// No Code field — historical wire shape is just error+instance.
type ScanNotFoundResponse struct {
	Error    string              `json:"error"    example:"unknown instance"`
	Instance domain.InstanceName `json:"instance" example:"alpha"`
}

// LoginRequest — JSON body for POST /auth/login (D48).
type LoginRequest struct {
	Username string `json:"username" example:"admin"`
	Password string `json:"password" example:"hunter2"`
}

// PasswordChangeRequest — JSON body for POST /auth/password.
type PasswordChangeRequest struct {
	Current string `json:"current" example:"hunter22"`
	New     string `json:"new"     example:"NewSecretLongEnough"`
}

// SessionResponse — body of GET /auth/session.
type SessionResponse struct {
	OK            bool   `json:"ok"             example:"true"`
	Username      string `json:"username"       example:"admin"`
	AutoGenerated bool   `json:"auto_generated" example:"false"`
}

// ScanTriggerRequest — optional body for POST /scan.
// SeriesIDs narrows the scan to specific IDs; empty = all. Unknown
// IDs are skipped with a WARN (Q-010-3); response stays 202.
// DryRun is an optional override of the instance/global dry_run
// setting. nil = use instance default; *true = force dry run;
// *false = force real grab regardless of instance config.
type ScanTriggerRequest struct {
	Instance  domain.InstanceName     `json:"instance,omitempty"   example:"alpha"`
	SeriesIDs []domain.SonarrSeriesID `json:"series_ids,omitempty"`
	DryRun    *bool                   `json:"dry_run,omitempty"`
}

// ScanTriggerItem — one row in the 202 array response of POST /scan.
type ScanTriggerItem struct {
	ScanRunID    string              `json:"scan_run_id" example:"7b3d4a92-1234-4abc-9def-000000000001"`
	InstanceName domain.InstanceName `json:"instance"    example:"alpha"`
	Status       string              `json:"status"      example:"completed" enums:"completed,failed,running,aborted,cancelled"`
	Series       int                 `json:"series_scanned"`
	Candidates   int                 `json:"candidates_found"`
	Errors       int                 `json:"errors"`
	Started      time.Time           `json:"started_at"`
	Finished     time.Time           `json:"finished_at"`
}

// Instance — Sonarr-instance health snapshot. Mode always emitted
// (Q-010-1) so the UI doesn't branch on field absence. URL is the
// configured Sonarr base URL — read-only echo from the runtime
// snapshot, populated by the handler from the static URLs map (see
// known limitation note in 028g). PublicURL is the optional
// browser-facing URL (D64); omitempty because the list endpoint is
// high-traffic and the field is empty for most rows. SPA prefers
// PublicURL over URL when rendering "open in Sonarr".
type Instance struct {
	Name             string     `json:"name"   example:"alpha"`
	URL              string     `json:"url"    example:"http://sonarr:8989"`
	PublicURL        string     `json:"public_url,omitempty" example:"https://sonarr.example.com"`
	Mode             string     `json:"mode"   example:"auto" enums:"auto,manual"`
	Health           string     `json:"health" example:"Available" enums:"Available,SelfThrottled,UnavailableAuth,UnavailableNetwork,UnavailableUnknown"`
	LastCheckAt      *time.Time `json:"last_check_at,omitempty"`
	LastError        string     `json:"last_error,omitempty"`
	TransitionsCount int        `json:"transitions_count"`
}

// InstanceList — body of GET /instances.
type InstanceList struct {
	Instances []Instance `json:"instances"`
}

// Scan — one ScanRun row.
type Scan struct {
	ID              string              `json:"id"               example:"7b3d4a92-1234-4abc-9def-000000000001"`
	Instance        domain.InstanceName `json:"instance"         example:"alpha"`
	Trigger         string              `json:"trigger"          example:"cron" enums:"cron,manual,webhook"`
	CreatedAt       time.Time           `json:"created_at"`
	StartedAt       time.Time           `json:"started_at"`
	FinishedAt      *time.Time          `json:"finished_at,omitempty"`
	Status          string              `json:"status"           example:"completed" enums:"running,completed,failed,aborted,cancelled"`
	SeriesScanned   int                 `json:"series_scanned"`
	CandidatesFound int                 `json:"candidates_found"`
	GrabsPerformed  int                 `json:"grabs_performed"`
	GrabsFailed     int                 `json:"grabs_failed"`
	ErrorsCount     int                 `json:"errors_count"`
	ErrorMessage    string              `json:"error_message,omitempty"`
	DryRun          bool                `json:"dry_run"`
}

// Decision — one decisions row.
// Decision — one decisions row.
//
// 046a adds the season-stats snapshot: TotalEpisodes / AiredEpisodes /
// ExistingEpisodes / GrabbedEpisodes. ExistingCount is kept for
// back-compat (counts have-files at evaluation time using episode-level
// data); ExistingEpisodes is the canonical new field driven by Sonarr's
// per-season statistics block. Pre-046a rows render with all four new
// fields = 0 — the UI treats 0 as "unknown" (em-dash placeholder).
type Decision struct {
	ID               string                `json:"id"               example:"dec_001"`
	ScanRunID        string                `json:"scan_run_id"`
	Instance         domain.InstanceName   `json:"instance"         example:"alpha"`
	SeriesID         domain.SonarrSeriesID `json:"series_id"`
	SeriesTitle      string                `json:"series_title"     example:"Severance"`
	SeasonNumber     int                   `json:"season_number"`
	Decision         string                `json:"decision"         example:"grab" enums:"grab,skip,blocked_cooldown,already_optimal,expired,error"`
	Reason           string                `json:"reason"           example:"upgrade_available"`
	Category         string                `json:"category"         example:"action_taken" enums:"all_complete,sonarr_handles,action_taken,blocked,nothing_found,error,unknown"`
	MissingCount     int                   `json:"missing_count"`
	ExistingCount    int                   `json:"existing_count"`
	ReleasesFound    int                   `json:"releases_found"`
	CandidatesCount  int                   `json:"candidates_count"`
	SelectedGUID     string                `json:"selected_guid,omitempty"`
	DryRunWouldGrab  bool                  `json:"dry_run_would_grab"`
	ErrorDetail      string                `json:"error_detail,omitempty" example:"sonarr: 503 service unavailable"`
	SupersededByID   string                `json:"superseded_by_id,omitempty" example:"7b3d4a92-1234-4abc-9def-000000000005"`
	TotalEpisodes    int                   `json:"total_episodes"    example:"10"`
	AiredEpisodes    int                   `json:"aired_episodes"    example:"8"`
	ExistingEpisodes int                   `json:"existing_episodes" example:"3"`
	GrabbedEpisodes  int                   `json:"grabbed_episodes"  example:"5"`
	// Intent — the F-P2-2 "why this grab" capture (091a). nil for
	// pre-091a rows AND for any decision path that couldn't infer a
	// reason (synthetic skip rows, error rows). Frontend GrabDrawer
	// renders a localised label for chosen_because and the raw
	// chosen_reason_detail string underneath. Always present as a
	// JSON key on the wire (null vs object), per omitempty/pointer
	// semantics, so the SPA can branch on `null` directly.
	Intent    *DecisionIntent `json:"intent,omitempty"`
	CreatedAt time.Time       `json:"created_at"`
}

// DecisionIntent is the wire shape of the F-P2-2 "why this grab"
// capture. Mirrors domain/decision.Intent verbatim. Slices are
// always emitted as JSON arrays (never null) so the SPA can
// `intent.target_episodes.map(...)` without branching on null.
// chosen_because stays a free-form string on the wire so adding a
// new enum value is an additive change.
type DecisionIntent struct {
	TargetEpisodes     []int  `json:"target_episodes"             example:"10,11"`
	HadEpisodes        []int  `json:"had_episodes"                example:"1,2,3,4,5,6,7,8,9"`
	ChosenBecause      string `json:"chosen_because"              example:"highest_score" enums:"only_candidate,highest_score,first_pass_quality,watchdog_better_quality,watchdog_better_dub,watchdog_better_other,watchdog_replay_unregistered,watchdog_replay_already_added,watchdog_replay_error,manual_selection"`
	ChosenReasonDetail string `json:"chosen_reason_detail"        example:"score 88 vs alternates 64, 71"`
}

// Grab — one grab_records row.
type Grab struct {
	ID                string                `json:"id"                  example:"grb_001"`
	Instance          domain.InstanceName   `json:"instance"            example:"alpha"`
	SeriesID          domain.SonarrSeriesID `json:"series_id"`
	SeriesTitle       string                `json:"series_title"        example:"Severance"`
	SeasonNumber      int                   `json:"season_number"`
	ReleaseGUID       string                `json:"release_guid"`
	ReleaseTitle      string                `json:"release_title"`
	IndexerID         int                   `json:"indexer_id"`
	IndexerName       string                `json:"indexer_name"        example:"tracker.x"`
	CustomFormatScore int                   `json:"custom_format_score"`
	Quality           string                `json:"quality"             example:"WEBDL-1080p"`
	CoverageCount     int                   `json:"coverage_count"`
	Status            string                `json:"status"              example:"imported" enums:"grabbed,imported,import_failed,grab_failed,expired"`
	ErrorMessage      string                `json:"error_message,omitempty"`
	ScanRunID         string                `json:"scan_run_id"`
	Attempts          int                   `json:"attempts"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
	// TorrentHash — qBit info-hash (40-char lowercase hex) captured
	// by the OnGrab webhook (Phase 10) or stamped at force-grab time.
	// Omitted from wire when nil so pre-Phase-10 rows stay clean.
	TorrentHash *domain.QbitHash `json:"torrent_hash,omitempty" example:"0123456789abcdef0123456789abcdef01234567"`
	// ReplayOfID — uuid of the original row this row re-grabs.
	// Populated by the Watchdog regrab path (039f-2); nil for scan /
	// rescan / manual paths. Omitted when nil.
	ReplayOfID *string `json:"replay_of_id,omitempty" example:"7b3d4a92-1234-4abc-9def-000000000003"`
	// ReplayedBy — uuids of newer grab_records rows that re-grab THIS
	// row (reverse of replay_of_id). Derived at read time by the
	// audit handler — a single batched SELECT covers the page. Capped
	// at ports.MaxReplaysPerParent (50); SPA renders "+N more" past
	// that. Empty slice omitted from wire.
	ReplayedBy []string `json:"replayed_by,omitempty"`
	// ReplayKind classifies a replay row relative to its parent
	// (F-P2-3). Derived server-side at read time from Parsed/Quality
	// on both sides. Empty / "primary" (omitted from wire) means this
	// row is not a replay or has no comparable axis. "replay_quality"
	// = better resolution / codec / HDR than parent. "replay_dub" =
	// gained a dub track the parent did not have. "replay_other" =
	// replay row but no parsed-axis improvement detected (parent
	// off-page, parent unparsed, or no axis differs).
	ReplayKind string `json:"replay_kind,omitempty" example:"replay_quality" enums:"replay_quality,replay_dub,replay_other"`
	// SizeBytes — release size in bytes (Sonarr OnGrab `release.size`
	// or manual-grab `releaseDTO.size`). Omitted when nil; SPA
	// renders "—" for missing values.
	SizeBytes *int64 `json:"size_bytes,omitempty" example:"13325829734"`
	// Parsed carries the Sonarr /api/v3/parse projection captured by
	// the OnGrab webhook in 044b. Nullable — pre-B2 rows and rows whose
	// parse call failed both emit `null`. The SPA Grabs page chip set
	// degrades to "no parsed" on null.
	Parsed *GrabParsed `json:"parsed,omitempty"`
	// ParsedAt is the wall-clock at which Sonarr parsed the release
	// title. Always emitted alongside a non-null Parsed; omitted when
	// Parsed is null.
	ParsedAt *time.Time `json:"parsed_at,omitempty"`
	// Intent surfaces the "why this grab" payload from the Decision
	// row that produced this grab (091a / F-P2-2). The audit handler
	// resolves the Decision lazily by (scan_run_id, instance, series,
	// season) at read time and copies the Intent here so GrabDrawer
	// can render "Почему этот грабе" without a second round-trip.
	// nil when no matching Decision was found OR the Decision itself
	// carried no intent (pre-091a rows, error decisions).
	Intent *DecisionIntent `json:"intent,omitempty"`
	// TitleSlug is the authoritative Sonarr slug for this grab's
	// series, joined at read time from series_cache on
	// (instance_name, series_id). The FE deep-links into Sonarr
	// using this value when present; absence falls the SPA back to
	// its client-side slugifier (lossy for `&`, apostrophes, and
	// year disambiguation). Omitted from wire when empty — pre-116
	// rows and rows whose series_cache row is absent emit no key,
	// keeping the audit handler test snapshots untouched. Mirrors
	// the 041g pattern on dto.MissingSeries.TitleSlug.
	TitleSlug string `json:"title_slug,omitempty" example:"your-friends-and-neighbors"`
	// PosterHash is the content-addressed sha256 of the stored hero
	// poster (size w342) for this grab's series, joined at read time
	// from the same series_cache → media_assets LEFT JOIN that powers
	// the catalog list (story 348a). The FE renders posters via
	// mediaUrl(hash) when set; nil falls back to the legacy proxy or
	// a monogram placeholder. Omitted from wire when nil so audit
	// snapshots taken pre-348b stay untouched. Story 348b.
	PosterHash *string `json:"poster_hash,omitempty" example:"3a2b1c..." extensions:"x-content-addressed=true"`
}

// GrabParsed is the Sonarr-parsed release metadata block exposed on
// the Grabs list / lookup. Mirrors domain/grab.Parsed. All fields are
// optional; absent values omit. See 044a for the data contract and
// the SPA design pack §F3 for the chip rendering rules.
type GrabParsed struct {
	Codec        string   `json:"codec,omitempty"         example:"HEVC"`
	Source       string   `json:"source,omitempty"        example:"WEB-DL"`
	Quality      string   `json:"quality,omitempty"       example:"WEBDL-2160p"`
	Resolution   int      `json:"resolution,omitempty"    example:"2160"`
	HDRFlags     []string `json:"hdr_flags,omitempty"     example:"HDR10+,DV"`
	Dub          string   `json:"dub,omitempty"           example:"Original"`
	Languages    []string `json:"languages,omitempty"     example:"Russian,English"`
	Subs         []string `json:"subs,omitempty"          example:"RUS"`
	ReleaseGroup string   `json:"release_group,omitempty" example:"NTb"`
}

// ScanList — keyset-paginated GET /scans response.
type ScanList struct {
	Items      []Scan `json:"items"`
	NextCursor string `json:"next_cursor,omitempty"`
}

// DecisionList — keyset-paginated GET /decisions response.
type DecisionList struct {
	Items      []Decision `json:"items"`
	NextCursor string     `json:"next_cursor,omitempty"`
}

// GrabList — keyset-paginated GET /grabs response.
type GrabList struct {
	Items      []Grab `json:"items"`
	NextCursor string `json:"next_cursor,omitempty"`
}

// HealthStatus — body of GET /healthz.
type HealthStatus struct {
	Status string `json:"status" example:"ok"`
}

// ReadyStatus — body of GET /readyz (200 or 503). Reports ONLY
// pod-local dependencies (currently: DB). External Sonarr instance
// health is operational status, not readiness — it is surfaced via
// GET /api/v1/instances and the seasonfill_instance_health Prometheus
// gauge. Keeping the readiness probe decoupled from upstream Sonarr
// ensures a misconfigured instance can't kick the pod out of the K8s
// Service and lock the operator out of the Settings UI.
type ReadyStatus struct {
	Status   string `json:"status"   example:"ok" enums:"ok,unavailable"`
	Database bool   `json:"database" example:"true"`
}

// MissingSeasonStat — per-season aired-missing count. Season 0 = specials.
//
// `episodes` is optional (omitempty) — historically the Missing handler
// embedded per-episode presence inline for small seasons (054c), but
// that fan-out cost N×ListEpisodes Sonarr calls per /missing request
// and saturated the 60s gateway timeout on real backlogs. The list
// handler no longer populates `episodes`; episode-level state lives on
// the drill endpoint /instances/:name/series/:id/seasons/:n/episodes
// (SeasonEpisodes handler). The field stays on the DTO for backward
// wire-shape compatibility — older clients that read `episodes` simply
// see it omitted and fall back to the season aggregate chip.
type MissingSeasonStat struct {
	SeasonNumber      int                     `json:"season_number"`
	MissingAiredCount int                     `json:"missing_aired_count"`
	AiredEpisodeCount int                     `json:"aired_episode_count,omitempty"`
	Episodes          []SeasonEpisodePresence `json:"episodes,omitempty"`
}

// SeasonEpisodePresence — one episode's on-disk state with title.
// Trimmed shape for the queue list: only what the chip-grid needs.
// `present` mirrors Sonarr's `hasFile`. Quality is not surfaced here —
// the operator opens the drill for per-quality detail.
type SeasonEpisodePresence struct {
	Number  int    `json:"number"        example:"5"`
	Title   string `json:"title"         example:"The Jerrick Trick"`
	Present bool   `json:"present"       example:"true"`
}

// MissingSeries — one row of GET /instances/:name/missing.
// TotalMissingAired is precomputed sum of Seasons[].MissingAiredCount.
// TitleSlug / Year / PosterHash are joined from series_cache (041g).
// TitleSlug is a plain string with empty fallback (NOT pointer) so the
// frontend renders the link the moment it is non-empty without nil
// checks. Year is *T with omitempty so cache misses don't bloat the
// wire payload.
//
// PosterHash carries the content-addressed sha256 of the stored hero
// poster (Story 348b). The FE consumes it with mediaUrl() to call
// /api/v1/media/<hash>. Story 350 dropped the legacy poster_path field.
type MissingSeries struct {
	SeriesID          domain.SonarrSeriesID `json:"series_id"             example:"122"`
	Title             string                `json:"title"                 example:"Severance"`
	Monitored         bool                  `json:"monitored"             example:"true"`
	TotalMissingAired int                   `json:"total_missing_aired"`
	Seasons           []MissingSeasonStat   `json:"seasons"`
	TitleSlug         string                `json:"title_slug"            example:"severance"`
	Year              *int                  `json:"year,omitempty"        example:"2022"`
	PosterHash        *string               `json:"poster_hash,omitempty" example:"3a2b1c..." extensions:"x-content-addressed=true"`
}

// MissingSeriesList — body of GET /instances/:name/missing.
type MissingSeriesList struct {
	Items []MissingSeries `json:"items"`
	Total int             `json:"total"`
}

// SeriesSearchItem — one row of GET /instances/:name/series. Trimmed
// to picker-specific fields (Q-013a-3) so 013b's Combobox doesn't have
// to ignore noise. SeasonCount is monitored-season count; MissingAired
// is derived from series-level statistics (same source as Missing).
type SeriesSearchItem struct {
	SeriesID     domain.SonarrSeriesID `json:"series_id"            example:"122"`
	Title        string                `json:"title"                example:"Severance"`
	Monitored    bool                  `json:"monitored"            example:"true"`
	SeasonCount  int                   `json:"season_count"         example:"2"`
	MissingAired int                   `json:"missing_aired_count"  example:"8"`
}

// SeriesSearchList — body of GET /instances/:name/series. `Total` is
// the count BEFORE `limit` is applied so 013b can render
// "showing N of M". `Items` is empty-array-never-null (matches
// ScanList behaviour for TS codegen).
type SeriesSearchList struct {
	Items []SeriesSearchItem `json:"items"`
	Total int                `json:"total" example:"142"`
}

// InstanceDetail — full per-instance shape returned by
// GET /api/v1/instances/:name. APIKey is always the literal "***"
// mask (027b round-2). NEVER carries the encrypted ciphertext or the
// decrypted plaintext. `UpdatedAt` is the source for the
// Last-Modified header (handler-side, not part of body — but kept on
// the DTO so the SPA can render "last edited" without a HEAD).
type InstanceDetail struct {
	Name             string              `json:"name"             example:"alpha"`
	URL              string              `json:"url"              example:"http://sonarr:8989"`
	APIKey           string              `json:"api_key"          example:"***"`
	Mode             string              `json:"mode"             example:"auto"  enums:"auto,manual"`
	TimeoutSec       int                 `json:"timeout_sec"`
	SearchTimeoutSec int                 `json:"search_timeout_sec"`
	DryRun           *bool               `json:"dry_run,omitempty"`
	Tags             InstanceTags        `json:"tags"`
	Search           InstanceSearch      `json:"search"`
	Ranking          InstanceRanking     `json:"ranking"`
	Limits           InstanceLimits      `json:"limits"`
	RateLimitRPM     int                 `json:"rate_limit_rpm"`
	RateLimitBurst   int                 `json:"rate_limit_burst"`
	Cooldown         InstanceCooldown    `json:"cooldown"`
	Retry            InstanceRetry       `json:"retry"`
	HealthCheck      InstanceHealthCheck `json:"health_check"`
	// PublicURL is the optional browser-facing URL (D64). Always
	// emitted; the JSON value is `null` when no override is stored.
	PublicURL *string `json:"public_url" example:"https://sonarr.example.com"`
	// WebhookInstallEnabled toggles the 041c reconciler (D65). Always
	// emitted as a concrete bool; defaults to true on fresh rows.
	WebhookInstallEnabled bool `json:"webhook_install_enabled" example:"true"`
	// WebhookURLOverride is the optional base URL for the auto-installed
	// Sonarr webhook (D65). Always emitted; `null` when unset.
	WebhookURLOverride *string `json:"webhook_url_override" example:"https://seasonfill.example.com"`
	// ParseOnGrabEnabled toggles the 044b parse-on-OnGrab hook. Always
	// emitted as a concrete bool; defaults to true on fresh rows.
	ParseOnGrabEnabled bool `json:"parse_on_grab_enabled" example:"true"`
	// ScanSkipHandledSeasons toggles the 046b scan pre-filter. Always
	// emitted as a concrete bool; defaults to true on fresh rows. When
	// true, scans skip seasons that Sonarr already handles (complete OR
	// nothing-on-disk-and-aired). When false, every monitored season
	// goes through the full evaluator (regression guard).
	ScanSkipHandledSeasons bool `json:"scan_skip_handled_seasons" example:"true"`
	// UIURL is the derived browser-facing URL the SPA links to. Equals
	// PublicURL when set, otherwise URL. Always emitted as a non-empty
	// string so the SPA never has to compute the fallback itself.
	UIURL     string    `json:"ui_url" example:"https://sonarr.example.com"`
	UpdatedAt time.Time `json:"updated_at"`
}

type InstanceTags struct {
	Mode    string   `json:"mode"    example:"include" enums:"include,exclude,off"`
	Include []string `json:"include"`
	Exclude []string `json:"exclude"`
}

type InstanceSearch struct {
	RequireAllAired      bool `json:"require_all_aired"`
	SkipSpecials         bool `json:"skip_specials"`
	SkipAnime            bool `json:"skip_anime"`
	MinCustomFormatScore int  `json:"min_custom_format_score"`
}

type InstanceRanking struct {
	IndexerPriorityEnabled bool    `json:"indexer_priority_enabled"`
	OriginBonus            float64 `json:"origin_bonus"`
}

type InstanceLimits struct {
	ScanMaxSeries   int `json:"scan_max_series"`
	MaxGrabsPerScan int `json:"max_grabs_per_scan"`
}

type InstanceCooldown struct {
	Mode                     string `json:"mode" enums:"smart,strict"`
	SeriesAfterGrabSec       int    `json:"series_after_grab_sec"`
	GUIDAfterFailedGrabSec   int    `json:"guid_after_failed_grab_sec"`
	GUIDAfterFailedImportSec int    `json:"guid_after_failed_import_sec"`
}

type InstanceRetry struct {
	MaxAttempts       int `json:"max_attempts"`
	InitialBackoffSec int `json:"initial_backoff_sec"`
	MaxBackoffSec     int `json:"max_backoff_sec"`
}

type InstanceHealthCheck struct {
	RecheckAuthSec    int `json:"recheck_auth_sec"`
	RecheckNetworkSec int `json:"recheck_network_sec"`
}

// InstanceCreateRequest — body of POST /api/v1/instances. `api_key`
// is required on create; everything else has server-side defaults
// applied via runtime.ApplyInstanceDefaults.
//
// F-3 validation: api_key is NOT tagged `required` at the DTO layer.
// InstanceUpdateRequest is an alias of this type and Update tolerates
// `api_key == ""` ("preserve stored secret"). The use case enforces
// the "non-empty on create" rule via instance.UseCase.Create —
// see handlers/instances_crud.go writeError dispatch for the typed
// per-field code.
type InstanceCreateRequest struct {
	Name             string              `json:"name"             example:"alpha"           validate:"required,min=1,max=64"`
	URL              string              `json:"url"              example:"http://sonarr:8989" validate:"required,url"`
	APIKey           string              `json:"api_key"          example:"abcd..."`
	Mode             string              `json:"mode,omitempty"   example:"auto"            validate:"omitempty,oneof=auto manual"`
	TimeoutSec       int                 `json:"timeout_sec,omitempty" validate:"omitempty,gte=0,lte=3600"`
	SearchTimeoutSec int                 `json:"search_timeout_sec,omitempty" validate:"omitempty,gte=0,lte=3600"`
	DryRun           *bool               `json:"dry_run,omitempty"`
	Tags             InstanceTags        `json:"tags"`
	Search           InstanceSearch      `json:"search"`
	Ranking          InstanceRanking     `json:"ranking"`
	Limits           InstanceLimits      `json:"limits"`
	RateLimitRPM     int                 `json:"rate_limit_rpm"   validate:"gte=0,lte=10000"`
	RateLimitBurst   int                 `json:"rate_limit_burst" validate:"gte=0,lte=10000"`
	Cooldown         InstanceCooldown    `json:"cooldown"`
	Retry            InstanceRetry       `json:"retry"`
	HealthCheck      InstanceHealthCheck `json:"health_check"`
	// PublicURL — optional browser-facing URL. Omitted/null = no
	// override. Empty string is rejected at the application layer with
	// INVALID_INSTANCE_PUBLIC_URL so a client cannot accidentally
	// downgrade the override into a silent no-op.
	PublicURL *string `json:"public_url,omitempty" example:"https://sonarr.example.com"`
	// WebhookInstallEnabled — pointer so omitted is distinguishable
	// from explicit `false`. Omitted/null defaults to true (matches the
	// migration default). Concrete false explicitly disables the 041c
	// reconciler.
	WebhookInstallEnabled *bool `json:"webhook_install_enabled,omitempty" example:"true"`
	// WebhookURLOverride — optional base URL for the auto-installed
	// Sonarr webhook. Omitted/null = use derived public URL from
	// runtime config. Empty-string rejected as for PublicURL.
	WebhookURLOverride *string `json:"webhook_url_override,omitempty" example:"https://seasonfill.example.com"`
	// ParseOnGrabEnabled — pointer so omitted is distinguishable from
	// explicit false. Omitted/null defaults to true.
	ParseOnGrabEnabled *bool `json:"parse_on_grab_enabled,omitempty" example:"true"`
	// ScanSkipHandledSeasons — pointer so omitted is distinguishable
	// from explicit false. Omitted/null defaults to true (matches the
	// 046b migration default). Concrete false disables the scan
	// pre-filter for this instance, forcing every monitored season through
	// the full evaluator.
	ScanSkipHandledSeasons *bool `json:"scan_skip_handled_seasons,omitempty" example:"true"`
}

// InstanceUpdateRequest — body of PUT /api/v1/instances/:name.
// `api_key` is optional ("" = preserve stored secret).
type InstanceUpdateRequest = InstanceCreateRequest

type InstanceTestRequest struct {
	URL    string `json:"url"     example:"http://sonarr:8989"`
	APIKey string `json:"api_key" example:"abcd..."`
}

type InstanceTestResponse struct {
	OK      bool   `json:"ok"`
	Version string `json:"version,omitempty"`
	Reason  string `json:"reason,omitempty"`
}

// RuntimeConfigDTO is the wire shape of GET/PUT /api/v1/config/runtime.
// Mirrors runtime.Snapshot minus Instances; bootstrap-only env-driven
// fields (WebUser, WebPassword*, APIKey, database, http.bind,
// log.level) are deliberately excluded. Durations are Go-style strings
// (e.g. "30s", "12h"). AutoGeneratedAPIKey is read-only on GET — any
// value the client sends on PUT is ignored.
type RuntimeConfigDTO struct {
	Cron            RuntimeCronDTO      `json:"cron"`
	Scan            RuntimeScanDTO      `json:"scan"`
	DryRun          bool                `json:"dry_run"`
	GlobalRateLimit RuntimeRateLimitDTO `json:"global_rate_limit"`
	Auth            RuntimeAuthDTO      `json:"auth"`
	// GUIDRewrites — operator-curated tracker GUID substitutions (107).
	// Always emitted as `[]` when no rules are configured (never null).
	GUIDRewrites        []GUIDRewriteDTO `json:"guid_rewrites"`
	AutoGeneratedAPIKey bool             `json:"auto_generated_api_key" example:"false"`
	UpdatedAt           time.Time        `json:"updated_at"`
}

// GUIDRewriteDTO is one rule in the operator-curated tracker GUID
// substitution table (107). Both From and To are wire-trimmed strings.
// The frontend applies replacements via strings.Replace(s, from, to, -1)
// in array order. Empty `to` means the rule strips the substring.
type GUIDRewriteDTO struct {
	From string `json:"from" example:"http://rutracker-proxy.servarr.svc.cluster.local"`
	To   string `json:"to"   example:"https://rutracker.org"`
}

type RuntimeCronDTO struct {
	Enabled  bool   `json:"enabled"`
	Schedule string `json:"schedule" example:"0 */6 * * *"`
	OnStart  bool   `json:"on_start"`
	Jitter   string `json:"jitter"   example:"1m"`
}

type RuntimeScanDTO struct {
	ShutdownGrace string `json:"shutdown_grace" example:"60s"`
	CooldownSweep string `json:"cooldown_sweep" example:"15m"`
}

type RuntimeRateLimitDTO struct {
	RPM   int `json:"rpm"   example:"30"`
	Burst int `json:"burst" example:"10"`
}

type RuntimeAuthDTO struct {
	SessionTTL     string   `json:"session_ttl"     example:"12h"`
	SecureCookie   bool     `json:"secure_cookie"`
	TrustedProxies []string `json:"trusted_proxies" example:"127.0.0.1,::1"`
	// Mode is one of "forms" | "basic" | "none" | "oidc". Default "forms".
	Mode string `json:"mode" example:"forms"`
	// LocalBypass enables the local-address bypass middleware (036c).
	LocalBypass bool `json:"local_bypass"`
	// LocalNetworks is the CIDR allow-list driving local-bypass.
	LocalNetworks []string `json:"local_networks" example:"127.0.0.0/8,10.0.0.0/8"`
	// SessionEpoch is read-only — the server bumps it whenever any
	// auth-invalidating field changes. PUT bodies that include it are
	// silently ignored (the usecase manages the value).
	SessionEpoch int64          `json:"session_epoch" example:"0"`
	OIDC         RuntimeOIDCDTO `json:"oidc"`
}

type RuntimeOIDCDTO struct {
	Issuer        string   `json:"issuer"          example:"https://keycloak.example.com/realms/homelab"`
	ClientID      string   `json:"client_id"       example:"seasonfill"`
	RedirectURL   string   `json:"redirect_url"    example:"https://seasonfill.example.com/api/v1/auth/oidc/callback"`
	Scopes        []string `json:"scopes"          example:"openid,profile,email"`
	UsernameClaim string   `json:"username_claim"  example:"preferred_username"`
	AllowedGroups []string `json:"allowed_groups"  example:"admins"`
	GroupsClaim   string   `json:"groups_claim"    example:"groups"`
	// ClientSecret is write-only: GET responses NEVER contain a value.
	ClientSecret            *string `json:"client_secret,omitempty"`
	ClientSecretConfigured  bool    `json:"client_secret_configured"`
	ClientSecretEnvOverride bool    `json:"client_secret_env_override"`
}

// AuthConfigDTO is the wire shape of GET /api/v1/auth/config. Public
// endpoint — no secrets, no auth required. Used by the SPA bootstrap
// path to decide whether to render Login / Logout / banners.
type AuthConfigDTO struct {
	Mode        string `json:"mode" example:"forms"`
	LocalBypass bool   `json:"local_bypass" example:"false"`
	// OIDCReady mirrors middleware.OIDCRuntime.IsReady(). When true,
	// LoginURL is also populated — SPA renders SSO button regardless of mode.
	OIDCReady bool   `json:"oidc_ready" example:"false"`
	LoginURL  string `json:"login_url,omitempty" example:"/api/v1/auth/oidc/start"`
}

// QbitDiscoverDTO is the response shape for
// GET /api/v1/instances/{name}/discover/qbit. Password is never
// returned — Sonarr redacts it server-side.
type QbitDiscoverDTO struct {
	Name     string `json:"name"`
	URL      string `json:"url"`
	Username string `json:"username,omitempty"`
	Category string `json:"category"`
}

// WebhookInstallDTO is the response shape for
// POST /api/v1/instances/{name}/webhook/install. Created=false means
// a matching webhook already existed (no-op); Created=true means a
// new one was POSTed to Sonarr.
type WebhookInstallDTO struct {
	Installed      bool `json:"installed" example:"true"`
	Created        bool `json:"created"   example:"true"`
	NotificationID int  `json:"notification_id" example:"42"`
}

// WebhookStatusDTO is the response shape for
// GET /api/v1/instances/{name}/webhook/status. Queries Sonarr's
// /api/v3/notification list and reports whether our canonical webhook
// URL is already present. NotificationID and URL are only populated
// when Installed is true.
type WebhookStatusDTO struct {
	Installed      bool    `json:"installed"                  example:"true"`
	NotificationID *int    `json:"notification_id,omitempty"  example:"42"`
	URL            *string `json:"url,omitempty"              example:"https://sf.example.com/api/v1/webhook/sonarr/homelab"`
	// Error carries the last reconcile failure message (041c). nil on
	// success. Served on 200 so the UI can render an "install failed"
	// badge without a separate fetch.
	Error *string `json:"error,omitempty" example:"sonarr unauthorized"`
}

// EpisodeFileDetail — one on-disk file row from the 043c
// episode-files endpoint. Mirrors Sonarr's episodeFile resource +
// derived episode_numbers grouping. NOT persisted — fetched lazily
// per drawer open (PRD decision #6).
type EpisodeFileDetail struct {
	ID             int    `json:"id"             example:"7001"`
	RelativePath   string `json:"relative_path"  example:"Season 02/Severance.S02E01.mkv"`
	SeasonNumber   int    `json:"season_number"  example:"2"`
	EpisodeNumbers []int  `json:"episode_numbers" example:"1,2"`
	SizeBytes      int64  `json:"size_bytes"     example:"13325829734"`
	Quality        string `json:"quality"        example:"WEBDL-2160p"`
}

// EpisodeFileList — body of GET /api/v1/instances/:name/grabs/:id/episode-files.
type EpisodeFileList struct {
	Items []EpisodeFileDetail `json:"items"`
}

// SeriesCacheItem — one row of GET /api/v1/instances/:name/series-cache.
// Lean shape: omits overview/genres/banner/fanart so a 24-item Dashboard
// poster response stays under ~20 KB. F11 will introduce a separate
// detail endpoint if richer fields are needed per series.
//
// LastGrabAt / LastImportedEpisode are derived at read time from
// grab_records (imported status, latest created_at per series). Empty
// means "no imported grab on file".
type SeriesCacheItem struct {
	SonarrSeriesID domain.SonarrSeriesID `json:"sonarr_series_id"        example:"122"`
	InstanceName   domain.InstanceName   `json:"instance_name"           example:"homelab"`
	Title          string                `json:"title"                   example:"For All Mankind"`
	TitleSlug      string                `json:"title_slug"              example:"for-all-mankind"`
	Year           *int                  `json:"year,omitempty"          example:"2019"`
	// Network field REMOVED in E-1 (Story 210). Network membership lives
	// in series_networks join; the catalog tile omits the network line
	// until the detail-card endpoint (future story) projects per-row.
	Status *string `json:"status,omitempty"        example:"continuing" enums:"continuing,ended,upcoming"`
	// PosterHash is the content-addressed sha256 of the stored w342
	// hero poster (LEFT JOIN media_assets on the synthetic TMDB CDN
	// URL). Absent when the row has not been warmed yet — the FE falls
	// back to a monogram placeholder. Story 348a; Story 350 dropped the
	// legacy poster_path companion.
	PosterHash          *string    `json:"poster_hash,omitempty"   example:"3a2b1c..."`
	Monitored           bool       `json:"monitored"               example:"true"`
	MissingCount        int        `json:"missing_count"           example:"0"`
	LastGrabAt          *time.Time `json:"last_grab_at,omitempty"`
	LastImportedEpisode string     `json:"last_imported_episode,omitempty" example:"S05"`
	// LastAiredAt is the datetime of the most recent aired episode
	// (Sonarr previousAiring). Absent when the series has no aired
	// episodes (upcoming). Powers the F11 air_date_desc sort.
	LastAiredAt *time.Time `json:"last_aired_at,omitempty"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

// SeriesCacheList — body of GET /api/v1/instances/:name/series-cache.
// Total is the pre-limit count (renders "showing N of M" in the UI).
// HasMore signals an additional page exists; NextCursor encodes the
// keyset position for the next request.
type SeriesCacheList struct {
	Items      []SeriesCacheItem `json:"items"`
	Total      int               `json:"total"      example:"42"`
	HasMore    bool              `json:"has_more"   example:"true"`
	NextCursor string            `json:"next_cursor,omitempty"`
}

// SeriesCacheNetworksList is the response shape for
// GET /api/v1/instances/{name}/series-cache/networks. Story 121a §A.
type SeriesCacheNetworksList struct {
	Networks []string `json:"networks"`
} // @name SeriesCacheNetworksList

// --- Watchdog rollups (047a) -------------------------------------------------

// WatchdogRollup is the per-instance F4 dashboard projection. Pointer
// fields are nil when the instance has never been polled.
type WatchdogRollup struct {
	InstanceName    domain.InstanceName `json:"instance_name"    example:"homelab"`
	Enabled         bool                `json:"enabled"          example:"true"`
	Active          bool                `json:"active"           example:"true"`
	Watched         int                 `json:"watched"          example:"12"`
	Unregistered    int                 `json:"unregistered"     example:"24"`
	Regrabs24h      int                 `json:"regrabs_24h"      example:"1"`
	Regrabs7d       int                 `json:"regrabs_7d"       example:"5"`
	BlacklistSize   int                 `json:"blacklist_size"   example:"3"`
	LastPollAt      *time.Time          `json:"last_poll_at,omitempty"`
	LastPollResult  *string             `json:"last_poll_result,omitempty" example:"ok"`
	NextPollAt      *time.Time          `json:"next_poll_at,omitempty"`
	QbitReachable   bool                `json:"qbit_reachable"   example:"true"`
	PollIntervalSec int                 `json:"poll_interval_seconds" example:"1800"`
	CooldownHours   int                 `json:"cooldown_hours"        example:"120"`
	NoBetterMax     int                 `json:"no_better_max"         example:"3"`
}

// WatchdogRollupList — body of GET /api/v1/watchdog/rollups.
type WatchdogRollupList struct {
	Items []WatchdogRollup `json:"items"`
}

// --- Watchdog blacklist (047b) -----------------------------------------------

// WatchdogBlacklistItem is one row of GET
// /api/v1/instances/:name/watchdog/blacklist. SeriesTitle is joined from
// series_cache at handler-time; "" when the cache row is missing.
//
// Source is "auto" for rows produced by the consecutive-no-better
// escalation (the only write path in v1) and reserved as "manual" for a
// future operator-driven blacklist UI. The column is derived at read
// time so the wire shape can stabilise before the migration ships.
type WatchdogBlacklistItem struct {
	ID           uint                  `json:"id"            example:"42"`
	InstanceName domain.InstanceName   `json:"instance_name" example:"homelab"`
	SeriesID     domain.SonarrSeriesID `json:"series_id"     example:"122"`
	SeriesTitle  string                `json:"series_title"  example:"Severance"`
	SeasonNumber int                   `json:"season_number" example:"3"`
	Reason       string                `json:"reason"        example:"consecutive_no_better"`
	Source       string                `json:"source"        example:"auto" enums:"auto,manual"`
	Consecutive  int                   `json:"consecutive"   example:"3"`
	CreatedAt    time.Time             `json:"created_at"`
	ExpiresAt    *time.Time            `json:"expires_at,omitempty"`
}

// WatchdogBlacklistList — body of GET /api/v1/instances/:name/watchdog/blacklist.
type WatchdogBlacklistList struct {
	Items      []WatchdogBlacklistItem `json:"items"`
	NextCursor string                  `json:"next_cursor,omitempty"`
}

// --- Watchdog seasons (098a) -------------------------------------------------

// WatchdogSeasonOrigin mirrors the origin_releases row (instance, series,
// season). All timestamps are UTC. Indexer is empty when the row was
// inserted before the indexer-name column populated. TorrentHash is the
// qBittorrent infohash of the currently-tracked torrent for the season
// (derived from the most recent non-failed grab_records row); empty when
// no grab has reported a hash yet (pre-Phase-10 rows).
type WatchdogSeasonOrigin struct {
	Indexer     string          `json:"indexer"               example:"RuTracker (Prowlarr)"`
	FirstSeenAt time.Time       `json:"first_seen_at"`
	LastSeenAt  time.Time       `json:"last_seen_at"`
	LastUsedAt  *time.Time      `json:"last_used_at,omitempty"`
	GUID        string          `json:"guid"                  example:"abc123"`
	TorrentHash domain.QbitHash `json:"torrent_hash,omitempty" example:"a1b2c3d4e5f60718293a4b5c6d7e8f9001122334"`
}

// WatchdogSeasonCooldown surfaces an active cooldowns row scoped to one
// (instance, series, season) triple. Nil when no active cooldown exists.
type WatchdogSeasonCooldown struct {
	ExpiresAt time.Time `json:"expires_at"`
	Reason    string    `json:"reason" example:"series_after_grab"`
}

// WatchdogSeasonNoBetter surfaces one regrab_no_better_counter row. Max
// mirrors the per-instance MaxConsecutiveNoBetter setting at the time
// the row was read so the SPA can render the n/N progress directly.
type WatchdogSeasonNoBetter struct {
	Consecutive int       `json:"consecutive" example:"1"`
	Max         int       `json:"max"         example:"3"`
	LastSeenAt  time.Time `json:"last_seen_at"`
}

// WatchdogSeasonBlacklist surfaces an active watchdog_blacklist row.
// ExpiresAt is nil for v1 (manual unblock only) but kept as pointer so
// a future auto-unblock policy doesn't break the wire shape.
type WatchdogSeasonBlacklist struct {
	Reason    string     `json:"reason"     example:"consecutive_no_better"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// WatchdogSeason is one row of GET /api/v1/watchdog/seasons. All
// optional sub-objects are nil when their backing table has no row for
// the (instance, series, season) triple.
type WatchdogSeason struct {
	Instance          domain.InstanceName      `json:"instance"           example:"homelab"`
	SeriesID          domain.SonarrSeriesID    `json:"series_id"          example:"169"`
	SeriesTitle       string                   `json:"series_title"       example:"Your Friends & Neighbors"`
	SeasonNumber      int                      `json:"season_number"      example:"2"`
	Monitored         bool                     `json:"monitored"          example:"true"`
	Origin            *WatchdogSeasonOrigin    `json:"origin,omitempty"`
	Cooldown          *WatchdogSeasonCooldown  `json:"cooldown,omitempty"`
	NoBetterCounter   *WatchdogSeasonNoBetter  `json:"no_better_counter,omitempty"`
	Blacklist         *WatchdogSeasonBlacklist `json:"blacklist,omitempty"`
	MissingAiredCount int                      `json:"missing_aired_count" example:"0"`
	LastAiredAt       *time.Time               `json:"last_aired_at,omitempty"`
}

// WatchdogSeasonsList — body of GET /api/v1/watchdog/seasons. NextCursor
// is the opaque keyset cursor for the next page (encoded
// instance:series_id:season tuple).
type WatchdogSeasonsList struct {
	Items      []WatchdogSeason `json:"items"`
	NextCursor string           `json:"next_cursor,omitempty"`
}

// WatchdogSeriesSeasonStats is the per-season counter triplet derived
// from the most recent decisions row for the season. Fields are zero
// when no decision has ever run for the season.
type WatchdogSeriesSeasonStats struct {
	AiredEpisodeCount int `json:"aired_episode_count"  example:"10"`
	EpisodeFileCount  int `json:"episode_file_count"   example:"10"`
	MissingAiredCount int `json:"missing_aired_count"  example:"0"`
}

// WatchdogSeriesRecentDecision is one row of the per-season
// recent_decisions trailer on GET /api/v1/watchdog/series/:instance/:id.
// Cap is 20 most recent first.
type WatchdogSeriesRecentDecision struct {
	ID        string    `json:"id"           example:"7b3d4a92-1234-4abc-9def-000000000001"`
	ScanRunID string    `json:"scan_run_id"  example:"7b3d4a92-1234-4abc-9def-000000000099"`
	Decision  string    `json:"decision"     example:"skip"`
	Reason    string    `json:"reason"       example:"skip_all_complete"`
	CreatedAt time.Time `json:"created_at"`
}

// WatchdogSeriesRecentGrab is one row of the per-season recent_grabs
// trailer on GET /api/v1/watchdog/series/:instance/:id. Cap is 20 most
// recent first.
type WatchdogSeriesRecentGrab struct {
	ID           string    `json:"id"            example:"7b3d4a92-1234-4abc-9def-000000000002"`
	ReleaseTitle string    `json:"release_title" example:"Severance.S03E01.2160p..."`
	Status       string    `json:"status"        example:"imported"`
	ReplayOfID   *string   `json:"replay_of_id,omitempty"`
	CreatedAt    time.Time `json:"created_at"`
}

// WatchdogSeriesSeason is the per-season aggregate inside the series
// drill response. Sub-objects mirror WatchdogSeason; trailers cap the
// per-season audit slices.
type WatchdogSeriesSeason struct {
	SeasonNumber    int                            `json:"season_number"     example:"2"`
	Stats           WatchdogSeriesSeasonStats      `json:"stats"`
	Origin          *WatchdogSeasonOrigin          `json:"origin,omitempty"`
	Cooldown        *WatchdogSeasonCooldown        `json:"cooldown,omitempty"`
	NoBetterCounter *WatchdogSeasonNoBetter        `json:"no_better_counter,omitempty"`
	Blacklist       *WatchdogSeasonBlacklist       `json:"blacklist,omitempty"`
	RecentDecisions []WatchdogSeriesRecentDecision `json:"recent_decisions"`
	RecentGrabs     []WatchdogSeriesRecentGrab     `json:"recent_grabs"`
}

// WatchdogSeriesDetail — body of GET
// /api/v1/watchdog/series/:instance/:id. Seasons is sorted ascending by
// SeasonNumber so the SPA can render them in airing order without a
// client-side sort.
type WatchdogSeriesDetail struct {
	Instance    domain.InstanceName    `json:"instance"     example:"homelab"`
	SeriesID    domain.SonarrSeriesID  `json:"series_id"    example:"169"`
	SeriesTitle string                 `json:"series_title" example:"Your Friends & Neighbors"`
	Monitored   bool                   `json:"monitored"    example:"true"`
	Seasons     []WatchdogSeriesSeason `json:"seasons"`
}

// --- Webhooks status aggregate (047b) ----------------------------------------

// WebhookStatusAggregateItem is one row of GET /api/v1/webhooks/status.
// Mirrors dto.WebhookStatusDTO plus the instance name and the explicit
// Healthy convenience boolean (avoids the SPA reimplementing the rule).
type WebhookStatusAggregateItem struct {
	InstanceName   domain.InstanceName `json:"instance_name"             example:"homelab"`
	Installed      bool                `json:"installed"                 example:"true"`
	Healthy        bool                `json:"healthy"                   example:"true"`
	NotificationID *int                `json:"notification_id,omitempty" example:"42"`
	URL            *string             `json:"url,omitempty"             example:"https://sf.example/api/v1/webhook/sonarr/homelab"`
	Error          *string             `json:"error,omitempty"           example:"sonarr 503"`
}

// WebhookStatusAggregate — body of GET /api/v1/webhooks/status.
type WebhookStatusAggregate struct {
	Items          []WebhookStatusAggregateItem `json:"items"`
	HealthyCount   int                          `json:"healthy_count"   example:"1"`
	UnhealthyCount int                          `json:"unhealthy_count" example:"1"`
}

// SeasonEpisodeItem — one episode row of
// GET /instances/:name/series/:id/seasons/:season/episodes.
// `aired` mirrors the domain notion of "release-time has passed"
// (`domain/series/episode.go:18 Aired`). `monitored` and `has_file`
// are pass-through from Sonarr. The DTO is intentionally trimmed —
// the queue drill renders chips, not episode metadata.
type SeasonEpisodeItem struct {
	Number     int       `json:"number"        example:"5"`
	Title      string    `json:"title"         example:"The Jerrick Trick"`
	Monitored  bool      `json:"monitored"     example:"true"`
	HasFile    bool      `json:"has_file"      example:"false"`
	Aired      bool      `json:"aired"         example:"true"`
	AirDateUTC time.Time `json:"air_date_utc"`
}

// SeasonEpisodeList — body of
// GET /instances/:name/series/:id/seasons/:season/episodes.
// `have` counts items with `has_file == true`. `miss` counts items
// with `monitored && aired && !has_file` — matches the "aired
// missing" semantics used by the rest of the queue surface so the
// drill's `miss` count agrees with the season-chip count from
// /missing (modulo polling drift). Items are sorted ascending by
// `number`.
type SeasonEpisodeList struct {
	Items []SeasonEpisodeItem `json:"items"`
	Total int                 `json:"total" example:"24"`
	Have  int                 `json:"have"  example:"11"`
	Miss  int                 `json:"miss"  example:"13"`
}
