package commands

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"os"

	authapp "github.com/alexmorbo/seasonfill/internal/admin/app"
	admin "github.com/alexmorbo/seasonfill/internal/admin/domain"
	adminpersistence "github.com/alexmorbo/seasonfill/internal/admin/persistence"
	"github.com/alexmorbo/seasonfill/internal/config"
	"github.com/alexmorbo/seasonfill/internal/logger"
	database "github.com/alexmorbo/seasonfill/internal/shared/db"
	sharedErrors "github.com/alexmorbo/seasonfill/internal/shared/errors"
)

// ResetPassword implements `seasonfill reset-password`.
// Modes (mutually exclusive):
//
//	--print          generate + persist + print plaintext to stdout once
//	--set <password> bcrypt-hash + persist + print "Password set"
//
// Reads DB connection from env vars (SEASONFILL_DATABASE_*).
func ResetPassword(args []string) error {
	fs := flag.NewFlagSet("reset-password", flag.ContinueOnError)
	printMode := fs.Bool("print", false, "Generate + persist + print new password once")
	setVal := fs.String("set", "", "Set the password to this exact value")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *printMode == (*setVal != "") {
		return errors.New("exactly one of --print or --set <password> is required")
	}

	cfg, err := config.FromEnv()
	if err != nil {
		return fmt.Errorf("load bootstrap config: %w", err)
	}
	log := logger.New(logger.Config{
		Level: cfg.Log.Level, Format: cfg.Log.Format, Output: os.Stderr,
	})

	db, err := database.Open(cfg.Database)
	if err != nil {
		return fmt.Errorf("open database: %w", err)
	}
	defer func() {
		if sqlDB, dErr := db.DB(); dErr == nil {
			_ = sqlDB.Close()
		}
	}()
	if err := database.Migrate(db); err != nil {
		return fmt.Errorf("migrate: %w", err)
	}

	repo := adminpersistence.NewAdminUserRepository(db)
	ctx := context.Background()

	var plain string
	autoGen := false
	if *printMode {
		gen, gErr := authapp.GeneratePassword(authapp.GeneratedPasswordLen)
		if gErr != nil {
			return fmt.Errorf("generate password: %w", gErr)
		}
		plain = gen
		autoGen = true
	} else {
		plain = *setVal
		if len(plain) < authapp.MinPasswordLen {
			return fmt.Errorf("password too short (min %d chars)", authapp.MinPasswordLen)
		}
	}

	hash, err := authapp.HashPassword(plain)
	if err != nil {
		return fmt.Errorf("hash password: %w", err)
	}

	_, getErr := repo.Get(ctx)
	var adminNF *sharedErrors.AdminUserNotFoundError
	switch {
	case getErr == nil:
		if err := repo.UpdatePassword(ctx, hash, autoGen); err != nil {
			return fmt.Errorf("update password: %w", err)
		}
	case errors.As(getErr, &adminNF):
		webUser := cfg.Auth.WebUser
		if webUser == "" {
			webUser = "admin"
		}
		log.Info("reset-password.bootstrap",
			slog.String("code", "admin_user_not_found"),
			slog.String("reason", "no admin row yet, creating from CLI seed"),
			slog.String("username", webUser),
		)
		if err := repo.Create(ctx, admin.AdminUser{
			Username: webUser, PasswordHash: hash, AutoGenerated: autoGen,
		}); err != nil {
			return fmt.Errorf("create admin user: %w", err)
		}
	default:
		return fmt.Errorf("query admin user: %w", getErr)
	}

	if *printMode {
		if _, err := fmt.Fprintln(os.Stdout, plain); err != nil {
			return fmt.Errorf("write stdout: %w", err)
		}
		log.Info("reset-password.printed",
			slog.String("notice", "new password written to stdout; persist it now"))
	} else {
		if _, err := fmt.Fprintln(os.Stdout, "Password set"); err != nil {
			return fmt.Errorf("write stdout: %w", err)
		}
		log.Info("reset-password.set")
	}
	return nil
}
