package ports

import (
	"context"

	"github.com/alexmorbo/seasonfill/domain/admin"
)

// AdminUserRepository persists the single admin_users row. Methods
// return ports.ErrNotFound when no row exists.
type AdminUserRepository interface {
	Get(ctx context.Context) (admin.AdminUser, error)
	Create(ctx context.Context, u admin.AdminUser) error
	UpdatePassword(ctx context.Context, hash string, autoGenerated bool) error
}
