package ports

import (
	"context"

	admin "github.com/alexmorbo/seasonfill/internal/admin/domain"
)

// AdminUserRepository persists the single admin_users row. Methods
// return ports.ErrNotFound when no row exists.
type AdminUserRepository interface {
	Get(ctx context.Context) (admin.AdminUser, error)
	GetByOIDCSubject(ctx context.Context, subject string) (admin.AdminUser, error)
	Create(ctx context.Context, u admin.AdminUser) error
	CreateFromOIDC(ctx context.Context, subject, username string) (admin.AdminUser, error)
	UpdatePassword(ctx context.Context, hash string, autoGenerated bool) error
}
