package ports

import (
	"context"
	"time"

	"github.com/alexmorbo/seasonfill/internal/runtime"
	"github.com/alexmorbo/seasonfill/internal/runtime/crypto"
)

// RuntimeConfigRow mirrors RuntimeConfigModel for transport between
// the repo and its callers (no DB model leaks).
type RuntimeConfigRow struct {
	Cron                runtime.CronSnapshot
	Scan                runtime.ScanSnapshot
	DryRun              bool
	GlobalRateLimit     runtime.RateLimitSnapshot
	Auth                runtime.AuthSnapshot
	APIKeyCiphertext    []byte
	APIKeyAutoGenerated bool
}

type RuntimeConfigRepository interface {
	// Get returns the singleton row. ErrNotFound when the row hasn't
	// been written yet.
	Get(ctx context.Context) (RuntimeConfigRow, error)

	// Upsert writes the singleton row from a runtime.Snapshot. Used
	// by both the seed-on-empty bootstrap path and (in 027c) the
	// HTTP PUT handler.
	Upsert(ctx context.Context, snap runtime.Snapshot) error

	// SaveAPIKey stores the encrypted master-API-key probe. Used by
	// the bootstrap auto-gen flow (application/bootstrap/apikey.go).
	SaveAPIKey(ctx context.Context, ciphertext []byte, autoGenerated bool) error
}

type SonarrInstanceRepository interface {
	List(ctx context.Context, c *crypto.Cipher) ([]runtime.InstanceSnapshot, error)
	GetByName(ctx context.Context, name string, c *crypto.Cipher) (runtime.InstanceSnapshot, error)
	Create(ctx context.Context, inst runtime.InstanceSnapshot, c *crypto.Cipher) (uint, error)
	Update(ctx context.Context, inst runtime.InstanceSnapshot, c *crypto.Cipher) error
	UpdateWithOptions(ctx context.Context, inst runtime.InstanceSnapshot, c *crypto.Cipher, preserveSecret bool) error
	Delete(ctx context.Context, name string) error
	Count(ctx context.Context) (int, error)
	GetUpdatedAt(ctx context.Context, name string) (time.Time, error)
}
