package persistence

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"gorm.io/gorm"

	"github.com/alexmorbo/seasonfill/internal/runtime"
	"github.com/alexmorbo/seasonfill/internal/runtime/crypto"
	ports "github.com/alexmorbo/seasonfill/internal/shared/dataports"
	database "github.com/alexmorbo/seasonfill/internal/shared/db"
	sharedErrors "github.com/alexmorbo/seasonfill/internal/shared/errors"
)

// Secret names persisted in app_secret. The legacy runtime_config
// stored these as BYTEA columns; D-5 moves them to app_secret rows
// keyed by secret_name (one row per logical secret).
const (
	secretNameAPIKeyProbe      = "api_key_probe"
	secretNameOIDCClientSecret = "oidc_client_secret"
)

// appConfigID is the singleton primary key for the app_config row.
// CHECK id=1 at the DB layer enforces uniqueness; the app refuses to
// write any other id.
const appConfigID = uint(1)

type RuntimeConfigRepository struct {
	db     *gorm.DB
	cipher *crypto.Cipher
}

func NewRuntimeConfigRepository(db *gorm.DB, cipher *crypto.Cipher) *RuntimeConfigRepository {
	return &RuntimeConfigRepository{db: db, cipher: cipher}
}

// Get reads the singleton app_config row plus the two app_secret rows
// (api_key_probe + oidc_client_secret) and assembles a
// ports.RuntimeConfigRow. ErrNotFound (with typed
// RuntimeConfigNotFoundError joined) is returned when the app_config
// row has not been written yet. Missing app_secret rows are tolerated
// — the OIDC / api_key ciphertext fields are left nil.
func (r *RuntimeConfigRepository) Get(ctx context.Context) (ports.RuntimeConfigRow, error) {
	db := dbFromContext(ctx, r.db).WithContext(ctx)

	var m database.AppConfigModel
	if err := db.Where("id = ?", appConfigID).First(&m).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return ports.RuntimeConfigRow{}, errors.Join(
				&sharedErrors.RuntimeConfigNotFoundError{},
				ports.ErrNotFound,
			)
		}
		return ports.RuntimeConfigRow{}, fmt.Errorf("get app_config: %w", err)
	}

	row := ports.RuntimeConfigRow{
		Cron: runtime.CronSnapshot{
			Enabled:  m.CronEnabled,
			Schedule: m.CronSchedule,
			OnStart:  m.CronOnStart,
			Jitter:   time.Duration(m.CronJitterSeconds) * time.Second,
		},
		Scan: runtime.ScanSnapshot{
			ShutdownGrace: time.Duration(m.ScanShutdownGraceSec) * time.Second,
			CooldownSweep: time.Duration(m.ScanCooldownSweepSec) * time.Second,
		},
		DryRun: m.DryRun,
		GlobalRateLimit: runtime.RateLimitSnapshot{
			RPM:   m.GlobalRPM,
			Burst: m.GlobalBurst,
		},
		Auth: runtime.AuthSnapshot{
			SessionTTL:   time.Duration(m.AuthSessionTTLSec) * time.Second,
			SecureCookie: m.AuthSecureCookie,
			SessionEpoch: m.AuthSessionEpoch,
		},
		APIKeyAutoGenerated: m.APIKeyAutoGenerated,
		UpdatedAt:           m.UpdatedAt,
	}
	if m.AuthTrustedProxies != "" {
		_ = json.Unmarshal([]byte(m.AuthTrustedProxies), &row.Auth.TrustedProxies)
	}
	row.Auth.OIDC = runtime.OIDCSnapshot{
		Issuer:        m.OIDCIssuer,
		ClientID:      m.OIDCClientID,
		RedirectURL:   m.OIDCRedirectURL,
		UsernameClaim: m.OIDCUsernameClaim,
	}
	if m.OIDCScopes != "" {
		_ = json.Unmarshal([]byte(m.OIDCScopes), &row.Auth.OIDC.Scopes)
	}
	if len(row.Auth.OIDC.Scopes) == 0 {
		row.Auth.OIDC.Scopes = runtime.DefaultOIDCSnapshot().Scopes
	}
	if row.Auth.OIDC.UsernameClaim == "" {
		row.Auth.OIDC.UsernameClaim = runtime.DefaultOIDCSnapshot().UsernameClaim
	}
	if m.OIDCAllowedGroups != "" {
		_ = json.Unmarshal([]byte(m.OIDCAllowedGroups), &row.Auth.OIDC.AllowedGroups)
	}
	if row.Auth.OIDC.AllowedGroups == nil {
		row.Auth.OIDC.AllowedGroups = []string{}
	}
	row.Auth.OIDC.GroupsClaim = m.OIDCGroupsClaim
	if row.Auth.OIDC.GroupsClaim == "" {
		row.Auth.OIDC.GroupsClaim = "groups"
	}
	// guid_rewrites — NULL/empty TEXT → empty (non-nil) slice. Malformed
	// JSON falls back to empty on purpose: a corrupt row should not 500
	// the entire GET handler. The next PUT canonicalises the column.
	// Story 107.
	row.GUIDRewrites = []runtime.GUIDRewriteRule{}
	if m.GUIDRewrites != "" {
		var parsed []runtime.GUIDRewriteRule
		if err := json.Unmarshal([]byte(m.GUIDRewrites), &parsed); err == nil && parsed != nil {
			row.GUIDRewrites = parsed
		}
	}

	// LEFT JOIN-style lookups into app_secret — missing rows are fine.
	ct, err := r.readAppSecret(ctx, db, secretNameOIDCClientSecret)
	if err != nil {
		return ports.RuntimeConfigRow{}, fmt.Errorf("get oidc client secret: %w", err)
	}
	if len(ct) > 0 {
		row.OIDCClientSecretCiphertext = append([]byte(nil), ct...)
	}

	ct, err = r.readAppSecret(ctx, db, secretNameAPIKeyProbe)
	if err != nil {
		return ports.RuntimeConfigRow{}, fmt.Errorf("get api_key probe: %w", err)
	}
	if len(ct) > 0 {
		row.APIKeyCiphertext = append([]byte(nil), ct...)
	}

	return row, nil
}

// readAppSecret returns the encrypted_value for an app_secret row by
// secret_name. Returns (nil, nil) when the row is absent — the
// caller treats nil bytes as "not set". Surfaces unexpected errors
// wrapped.
func (r *RuntimeConfigRepository) readAppSecret(_ context.Context, db *gorm.DB, name string) ([]byte, error) {
	var s database.AppSecretModel
	err := db.Where("secret_name = ?", name).Take(&s).Error
	if err == nil {
		return s.EncryptedValue, nil
	}
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	return nil, err
}

// Upsert writes the singleton app_config row. When ifUnmodifiedSince
// != nil and the existing row exists with updated_at strictly newer
// than the header value (second-truncated), returns ports.ErrStaleWrite
// without writing. The "row missing → create fresh" path is taken
// regardless of ifUnmodifiedSince (the first ever PUT can't be stale).
func (r *RuntimeConfigRepository) Upsert(
	ctx context.Context,
	snap runtime.Snapshot,
	ifUnmodifiedSince *time.Time,
) error {
	proxies, _ := json.Marshal(snap.Auth.TrustedProxies)
	oidcScopes, _ := json.Marshal(snap.Auth.OIDC.Scopes)
	oidcGroups, _ := json.Marshal(snap.Auth.OIDC.AllowedGroups)
	rewriteList := snap.GUIDRewrites
	if rewriteList == nil {
		rewriteList = []runtime.GUIDRewriteRule{}
	}
	rewrites, _ := json.Marshal(rewriteList)

	return dbFromContext(ctx, r.db).WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		now := time.Now().UTC()

		var existing database.AppConfigModel
		err := tx.Where("id = ?", appConfigID).First(&existing).Error
		switch {
		case err == nil:
			if ifUnmodifiedSince != nil {
				stored := existing.UpdatedAt.Truncate(time.Second)
				provided := ifUnmodifiedSince.Truncate(time.Second)
				if stored.After(provided) {
					return ports.ErrStaleWrite
				}
			}
			existing.CronEnabled = snap.Cron.Enabled
			existing.CronSchedule = snap.Cron.Schedule
			existing.CronOnStart = snap.Cron.OnStart
			existing.CronJitterSeconds = int(snap.Cron.Jitter / time.Second)
			existing.ScanShutdownGraceSec = int(snap.Scan.ShutdownGrace / time.Second)
			existing.ScanCooldownSweepSec = int(snap.Scan.CooldownSweep / time.Second)
			existing.DryRun = snap.DryRun
			existing.GlobalRPM = snap.GlobalRateLimit.RPM
			existing.GlobalBurst = snap.GlobalRateLimit.Burst
			existing.AuthSessionTTLSec = int(snap.Auth.SessionTTL / time.Second)
			existing.AuthSecureCookie = snap.Auth.SecureCookie
			existing.AuthTrustedProxies = string(proxies)
			existing.AuthSessionEpoch = snap.Auth.SessionEpoch
			existing.OIDCIssuer = snap.Auth.OIDC.Issuer
			existing.OIDCClientID = snap.Auth.OIDC.ClientID
			existing.OIDCRedirectURL = snap.Auth.OIDC.RedirectURL
			existing.OIDCScopes = string(oidcScopes)
			existing.OIDCUsernameClaim = snap.Auth.OIDC.UsernameClaim
			existing.OIDCAllowedGroups = string(oidcGroups)
			existing.OIDCGroupsClaim = snap.Auth.OIDC.GroupsClaim
			existing.GUIDRewrites = string(rewrites)
			existing.UpdatedAt = now
			return tx.Save(&existing).Error
		case errors.Is(err, gorm.ErrRecordNotFound):
			row := database.AppConfigModel{
				ID:                   appConfigID,
				CronEnabled:          snap.Cron.Enabled,
				CronSchedule:         snap.Cron.Schedule,
				CronOnStart:          snap.Cron.OnStart,
				CronJitterSeconds:    int(snap.Cron.Jitter / time.Second),
				ScanShutdownGraceSec: int(snap.Scan.ShutdownGrace / time.Second),
				ScanCooldownSweepSec: int(snap.Scan.CooldownSweep / time.Second),
				DryRun:               snap.DryRun,
				GlobalRPM:            snap.GlobalRateLimit.RPM,
				GlobalBurst:          snap.GlobalRateLimit.Burst,
				AuthSessionTTLSec:    int(snap.Auth.SessionTTL / time.Second),
				AuthSecureCookie:     snap.Auth.SecureCookie,
				AuthTrustedProxies:   string(proxies),
				AuthSessionEpoch:     snap.Auth.SessionEpoch,
				OIDCIssuer:           snap.Auth.OIDC.Issuer,
				OIDCClientID:         snap.Auth.OIDC.ClientID,
				OIDCRedirectURL:      snap.Auth.OIDC.RedirectURL,
				OIDCScopes:           string(oidcScopes),
				OIDCUsernameClaim:    snap.Auth.OIDC.UsernameClaim,
				OIDCAllowedGroups:    string(oidcGroups),
				OIDCGroupsClaim:      snap.Auth.OIDC.GroupsClaim,
				GUIDRewrites:         string(rewrites),
				CreatedAt:            now,
				UpdatedAt:            now,
			}
			return tx.Create(&row).Error
		default:
			return fmt.Errorf("upsert app_config: %w", err)
		}
	})
}

// SaveAPIKey persists the encrypted master-key probe in app_secret
// (secret_name='api_key_probe') and stamps app_config.api_key_auto_generated.
// When the app_config row is missing, seeds it with defaults
// + the supplied auto-generated flag so bootstrap can publish a
// usable snapshot on first run.
func (r *RuntimeConfigRepository) SaveAPIKey(ctx context.Context, ct []byte, autoGen bool) error {
	return dbFromContext(ctx, r.db).WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		now := time.Now().UTC()
		if err := writeAppSecret(tx, secretNameAPIKeyProbe, ct, now); err != nil {
			return fmt.Errorf("save api key: %w", err)
		}

		var existing database.AppConfigModel
		err := tx.Where("id = ?", appConfigID).First(&existing).Error
		switch {
		case err == nil:
			existing.APIKeyAutoGenerated = autoGen
			existing.UpdatedAt = now
			return tx.Save(&existing).Error
		case errors.Is(err, gorm.ErrRecordNotFound):
			def := runtime.Defaults()
			proxiesJSON, _ := json.Marshal(def.Auth.TrustedProxies)
			row := database.AppConfigModel{
				ID:                   appConfigID,
				APIKeyAutoGenerated:  autoGen,
				CreatedAt:            now,
				UpdatedAt:            now,
				CronEnabled:          def.Cron.Enabled,
				CronSchedule:         def.Cron.Schedule,
				CronJitterSeconds:    int(def.Cron.Jitter / time.Second),
				ScanShutdownGraceSec: int(def.Scan.ShutdownGrace / time.Second),
				ScanCooldownSweepSec: int(def.Scan.CooldownSweep / time.Second),
				DryRun:               def.DryRun,
				GlobalRPM:            def.GlobalRateLimit.RPM,
				GlobalBurst:          def.GlobalRateLimit.Burst,
				AuthSessionTTLSec:    int(def.Auth.SessionTTL / time.Second),
				AuthSecureCookie:     def.Auth.SecureCookie,
				AuthTrustedProxies:   string(proxiesJSON),
				AuthSessionEpoch:     def.Auth.SessionEpoch,
				OIDCIssuer:           def.Auth.OIDC.Issuer,
				OIDCClientID:         def.Auth.OIDC.ClientID,
				OIDCRedirectURL:      def.Auth.OIDC.RedirectURL,
				OIDCScopes:           string(mustJSON(def.Auth.OIDC.Scopes)),
				OIDCUsernameClaim:    def.Auth.OIDC.UsernameClaim,
				OIDCAllowedGroups:    string(mustJSON(def.Auth.OIDC.AllowedGroups)),
				OIDCGroupsClaim:      "groups",
				GUIDRewrites:         "[]",
			}
			return tx.Create(&row).Error
		default:
			return fmt.Errorf("save api key: %w", err)
		}
	})
}

func mustJSON(v any) []byte { b, _ := json.Marshal(v); return b }

// UpsertOIDCSecret writes the AES-GCM ciphertext for the OIDC client
// secret into app_secret(secret_name='oidc_client_secret'). Empty
// plaintext deletes the row (operator clearing the secret).
func (r *RuntimeConfigRepository) UpsertOIDCSecret(ctx context.Context, plaintext string) error {
	db := dbFromContext(ctx, r.db).WithContext(ctx)
	now := time.Now().UTC()
	if plaintext == "" {
		if err := db.Where("secret_name = ?", secretNameOIDCClientSecret).
			Delete(&database.AppSecretModel{}).Error; err != nil {
			return fmt.Errorf("clear oidc client secret: %w", err)
		}
		return nil
	}
	if r.cipher == nil {
		return fmt.Errorf("oidc client secret: cipher not configured")
	}
	sealed, err := r.cipher.Seal([]byte(plaintext))
	if err != nil {
		return fmt.Errorf("seal oidc client secret: %w", err)
	}
	if err := writeAppSecret(db, secretNameOIDCClientSecret, sealed, now); err != nil {
		return fmt.Errorf("upsert oidc client secret: %w", err)
	}
	return nil
}

// DecryptOIDCSecret returns the plaintext OIDC client secret stored
// in app_secret(secret_name='oidc_client_secret'). Empty string when
// the row is absent (no secret configured) so the env override path
// remains the source of truth.
func (r *RuntimeConfigRepository) DecryptOIDCSecret(ctx context.Context) (string, error) {
	if r.cipher == nil {
		return "", nil
	}
	db := dbFromContext(ctx, r.db).WithContext(ctx)
	ct, err := r.readAppSecret(ctx, db, secretNameOIDCClientSecret)
	if err != nil {
		return "", fmt.Errorf("load oidc client secret: %w", err)
	}
	if len(ct) == 0 {
		return "", nil
	}
	pt, err := r.cipher.Open(ct)
	if err != nil {
		return "", fmt.Errorf("decrypt oidc client secret: %w", err)
	}
	return string(pt), nil
}

// writeAppSecret upserts a single (secret_name, encrypted_value) row.
// Uses Find→Create/Save rather than Clauses(OnConflict) to keep the
// SQL portable across SQLite + Postgres (the dialects diverge on
// ON CONFLICT DO UPDATE shape for non-PK conflict targets).
func writeAppSecret(db *gorm.DB, name string, value []byte, now time.Time) error {
	var existing database.AppSecretModel
	err := db.Where("secret_name = ?", name).Take(&existing).Error
	switch {
	case err == nil:
		existing.EncryptedValue = value
		existing.UpdatedAt = now
		return db.Save(&existing).Error
	case errors.Is(err, gorm.ErrRecordNotFound):
		row := database.AppSecretModel{
			SecretName:     name,
			EncryptedValue: value,
			CreatedAt:      now,
			UpdatedAt:      now,
		}
		return db.Create(&row).Error
	default:
		return err
	}
}

// GetTimezone returns the operator-selected IANA timezone name from
// the singleton app_config.timezone column. Empty string + nil error
// when the column is NULL (no override; tz resolver falls back to env
// / UTC). Returns ports.ErrNotFound only when the app_config row
// itself is missing (pre-bootstrap state). D-5 / 466c re-homed this
// off the legacy app_settings table.
func (r *RuntimeConfigRepository) GetTimezone(ctx context.Context) (string, error) {
	var m database.AppConfigModel
	err := dbFromContext(ctx, r.db).WithContext(ctx).
		Select("timezone").
		Where("id = ?", appConfigID).
		First(&m).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return "", ports.ErrNotFound
		}
		return "", fmt.Errorf("get timezone: %w", err)
	}
	if m.Timezone == nil {
		return "", nil
	}
	return *m.Timezone, nil
}

// SetTimezone writes name into app_config.timezone. Empty name clears
// the override (SQL NULL). Seeds a defaults-filled row on first call
// so the operator can persist a timezone before the rest of the
// runtime_config singleton is written by the HTTP PUT path.
func (r *RuntimeConfigRepository) SetTimezone(ctx context.Context, name string) error {
	return dbFromContext(ctx, r.db).WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		now := time.Now().UTC()
		var tzPtr *string
		if name != "" {
			n := name
			tzPtr = &n
		}

		var existing database.AppConfigModel
		err := tx.Where("id = ?", appConfigID).First(&existing).Error
		switch {
		case err == nil:
			existing.Timezone = tzPtr
			existing.UpdatedAt = now
			return tx.Save(&existing).Error
		case errors.Is(err, gorm.ErrRecordNotFound):
			def := runtime.Defaults()
			proxiesJSON, _ := json.Marshal(def.Auth.TrustedProxies)
			row := database.AppConfigModel{
				ID:                   appConfigID,
				CreatedAt:            now,
				UpdatedAt:            now,
				Timezone:             tzPtr,
				CronEnabled:          def.Cron.Enabled,
				CronSchedule:         def.Cron.Schedule,
				CronJitterSeconds:    int(def.Cron.Jitter / time.Second),
				ScanShutdownGraceSec: int(def.Scan.ShutdownGrace / time.Second),
				ScanCooldownSweepSec: int(def.Scan.CooldownSweep / time.Second),
				DryRun:               def.DryRun,
				GlobalRPM:            def.GlobalRateLimit.RPM,
				GlobalBurst:          def.GlobalRateLimit.Burst,
				AuthSessionTTLSec:    int(def.Auth.SessionTTL / time.Second),
				AuthSecureCookie:     def.Auth.SecureCookie,
				AuthTrustedProxies:   string(proxiesJSON),
				AuthSessionEpoch:     def.Auth.SessionEpoch,
				OIDCIssuer:           def.Auth.OIDC.Issuer,
				OIDCClientID:         def.Auth.OIDC.ClientID,
				OIDCRedirectURL:      def.Auth.OIDC.RedirectURL,
				OIDCScopes:           string(mustJSON(def.Auth.OIDC.Scopes)),
				OIDCUsernameClaim:    def.Auth.OIDC.UsernameClaim,
				OIDCAllowedGroups:    string(mustJSON(def.Auth.OIDC.AllowedGroups)),
				OIDCGroupsClaim:      "groups",
				GUIDRewrites:         "[]",
			}
			return tx.Create(&row).Error
		default:
			return fmt.Errorf("set timezone: %w", err)
		}
	})
}

var _ ports.RuntimeConfigRepository = (*RuntimeConfigRepository)(nil)
