package persistence

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/alexmorbo/seasonfill/internal/runtime"
	"github.com/alexmorbo/seasonfill/internal/runtime/crypto"
	ports "github.com/alexmorbo/seasonfill/internal/shared/dataports"
	database "github.com/alexmorbo/seasonfill/internal/shared/db"
	sharedErrors "github.com/alexmorbo/seasonfill/internal/shared/errors"
	"github.com/alexmorbo/seasonfill/internal/shared/testhelpers"
)

func TestRuntimeConfigRepository_GetNotFound(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)

			_, err := repo.Get(context.Background())
			require.ErrorIs(t, err, ports.ErrNotFound)

			var typed *sharedErrors.RuntimeConfigNotFoundError
			require.True(t, errors.As(err, &typed),
				"Get on empty table must expose typed RuntimeConfigNotFoundError via errors.As")
		})
	}
}

func TestRuntimeConfigRepository_UpsertAndGet(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			snap := runtime.Snapshot{
				Cron: runtime.CronSnapshot{
					Enabled:  true,
					Schedule: "0 12 * * *",
					OnStart:  false,
					Jitter:   2 * time.Minute,
				},
				Scan: runtime.ScanSnapshot{
					ShutdownGrace: 90 * time.Second,
					CooldownSweep: 20 * time.Minute,
				},
				DryRun: false,
				GlobalRateLimit: runtime.RateLimitSnapshot{
					RPM: 60, Burst: 20,
				},
				Auth: runtime.AuthSnapshot{
					SessionTTL:     24 * time.Hour,
					SecureCookie:   true,
					TrustedProxies: []string{"10.0.0.1", "10.0.0.2"},
					Mode:           runtime.AuthModeForms,
				},
			}

			require.NoError(t, repo.Upsert(ctx, snap, nil))

			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Equal(t, snap.Cron.Enabled, row.Cron.Enabled)
			assert.Equal(t, snap.Cron.Schedule, row.Cron.Schedule)
			assert.Equal(t, snap.Cron.Jitter, row.Cron.Jitter)
			assert.Equal(t, snap.DryRun, row.DryRun)
			assert.Equal(t, snap.GlobalRateLimit.RPM, row.GlobalRateLimit.RPM)
			assert.Equal(t, snap.Auth.SessionTTL, row.Auth.SessionTTL)
			assert.Equal(t, snap.Auth.SecureCookie, row.Auth.SecureCookie)
			assert.Equal(t, snap.Auth.TrustedProxies, row.Auth.TrustedProxies)
		})
	}
}

func TestRuntimeConfigRepository_SaveAPIKey_Fresh(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			ct := []byte{0x01, 0x02, 0x03}
			require.NoError(t, repo.SaveAPIKey(ctx, ct, true))

			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Equal(t, ct, row.APIKeyCiphertext)
			assert.True(t, row.APIKeyAutoGenerated)
			assert.True(t, row.Cron.Enabled)
			assert.Equal(t, "0 */6 * * *", row.Cron.Schedule)
		})
	}
}

func TestRuntimeConfigRepository_SaveAPIKey_Existing(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			snap := runtime.Defaults()
			require.NoError(t, repo.Upsert(ctx, snap, nil))

			ct := []byte{0x04, 0x05, 0x06}
			require.NoError(t, repo.SaveAPIKey(ctx, ct, false))

			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Equal(t, ct, row.APIKeyCiphertext)
			assert.False(t, row.APIKeyAutoGenerated)
			assert.Equal(t, snap.Cron.Schedule, row.Cron.Schedule)
		})
	}
}

func TestRuntimeConfigRepository_Upsert_StaleIUS_Rejects(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			snap := runtime.Defaults()
			require.NoError(t, repo.Upsert(ctx, snap, nil))
			row, err := repo.Get(ctx)
			require.NoError(t, err)
			staleHeader := row.UpdatedAt.Add(-1 * time.Second)

			snap.Cron.Schedule = "0 0 * * *"
			require.ErrorIs(t, repo.Upsert(ctx, snap, &staleHeader), ports.ErrStaleWrite)

			got, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.NotEqual(t, "0 0 * * *", got.Cron.Schedule, "stale write must not persist")
		})
	}
}

func TestRuntimeConfigRepository_Upsert_FreshIUS_Writes(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			snap := runtime.Defaults()
			require.NoError(t, repo.Upsert(ctx, snap, nil))
			row, err := repo.Get(ctx)
			require.NoError(t, err)
			fresh := row.UpdatedAt.Truncate(time.Second)

			snap.Cron.Schedule = "0 0 * * *"
			require.NoError(t, repo.Upsert(ctx, snap, &fresh))
			got, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Equal(t, "0 0 * * *", got.Cron.Schedule)
		})
	}
}

func TestRuntimeConfigRepository_Upsert_NoIUS_LWW(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			snap := runtime.Defaults()
			require.NoError(t, repo.Upsert(ctx, snap, nil))
			snap.Cron.Schedule = "30 * * * *"
			require.NoError(t, repo.Upsert(ctx, snap, nil))
			got, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Equal(t, "30 * * * *", got.Cron.Schedule)
		})
	}
}

func TestRuntimeConfigRepository_Upsert_FreshRow_IgnoresIUS(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			// First ever PUT — no existing row to be stale against.
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			header := time.Now().UTC().Add(-time.Hour)
			snap := runtime.Defaults()
			require.NoError(t, repo.Upsert(ctx, snap, &header))
		})
	}
}

func TestRuntimeConfigRepository_AuthModes_RoundTrip(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			snap := runtime.Defaults()
			snap.Auth.Mode = runtime.AuthModeBasic
			snap.Auth.LocalBypass = true
			snap.Auth.LocalNetworks = []string{"127.0.0.0/8", "10.0.0.0/8"}
			snap.Auth.SessionEpoch = 123456789

			require.NoError(t, repo.Upsert(ctx, snap, nil))
			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Equal(t, runtime.AuthModeBasic, row.Auth.Mode)
			assert.True(t, row.Auth.LocalBypass)
			assert.Equal(t, []string{"127.0.0.0/8", "10.0.0.0/8"}, row.Auth.LocalNetworks)
			assert.Equal(t, int64(123456789), row.Auth.SessionEpoch)
		})
	}
}

func TestRuntimeConfigRepository_AuthModeNormalizesEmpty(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			snap := runtime.Defaults()
			snap.Auth.Mode = "" // legacy / mis-seeded row
			require.NoError(t, repo.Upsert(ctx, snap, nil))
			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Equal(t, runtime.AuthModeForms, row.Auth.Mode,
				"empty mode must normalize to forms")
		})
	}
}

func TestRuntimeConfigRepository_LocalNetworksFallback(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			snap := runtime.Defaults()
			snap.Auth.LocalNetworks = nil
			require.NoError(t, repo.Upsert(ctx, snap, nil))
			row, err := repo.Get(ctx)
			require.NoError(t, err)
			// Empty list → fall back to the hardcoded default network set so
			// the bypass middleware never operates on an empty allow-list by
			// accident.
			assert.NotEmpty(t, row.Auth.LocalNetworks)
			assert.Contains(t, row.Auth.LocalNetworks, "127.0.0.0/8")
		})
	}
}

// --- OIDC round-trip tests ---

func TestRuntimeConfigRepository_OIDCFields_FullRoundTrip(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			snap := runtime.Defaults()
			snap.Auth.Mode = runtime.AuthModeOIDC
			snap.Auth.OIDC = runtime.OIDCSnapshot{
				Issuer:        "https://sso.example.com",
				ClientID:      "seasonfill-client",
				RedirectURL:   "https://app.example.com/callback",
				Scopes:        []string{"openid", "profile", "email"},
				UsernameClaim: "preferred_username",
				AllowedGroups: []string{"admins", "editors"},
				GroupsClaim:   "groups",
			}

			require.NoError(t, repo.Upsert(ctx, snap, nil))
			row, err := repo.Get(ctx)
			require.NoError(t, err)

			assert.Equal(t, "https://sso.example.com", row.Auth.OIDC.Issuer)
			assert.Equal(t, "seasonfill-client", row.Auth.OIDC.ClientID)
			assert.Equal(t, "https://app.example.com/callback", row.Auth.OIDC.RedirectURL)
			assert.Equal(t, []string{"openid", "profile", "email"}, row.Auth.OIDC.Scopes)
			assert.Equal(t, "preferred_username", row.Auth.OIDC.UsernameClaim)
			assert.Equal(t, []string{"admins", "editors"}, row.Auth.OIDC.AllowedGroups)
		})
	}
}

func TestRuntimeConfigRepository_OIDCFields_DefaultsWhenAbsent(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			// Upsert with all OIDC fields at zero-value (not mode=oidc, no explicit OIDC config).
			snap := runtime.Defaults()
			// Explicitly zero the OIDC sub-struct to simulate a pre-OIDC row.
			snap.Auth.OIDC = runtime.OIDCSnapshot{}
			require.NoError(t, repo.Upsert(ctx, snap, nil))

			row, err := repo.Get(ctx)
			require.NoError(t, err)

			// Issuer, ClientID, RedirectURL default to empty.
			assert.Empty(t, row.Auth.OIDC.Issuer)
			assert.Empty(t, row.Auth.OIDC.ClientID)
			assert.Empty(t, row.Auth.OIDC.RedirectURL)
			// Scopes fall back to the default set when stored value is empty.
			assert.Equal(t, runtime.DefaultOIDCSnapshot().Scopes, row.Auth.OIDC.Scopes)
			// AllowedGroups falls back to an empty (non-nil) slice.
			assert.NotNil(t, row.Auth.OIDC.AllowedGroups)
			assert.Empty(t, row.Auth.OIDC.AllowedGroups)
			// UsernameClaim falls back to the default.
			assert.Equal(t, runtime.DefaultOIDCSnapshot().UsernameClaim, row.Auth.OIDC.UsernameClaim)
		})
	}
}

func TestRuntimeConfigRepository_OIDCScopes_OrderPreserved(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			ordered := []string{"openid", "profile", "email", "groups"}
			snap := runtime.Defaults()
			snap.Auth.OIDC.Scopes = ordered
			require.NoError(t, repo.Upsert(ctx, snap, nil))

			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Equal(t, ordered, row.Auth.OIDC.Scopes,
				"scopes JSON round-trip must preserve order and elements")
		})
	}
}

func TestRuntimeConfigRepository_OIDCAllowedGroups_OrderPreserved(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			ordered := []string{"zebra-team", "alpha-team", "beta-team"}
			snap := runtime.Defaults()
			snap.Auth.OIDC.AllowedGroups = ordered
			require.NoError(t, repo.Upsert(ctx, snap, nil))

			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Equal(t, ordered, row.Auth.OIDC.AllowedGroups,
				"allowed_groups JSON round-trip must preserve order and elements")
		})
	}
}

// --- 107: guid_rewrites round-trip ---------------------------------------

func TestRuntimeConfigRepository_GUIDRewrites_PreservesOrder(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			ordered := []runtime.GUIDRewriteRule{
				{From: "http://rutracker-proxy", To: "https://rutracker.org"},
				{From: "http://nnm-proxy", To: "https://nnm-club.me"},
				{From: "http://kinozal-proxy", To: "https://kinozal.tv"},
			}
			snap := runtime.Defaults()
			snap.GUIDRewrites = ordered
			require.NoError(t, repo.Upsert(ctx, snap, nil))

			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Equal(t, ordered, row.GUIDRewrites,
				"order and content must round-trip through JSON serialisation")
		})
	}
}

func TestRuntimeConfigRepository_GUIDRewrites_EmptyOnFreshRow(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			snap := runtime.Defaults()
			require.NoError(t, repo.Upsert(ctx, snap, nil))

			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.NotNil(t, row.GUIDRewrites)
			assert.Empty(t, row.GUIDRewrites)
		})
	}
}

func TestRuntimeConfigRepository_GUIDRewrites_NilSnapshotPersistsEmptyArray(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			snap := runtime.Defaults()
			snap.GUIDRewrites = nil // simulate a snapshot built without the field
			require.NoError(t, repo.Upsert(ctx, snap, nil))

			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.NotNil(t, row.GUIDRewrites,
				"nil snapshot must persist as `[]` so Get returns non-nil")
			assert.Empty(t, row.GUIDRewrites)
		})
	}
}

func TestRuntimeConfigRepository_GUIDRewrites_SaveAPIKeyBootstrap(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			// SaveAPIKey on a missing row seeds defaults — verify guid_rewrites
			// arrives as a valid empty JSON array so a subsequent Get works.
			require.NoError(t, repo.SaveAPIKey(ctx, []byte{0xAA}, true))
			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.NotNil(t, row.GUIDRewrites)
			assert.Empty(t, row.GUIDRewrites)
		})
	}
}

// --- D-5 (466b) NEW tests ---

// TestRuntimeConfigRepository_AppConfig_SingletonGuard proves the DB
// rejects any insert with id != 1 (Postgres CHECK + SQLite CHECK both
// honor it).
func TestRuntimeConfigRepository_AppConfig_SingletonGuard(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			// Seed a valid id=1 row.
			repo := NewRuntimeConfigRepository(db, nil)
			require.NoError(t, repo.Upsert(context.Background(), runtime.Defaults(), nil))

			// Attempt to insert id=2 — CHECK constraint must reject.
			bad := database.AppConfigModel{
				ID:                 2,
				CronSchedule:       "0 0 * * *",
				AuthTrustedProxies: "[]",
				AuthLocalNetworks:  "[]",
				AuthMode:           "forms",
				OIDCScopes:         "[]",
				OIDCAllowedGroups:  "[]",
				OIDCGroupsClaim:    "groups",
				GUIDRewrites:       "[]",
				CreatedAt:          time.Now().UTC(),
				UpdatedAt:          time.Now().UTC(),
			}
			err := db.Create(&bad).Error
			require.Error(t, err, "CHECK id=1 must reject id=2")
		})
	}
}

// TestRuntimeConfigRepository_OIDCSecret_RoundTrip_AppSecretTable
// proves the OIDC client secret lands in app_secret(secret_name='oidc_client_secret'),
// NOT in app_config.
func TestRuntimeConfigRepository_OIDCSecret_RoundTrip_AppSecretTable(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			cipher, err := crypto.New("test-master-key-for-oidc-secret")
			require.NoError(t, err)
			repo := NewRuntimeConfigRepository(db, cipher)
			ctx := context.Background()

			// Seed app_config first so the singleton row exists.
			require.NoError(t, repo.Upsert(ctx, runtime.Defaults(), nil))

			require.NoError(t, repo.UpsertOIDCSecret(ctx, "super-secret-oidc"))

			// Inspect the storage: should be an app_secret row with secret_name='oidc_client_secret'.
			var stored database.AppSecretModel
			require.NoError(t, db.Where("secret_name = ?", "oidc_client_secret").
				Take(&stored).Error)
			assert.NotEmpty(t, stored.EncryptedValue)

			plaintext, err := repo.DecryptOIDCSecret(ctx)
			require.NoError(t, err)
			assert.Equal(t, "super-secret-oidc", plaintext)
		})
	}
}

func TestRuntimeConfigRepository_APIKey_RoundTrip_AppSecretTable(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			ct := []byte{0xCA, 0xFE, 0xBA, 0xBE}
			require.NoError(t, repo.SaveAPIKey(ctx, ct, true))

			var stored database.AppSecretModel
			require.NoError(t, db.Where("secret_name = ?", "api_key_probe").
				Take(&stored).Error)
			assert.Equal(t, ct, stored.EncryptedValue)

			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Equal(t, ct, row.APIKeyCiphertext)
			assert.True(t, row.APIKeyAutoGenerated)
		})
	}
}

// TestRuntimeConfigRepository_Get_NoAppSecret_ReturnsNilCiphertext
// confirms that a present app_config row with no companion app_secret
// rows lands a nil ciphertext on the row, not an error.
func TestRuntimeConfigRepository_Get_NoAppSecret_ReturnsNilCiphertext(t *testing.T) {
	t.Parallel()
	for _, backend := range testhelpers.AllBackends(t) {
		t.Run(backend.Name, func(t *testing.T) {
			t.Parallel()
			db := backend.NewDB(t)
			repo := NewRuntimeConfigRepository(db, nil)
			ctx := context.Background()

			require.NoError(t, repo.Upsert(ctx, runtime.Defaults(), nil))

			row, err := repo.Get(ctx)
			require.NoError(t, err)
			assert.Nil(t, row.APIKeyCiphertext)
			assert.Nil(t, row.OIDCClientSecretCiphertext)
		})
	}
}
