import { useEffect, useState } from 'react';
import { AlertTriangle, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useSession } from '@/lib/auth';
import { PasswordChangeDialog } from './PasswordChangeDialog';

const DISMISS_KEY = 'seasonfill.autogen_banner.dismissed';

export function AutoGenPasswordBanner() {
  const { data, isSuccess } = useSession();
  const [dismissed, setDismissed] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);

  useEffect(() => {
    try {
      setDismissed(sessionStorage.getItem(DISMISS_KEY) === '1');
    } catch {
      // sessionStorage may be unavailable (private mode / SSR) — silent fallback
    }
  }, []);

  if (!isSuccess || !data?.autoGenerated || dismissed) return null;

  const dismiss = () => {
    try { sessionStorage.setItem(DISMISS_KEY, '1'); } catch { /* ignore */ }
    setDismissed(true);
  };

  return (
    <>
      <div
        role="alert"
        className="flex items-center gap-3 px-4 py-2 bg-status-warning/10 border-b border-status-warning/40 text-status-warning text-[12.5px]"
      >
        <AlertTriangle className="w-4 h-4 shrink-0" aria-hidden="true" />
        <span className="flex-1">
          Auto-generated password is in use — please change it.
        </span>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => setDialogOpen(true)}
        >
          Change password
        </Button>
        <button
          type="button"
          aria-label="Dismiss banner"
          onClick={dismiss}
          className="grid place-items-center w-6 h-6 rounded hover:bg-status-warning/20"
        >
          <X className="w-3.5 h-3.5" />
        </button>
      </div>
      <PasswordChangeDialog open={dialogOpen} onOpenChange={setDialogOpen} />
    </>
  );
}
