import { describe, expect, it, vi, afterEach, beforeEach } from 'vitest';
import userEvent from '@testing-library/user-event';
import { screen } from '@testing-library/react';
import { renderWithProviders } from '@/test-utils';
import { AutoGenPasswordBanner } from './AutoGenPasswordBanner';
import * as auth from '@/lib/auth';

afterEach(() => { vi.restoreAllMocks(); sessionStorage.clear(); });
beforeEach(() => { sessionStorage.clear(); });

function mockSession(data: { username: string; autoGenerated: boolean } | null) {
  vi.spyOn(auth, 'useSession').mockReturnValue({
    data: data ?? undefined,
    isSuccess: data !== null,
    isPending: false,
    isError: false,
    error: null,
  } as unknown as ReturnType<typeof auth.useSession>);
}

describe('<AutoGenPasswordBanner />', () => {
  it('renders when session.autoGenerated=true', () => {
    mockSession({ username: 'admin', autoGenerated: true });
    renderWithProviders(<AutoGenPasswordBanner />);
    expect(screen.getByRole('alert')).toHaveTextContent(/auto-generated password/i);
    expect(screen.getByRole('button', { name: /change password/i })).toBeInTheDocument();
  });

  it('renders nothing when session.autoGenerated=false', () => {
    mockSession({ username: 'admin', autoGenerated: false });
    renderWithProviders(<AutoGenPasswordBanner />);
    expect(screen.queryByRole('alert')).not.toBeInTheDocument();
  });

  it('renders nothing while session is unresolved', () => {
    mockSession(null);
    renderWithProviders(<AutoGenPasswordBanner />);
    expect(screen.queryByRole('alert')).not.toBeInTheDocument();
  });

  it('hides after dismiss + persists in sessionStorage', async () => {
    mockSession({ username: 'admin', autoGenerated: true });
    const { unmount } = renderWithProviders(<AutoGenPasswordBanner />);
    await userEvent.click(screen.getByRole('button', { name: /dismiss banner/i }));
    expect(screen.queryByRole('alert')).not.toBeInTheDocument();
    unmount();
    renderWithProviders(<AutoGenPasswordBanner />);
    expect(screen.queryByRole('alert')).not.toBeInTheDocument();
  });
});
