import { describe, expect, it, vi, beforeEach, afterEach } from 'vitest';
import userEvent from '@testing-library/user-event';
import { screen, waitFor } from '@testing-library/react';
import { renderWithProviders } from '@/test-utils';
import { TopBar } from './TopBar';
import { InstanceFilterProvider } from '@/lib/instance-filter-context';
import { TooltipProvider } from '@/components/ui/tooltip';
import * as auth from '@/lib/auth';

const { navigateSpy, toastSpies } = vi.hoisted(() => ({
  navigateSpy: vi.fn(),
  toastSpies: { success: vi.fn(), error: vi.fn(), warning: vi.fn() },
}));
vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual<typeof import('react-router-dom')>('react-router-dom');
  return { ...actual, useNavigate: () => navigateSpy };
});
vi.mock('sonner', () => ({ toast: toastSpies }));

beforeEach(() => {
  Object.defineProperty(window, 'location', {
    writable: true, value: { pathname: '/', search: '', assign: vi.fn() },
  });
  globalThis.fetch = vi.fn().mockResolvedValue(new Response(JSON.stringify({
    instances: [
      { name: 'alpha', health: 'Available' },
      { name: 'beta',  health: 'UnavailableNetwork' },
    ],
  }), { status: 200, headers: { 'Content-Type': 'application/json' } })) as typeof fetch;
  vi.spyOn(auth, 'useSession').mockReturnValue({
    data: { username: 'admin', autoGenerated: false },
    isSuccess: true,
    isPending: false,
    isError: false,
    error: null,
  } as unknown as ReturnType<typeof auth.useSession>);
});
afterEach(() => {
  vi.restoreAllMocks();
  navigateSpy.mockReset(); toastSpies.success.mockReset(); toastSpies.error.mockReset();
});

// Local TooltipProvider with delayDuration=0 mirrors the production
// provider in main.tsx and keeps tooltip-open semantics synchronous-ish
// in unit tests. See SeriesGroup.test.tsx for the canonical pattern.
const ui = () => (
  <TooltipProvider delayDuration={0}>
    <InstanceFilterProvider><TopBar onMenuClick={() => {}} /></InstanceFilterProvider>
  </TooltipProvider>
);

describe('<TopBar />', () => {
  it('renders one chip per instance from useInstances()', async () => {
    renderWithProviders(ui());
    // Chip accessible name = visible instance name. The chip names ('alpha',
    // 'beta') are unique within TopBar, so screen-level findByRole is enough
    // — and crucially awaits the async React Query fetch that populates them.
    expect(await screen.findByRole('button', { name: 'alpha' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'beta' })).toBeInTheDocument();
  });

  it('colors the chip dot from health: green for Available, red for Unavailable*', async () => {
    renderWithProviders(ui());
    // The dot is the chip button's first child span. With capitalized
    // backend values, healthKind() maps Available→success (green) and the
    // Unavailable* family→danger (red). A lowercase revert would miss every
    // real value and fall through to neutral, failing both assertions.
    const alpha = await screen.findByRole('button', { name: 'alpha' });
    expect(alpha.querySelector('span')).toHaveClass('bg-status-success');

    const beta = screen.getByRole('button', { name: 'beta' });
    expect(beta.querySelector('span')).toHaveClass('bg-status-danger');
  });

  it('toggles aria-pressed when chip is clicked', async () => {
    renderWithProviders(ui());
    const chip = await screen.findByRole('button', { name: 'alpha' });
    expect(chip).toHaveAttribute('aria-pressed', 'false');
    await userEvent.click(chip);
    expect(chip).toHaveAttribute('aria-pressed', 'true');
  });

  it('logout calls auth.logout() and navigates to /login', async () => {
    const spy = vi.spyOn(auth, 'logout').mockResolvedValue(undefined);
    renderWithProviders(ui());
    await userEvent.click(screen.getByRole('button', { name: /account menu/i }));
    await userEvent.click(await screen.findByRole('menuitem', { name: /logout/i }));
    await waitFor(() => expect(spy).toHaveBeenCalled());
    expect(toastSpies.success).toHaveBeenCalledWith('Signed out');
    expect(navigateSpy).toHaveBeenCalledWith('/login', { replace: true });
  });

  it('account menu shows the session username as the label', async () => {
    renderWithProviders(ui());
    await userEvent.click(screen.getByRole('button', { name: /account menu/i }));
    expect(await screen.findByText('admin')).toBeInTheDocument();
  });

  it('clicking "Change password" opens the password-change dialog', async () => {
    renderWithProviders(ui());
    await userEvent.click(screen.getByRole('button', { name: /account menu/i }));
    await userEvent.click(await screen.findByRole('menuitem', { name: /change password/i }));
    expect(await screen.findByRole('dialog')).toBeInTheDocument();
    expect(screen.getByText(/set a new password/i)).toBeInTheDocument();
  });
});
