package runtimeconfig

import "time"

// Input is the parsed, typed representation of a PUT /config/runtime body.
// Wire-layer concerns (duration strings, JSON tags) belong in the handler;
// application layer works with Go types only.
type Input struct {
	Cron            CronInput
	Scan            ScanInput
	DryRun          bool
	GlobalRateLimit GlobalRateLimitInput
	Auth            AuthInput
}

type CronInput struct {
	Enabled  bool
	Schedule string
	OnStart  bool
	Jitter   time.Duration
}

type ScanInput struct {
	ShutdownGrace time.Duration
	CooldownSweep time.Duration
}

type GlobalRateLimitInput struct {
	RPM   int
	Burst int
}

type AuthInput struct {
	SessionTTL     time.Duration
	SecureCookie   bool
	TrustedProxies []string
	// Mode is one of runtime.AuthMode{Forms,Basic,None,OIDC}. Validated by
	// the usecase; rejected at the boundary so a bogus value never
	// reaches the dispatcher.
	Mode string
	// LocalBypass + LocalNetworks drive the local-address bypass.
	// Both are wired here so a single PUT applies the full set atomically.
	LocalBypass   bool
	LocalNetworks []string
	OIDC          OIDCInput
}

// OIDCInput is the wire-validated OIDC config. ClientSecret follows the
// dirty-bit pattern used for instance api_key:
//   - nil               → preserve existing ciphertext (no write)
//   - non-nil ""        → clear the stored ciphertext
//   - non-nil non-empty → encrypt and store
//
// Env OIDC_CLIENT_SECRET, when set, overrides DB at OIDC callback time.
type OIDCInput struct {
	Issuer        string
	ClientID      string
	ClientSecret  *string
	RedirectURL   string
	Scopes        []string
	UsernameClaim string
	AllowedGroups []string
	GroupsClaim   string
}

// Output is the typed representation returned by Get and Update.
// Handlers convert this to dto.RuntimeConfigDTO for serialization.
type Output struct {
	Cron                CronInput
	Scan                ScanInput
	DryRun              bool
	GlobalRateLimit     GlobalRateLimitInput
	Auth                AuthOutput
	AutoGeneratedAPIKey bool
	UpdatedAt           time.Time
}

// AuthOutput mirrors AuthInput plus the read-only SessionEpoch
// (managed by the usecase, never accepted from the client).
type AuthOutput struct {
	SessionTTL     time.Duration
	SecureCookie   bool
	TrustedProxies []string
	Mode           string
	LocalBypass    bool
	LocalNetworks  []string
	SessionEpoch   int64
	OIDC           OIDCOutput
}

type OIDCOutput struct {
	Issuer                  string
	ClientID                string
	RedirectURL             string
	Scopes                  []string
	UsernameClaim           string
	AllowedGroups           []string
	GroupsClaim             string
	ClientSecretConfigured  bool
	ClientSecretEnvOverride bool
}
