package runtimeconfig

import "time"

// Input is the parsed, typed representation of a PUT /config/runtime body.
// Wire-layer concerns (duration strings, JSON tags) belong in the handler;
// application layer works with Go types only.
type Input struct {
	Cron            CronInput
	Scan            ScanInput
	DryRun          bool
	GlobalRateLimit GlobalRateLimitInput
	Auth            AuthInput
	Security        SecurityInput
}

type CronInput struct {
	Enabled  bool
	Schedule string
	OnStart  bool
	Jitter   time.Duration
}

type ScanInput struct {
	ShutdownGrace time.Duration
	CooldownSweep time.Duration
}

type GlobalRateLimitInput struct {
	RPM   int
	Burst int
}

type AuthInput struct {
	SessionTTL     time.Duration
	SecureCookie   bool
	TrustedProxies []string
}

type SecurityInput struct {
	AllowPrivateTargets bool
}

// Output is the typed representation returned by Get and Update.
// Handlers convert this to dto.RuntimeConfigDTO for serialization.
type Output struct {
	Cron                CronInput
	Scan                ScanInput
	DryRun              bool
	GlobalRateLimit     GlobalRateLimitInput
	Auth                AuthInput
	Security            SecurityInput
	AutoGeneratedAPIKey bool
	UpdatedAt           time.Time
}
